FROM ubuntu:20.04

RUN apt update && apt install -y curl mariadb-client && \
    apt-get autoremove -y && \
    apt-get clean all && \
    rm -rf /var/lib/apt/lists/*

ARG DOLT_RELEASE="v1.53.5"
RUN curl -L https://github.com/dolthub/dolt/releases/download/${DOLT_RELEASE}/install.sh | bash

RUN dolt config --global --add user.name nautobot
RUN dolt config --global --add user.email opensource@networktocode.COM

RUN mkdir -p /var/lib/
WORKDIR /var/lib
RUN dolt sql -q "CREATE DATABASE nautobot CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
RUN dolt sql -q "CREATE DATABASE test_nautobot CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
RUN dolt sql -q "CREATE USER 'nautobot'@'%' IDENTIFIED BY 'decinablesprewad';"
RUN dolt sql -q "GRANT ALL PRIVILEGES ON *.* to 'nautobot'@'%';"

COPY ./development/dolt-config.yaml /var/lib/nautobot/dolt-config.yaml

EXPOSE 3306

RUN dolt sql -q "SET @@persist.join_complexity_limit = 13"
