# We can't remove volumes in a compose override, for the test configuration using the final containers
# we don't want the volumes so this is the default override file to add the volumes in the dev case
# any override will need to include these volumes to use them.
# see:  https://github.com/docker/compose/issues/3729
---
services:
  nautobot:
    volumes:
      - ./nautobot_config.py:/opt/nautobot/nautobot_config.py
      - ../:/source
  celery_worker:
    volumes:
      - ./nautobot_config.py:/opt/nautobot/nautobot_config.py
      - ../:/source
  celery_beat:
    volumes:
      - ./nautobot_config.py:/opt/nautobot/nautobot_config.py
      - ../:/source
  mkdocs:
    volumes:
      - ../:/source
  ui_build:
    image: "local/nautobot-dev:local-${NAUTOBOT_VER}-py${PYTHON_VER}"
    entrypoint: "bash -c 'npm --prefix /source/nautobot/ui run build:watch'"
    healthcheck:
      disable: true
    tty: true
    volumes:
      - ../.editorconfig:/source/.editorconfig
      - ../nautobot/ui/src:/source/nautobot/ui/src
      - ../nautobot/ui/.gitignore:/source/nautobot/ui/.gitignore
      - ../nautobot/ui/.node-version:/source/nautobot/ui/.node-version
      - ../nautobot/ui/.prettierignore:/source/nautobot/ui/.prettierignore
      - ../nautobot/ui/eslint.config.js:/source/nautobot/ui/eslint.config.js
      - ../nautobot/ui/package-lock.json:/source/nautobot/ui/package-lock.json
      - ../nautobot/ui/package.json:/source/nautobot/ui/package.json
      - ../nautobot/ui/prettier.config.js:/source/nautobot/ui/prettier.config.js
      - ../nautobot/ui/webpack.config.js:/source/nautobot/ui/webpack.config.js
      - ../nautobot/project-static/dist:/source/nautobot/project-static/dist
