# Used to run the final container images vs the dev containers
---
version: "3"
services:
  nautobot:
    build:
      target: final
    image: "networktocode/nautobot"
    ports:
      - 80:80
      - 443:443
  worker:
    image: "networktocode/nautobot"
