---
log_level: "info"

behavior:
  read_only: false
  autocommit: true

listener:
  host: "0.0.0.0"
  port: 3306
  max_connections: 128
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000
