# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_auto_20160517_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefix',
            name='status_new',
        ),
        migrations.RemoveField(
            model_name='vlan',
            name='status_new',
        ),
    ]
