# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0014_ipaddress_status_add_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlans', to='dcim.Site'),
        ),
        migrations.AlterField(
            model_name='vlangroup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlan_groups', to='dcim.Site'),
        ),
    ]
