# Generated by Django 3.1 on 2020-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prefix',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vlan',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vrf',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
