# Generated by Django 2.0.8 on 2018-10-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_api_tokens_squashed_0002_unicode_literals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={},
        ),
    ]
