# Generated by Django 3.1.7 on 2021-03-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0004_initial_part_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="ansible_connection",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
