# Generated by Django 3.1.8 on 2021-05-07 22:13

from django.db import migrations
import nautobot.utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0004_initial_part_4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="time_zone",
            field=nautobot.utilities.fields.TimeZoneField(blank=True),
        ),
    ]
