from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields

# From 0005_device_local_context_schema
# Generated by Django 3.1.12 on 2021-06-16 02:42

# From 0006_auto_slug
# Generated by Django 3.1.13 on 2021-08-05 19:24

# From 0007_device_secrets_group
# Generated by Django 3.1.13 on 2021-11-15 13:10

# From 0008_increase_all_serial_lengths
# Generated by Django 3.1.14 on 2021-12-21 21:20


class Migration(migrations.Migration):
    replaces = [
        ("dcim", "0005_device_local_context_schema"),
        ("dcim", "0006_auto_slug"),
        ("dcim", "0007_device_secrets_group"),
        ("dcim", "0008_increase_all_serial_lengths"),
    ]

    dependencies = [
        ("extras", "0007_configcontextschema"),
        ("dcim", "0004_initial_part_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="local_context_schema",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.configcontextschema"
            ),
        ),
        migrations.AlterField(
            model_name="devicerole",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="model", unique=None
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="rackgroup",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=None
            ),
        ),
        migrations.AlterField(
            model_name="rackrole",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="secrets_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="extras.secretsgroup",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="serial",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rack",
            name="serial",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
