# Generated by Django 3.1.13 on 2021-08-03 04:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0005_device_local_context_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicerole",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="model"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="rackgroup",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="rackrole",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
    ]
