# Generated by Django 3.1.13 on 2021-11-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0016_secret"),
        ("dcim", "0006_auto_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="secrets_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="extras.secretsgroup",
            ),
        ),
    ]
