from django.db import migrations, models
import nautobot.core.models.fields
import nautobot.core.models.ordering
from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.statuses
from nautobot.dcim.choices import InterfaceStatusChoices
from nautobot.extras.management import clear_status_choices, populate_status_choices
import django.core.serializers.json
import nautobot.extras.models.mixins
import nautobot.extras.utils
import taggit.managers
import uuid


# From 0009_add_natural_indexing
# Generated by Django 3.2.12 on 2022-04-14 20:45

# From 0010_interface_status
# Generated by Django 3.2.13 on 2022-05-04 21:21

# From 0011_interface_status_data_migration
# Generated by Django 3.1.14 on 2022-03-19 23:21



def populate_interface_status(apps, schema_editor):
    """
    Create/link default Status records for the Interface content-type, and default all Interfaces to "active" status.
    """
    # Create Interface Statuses and add dcim.Interface to its content_types
    populate_status_choices(apps, schema_editor, models=["dcim.Interface"])

    Status = apps.get_model("extras.Status")
    Interface = apps.get_model("dcim.Interface")

    # populate existing interfaces status
    active_status = Status.objects.get(slug=InterfaceStatusChoices.STATUS_ACTIVE)
    for interface in Interface.objects.all():
        interface.status = active_status
        interface.save()


def clear_interface_status(apps, schema_editor):
    """
    Clear the status field on all Interfaces, and de-link/delete all Status records from the Interface content-type.
    """
    Interface = apps.get_model("dcim.Interface")

    for interface in Interface.objects.filter(status__isnull=False):
        interface.status = None
        interface.save()

    clear_status_choices(apps, schema_editor, models=["dcim.Interface"])

# From 0012_interface_parent_bridge
# Generated by Django 3.2.12 on 2022-04-18 08:00

# From 0013_location_location_type
# Generated by Django 3.2.13 on 2022-06-15 14:00


class Migration(migrations.Migration):

    replaces = [
        ("dcim", "0009_add_natural_indexing"),
        ("dcim", "0010_interface_status"),
        ("dcim", "0011_interface_status_data_migration"),
        ("dcim", "0012_interface_parent_bridge"),
        ("dcim", "0013_location_location_type"),
    ]

    dependencies = [
        ("dcim", "0008_increase_all_serial_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="interface",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="serial",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="powerpanel",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="rack",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="rack",
            name="serial",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rackgroup",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize_interface,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="virtualchassis",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),

        migrations.AddField(
            model_name="interface",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dcim_interface_related",
                to="extras.status",
            ),
        ),

        migrations.RunPython(populate_interface_status, clear_interface_status),

        migrations.AddField(
            model_name="interface",
            name="parent_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_interfaces",
                to="dcim.interface",
            ),
        ),
        migrations.AddField(
            model_name="interface",
            name="bridge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bridged_interfaces",
                to="dcim.interface",
            ),
        ),

        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    nautobot.core.models.fields.AutoSlugField(
                        blank=True, max_length=100, populate_from="name", unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "content_types",
                    models.ManyToManyField(
                        limit_choices_to=nautobot.extras.utils.FeatureQuery("locations"),
                        related_name="location_types",
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dcim.locationtype",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "_name",
                    nautobot.core.models.fields.NaturalOrderingField(
                        "name",
                        blank=True,
                        db_index=True,
                        max_length=100,
                        naturalize_function=nautobot.core.models.ordering.naturalize,
                    ),
                ),
                (
                    "slug",
                    nautobot.core.models.fields.AutoSlugField(
                        blank=True, max_length=100, populate_from=["parent__slug", "name"], unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "location_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="locations", to="dcim.locationtype"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dcim.location",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="dcim.site",
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dcim_location_related",
                        to="extras.status",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("_name",),
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin),
        ),
        migrations.AddField(
            model_name="device",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="dcim.location",
            ),
        ),
        migrations.AddField(
            model_name="powerpanel",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="powerpanels",
                to="dcim.location",
            ),
        ),
        migrations.AddField(
            model_name="rack",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="racks",
                to="dcim.location",
            ),
        ),
        migrations.AddField(
            model_name="rackgroup",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rack_groups",
                to="dcim.location",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("parent", "name")},
        ),
    ]
