# Generated by Django 3.2.12 on 2022-04-14 20:45

from django.db import migrations, models
import nautobot.utilities.ordering
import nautobot.utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0008_increase_all_serial_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
