# Generated by Django 3.2.12 on 2022-04-14 20:45

from django.db import migrations, models
import nautobot.utilities.ordering
import nautobot.utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0008_increase_all_serial_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="interface",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="serial",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="powerpanel",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="rack",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="rack",
            name="serial",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rackgroup",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize_interface,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="_name",
            field=nautobot.utilities.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.utilities.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="virtualchassis",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
