# Generated by Django 3.2.13 on 2022-06-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0013_locations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="locationtype",
            options={"ordering": ("name",)},
        ),
    ]
