import uuid

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers

import nautobot.core.models.fields
from nautobot.extras.management import clear_status_choices, populate_status_choices
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses

# From 0014_location_status_data_migration
# Generated by Django 3.1.14 on 2022-03-19 23:21


def populate_location_status(apps, schema_editor):
    """Create/link default Status records for the Location content-type."""
    populate_status_choices(apps, schema_editor, models=["dcim.Location"])


def clear_location_status(apps, schema_editor):
    """De-link/delete all Status records from the Location content-type."""
    clear_status_choices(apps, schema_editor, models=["dcim.Location"])


# From 0015_device_components__changeloggedmodel
# Generated by Django 3.2.15 on 2022-09-27 17:24

# From 0016_device_components__timestamp_data_migration
# Generated by Django 3.1.14 on 2022-03-19 23:21


# Models that need to share their parent's timestamps.
COMPONENT_MODELS = [
    "dcim.consoleport",
    "dcim.consoleporttemplate",
    "dcim.consoleserverport",
    "dcim.consoleserverporttemplate",
    "dcim.devicebay",
    "dcim.devicebaytemplate",
    "dcim.frontport",
    "dcim.frontporttemplate",
    "dcim.interface",
    "dcim.interfacetemplate",
    "dcim.inventoryitem",
    "dcim.poweroutlet",
    "dcim.poweroutlettemplate",
    "dcim.powerport",
    "dcim.powerporttemplate",
    "dcim.rearport",
    "dcim.rearporttemplate",
]


def populate_device_component_timestamps(apps, schema_editor):
    """
    Set created/last_updated fields of existing components to None, rather than the time of the migration.
    """
    for model_path in COMPONENT_MODELS:
        model = apps.get_model(model_path)
        model.objects.all().update(created=None, last_updated=None)


# From 0017_locationtype_nestable
# Generated by Django 3.2.15 on 2022-10-13 16:24

# From 0018_device_redundancy_group
# Generated by Django 3.2.16 on 2022-10-28 17:25


class Migration(migrations.Migration):
    replaces = [
        ("dcim", "0014_location_status_data_migration"),
        ("dcim", "0015_device_components__changeloggedmodel"),
        ("dcim", "0016_device_components__timestamp_data_migration"),
        ("dcim", "0017_locationtype_nestable"),
        ("dcim", "0018_device_redundancy_group"),
    ]

    dependencies = [
        ("dcim", "0013_location_location_type"),
    ]

    operations = [
        migrations.RunPython(populate_location_status, clear_location_status),
        migrations.AddField(
            model_name="consoleport",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="consoleport",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="consoleporttemplate",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="consoleporttemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="consoleserverport",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="consoleserverport",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="consoleserverporttemplate",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="consoleserverporttemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="devicebay",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="devicebay",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="devicebaytemplate",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="devicebaytemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="frontport",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="frontport",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="frontporttemplate",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="frontporttemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="interface",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="interface",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="interfacetemplate",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="interfacetemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="poweroutlet",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="poweroutlet",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="poweroutlettemplate",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="poweroutlettemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="powerport",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="powerport",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="powerporttemplate",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="powerporttemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="rearport",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="rearport",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="rearporttemplate",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="rearporttemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(populate_device_component_timestamps, migrations.RunPython.noop),
        migrations.AddField(
            model_name="locationtype",
            name="nestable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="device_redundancy_group_priority",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.CreateModel(
            name="DeviceRedundancyGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    nautobot.core.models.fields.AutoSlugField(
                        blank=True, max_length=100, populate_from="name", unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("failover_strategy", models.CharField(blank=True, max_length=50)),
                ("comments", models.TextField(blank=True)),
                (
                    "secrets_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="extras.secretsgroup",
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dcim_deviceredundancygroup_related",
                        to="extras.status",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="device_redundancy_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="dcim.deviceredundancygroup",
            ),
        ),
    ]
