# Generated by Django 3.2.20 on 2023-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0019_device_redundancy_group_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="network_driver",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
