# Generated by Django 3.2.16 on 2022-11-25 11:45

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.roles
from nautobot.extras.utils import migrate_role_data


def migrate_data_from_legacy_role_to_new_role(apps, schema):
    """Copy record from role to temp_role"""

    model = apps.get_model("dcim", "Device")
    role_model = apps.get_model("extras", "Role")
    migrate_role_data(model=model, role_model=role_model)


def reverse_role_data_migrate(apps, schema):
    """Reverse changes made to new_role"""

    model = apps.get_model("dcim", "Device")
    device_role_model = apps.get_model("dcim", "DeviceRole")
    migrate_role_data(
        model=model,
        role_model=device_role_model,
        legacy_role="new_role",
        new_role="legacy_role",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0020_alter_device_role_add_new_role"),
    ]

    operations = [
        migrations.RunPython(migrate_data_from_legacy_role_to_new_role, reverse_role_data_migrate),
    ]
