# Generated by Django 3.2.16 on 2022-11-25 11:45

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.roles


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0021_migrate_device_role_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="new_role",
            new_name="role",
        ),
    ]
