# Generated by Django 3.2.16 on 2023-01-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0023_alter_interface_mac_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="local_context_data",
            new_name="local_config_context_data",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="local_context_data_owner_content_type",
            new_name="local_config_context_data_owner_content_type",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="local_context_data_owner_object_id",
            new_name="local_config_context_data_owner_object_id",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="local_context_schema",
            new_name="local_config_context_schema",
        ),
        migrations.RenameField(
            model_name="interface",
            old_name="parent_interface",
            new_name="parent",
        ),
        migrations.AlterField(
            model_name="interface",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="dcim.interface",
            ),
        ),
    ]
