# Generated by Django 3.2.16 on 2022-11-25 11:45

from django.db import migrations
from nautobot.extras.utils import migrate_role_data


def migrate_data_from_legacy_role_to_new_role(apps, schema):
    """Copy data from legacy_role to new_role."""
    new_role_model = apps.get_model("extras", "Role")
    for model_name in ("Device", "Rack"):
        model = apps.get_model("dcim", model_name)
        legacy_role_model = apps.get_model("dcim", f"{model_name}Role")
        migrate_role_data(
            model_to_migrate=model,
            legacy_role_model=legacy_role_model,
            new_role_model=new_role_model,
        )


def reverse_role_data_migrate(apps, schema):
    """Reverse changes made to new_role"""
    legacy_role_model = apps.get_model("extras", "Role")
    for model_name in ("Device", "Rack"):
        model = apps.get_model("dcim", model_name)
        new_role_model = apps.get_model("dcim", f"{model_name}Role")
        migrate_role_data(
            model_to_migrate=model,
            legacy_role_field_name="new_role",
            legacy_role_model=legacy_role_model,
            new_role_field_name="legacy_role",
            new_role_model=new_role_model,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0024_alter_device_and_rack_role_add_new_role"),
    ]

    operations = [
        migrations.RunPython(migrate_data_from_legacy_role_to_new_role, reverse_role_data_migrate),
    ]
