# Generated by Django 3.2.17 on 2023-02-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0032_remove_site_foreign_key_from_dcim_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="region",
        ),
        migrations.RemoveField(
            model_name="site",
            name="status",
        ),
        migrations.RemoveField(
            model_name="site",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="site",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
        migrations.DeleteModel(
            name="Site",
        ),
    ]
