# Generated by Django 3.2.17 on 2023-02-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0033_created_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='region',
        ),
        migrations.RemoveField(
            model_name='site',
            name='status',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
