# Generated by Django 3.2.16 on 2023-01-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0034_migrate_region_and_site_data_to_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consoleport",
            name="_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dcim_consoleport_related",
                to="dcim.cablepath",
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dcim_consoleserverport_related",
                to="dcim.cablepath",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dcim_interface_related",
                to="dcim.cablepath",
            ),
        ),
        migrations.AlterField(
            model_name="powerfeed",
            name="_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dcim_powerfeed_related",
                to="dcim.cablepath",
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dcim_poweroutlet_related",
                to="dcim.cablepath",
            ),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dcim_powerport_related",
                to="dcim.cablepath",
            ),
        ),
    ]
