# Generated by Django 3.2.18 on 2023-03-14 19:40

from django.db import migrations
import nautobot.dcim.models.locations


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0036_remove_region_and_site"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="location",
            managers=[
                ("objects", nautobot.dcim.models.locations.LocationQuerySet.as_manager()),
            ],
        ),
    ]
