# Generated by Django 3.2.18 on 2023-03-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0023_delete_aggregate'),
        ('dcim', '0036_remove_region_and_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='ipam.vrf'),
        ),
    ]
