# Generated by Django 3.2.18 on 2023-03-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0037_interface_ip_addresses_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceredundancygroup",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="slug",
        ),
    ]
