# Generated by Django 3.2.18 on 2023-03-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0024_interface_to_ipaddress_m2m"),
        ("dcim", "0040_remove_region_and_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="ip_addresses",
            field=models.ManyToManyField(
                blank=True, related_name="interfaces", through="ipam.IPAddressToInterface", to="ipam.IPAddress"
            ),
        ),
    ]
