from django.db import migrations
import django.db.models.deletion

from nautobot.core.choices import ColorChoices
import nautobot.extras.models.roles
import nautobot.extras.models.statuses
from nautobot.extras.utils import fixup_null_statuses


# From 0046_fixup_null_statuses
def fixup_null_roles(apps, schema):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Device = apps.get_model("dcim", "Device")
    device_ct = ContentType.objects.get_for_model(Device)
    Role = apps.get_model("extras", "Role")
    instances_to_fixup = Device.objects.filter(role__isnull=True)
    if instances_to_fixup.exists():
        null_role, _ = Role.objects.get_or_create(
            name="NULL",
            defaults={
                "color": ColorChoices.COLOR_BLACK,
                "description": "Created by Nautobot to replace invalid null references",
            },
        )
        null_role.content_types.add(device_ct)
        updated_count = instances_to_fixup.update(role=null_role)
        print(f"    Found and fixed {updated_count} instances of Device that had null 'role' field.")


def migrate_null_statuses(apps, schema):
    status_model = apps.get_model("extras", "Status")
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model_name in (
        "Cable",
        "Device",
        "DeviceRedundancyGroup",
        "Interface",
        "Location",
        "PowerFeed",
        "Rack",
    ):
        model = apps.get_model("dcim", model_name)
        model_ct = ContentType.objects.get_for_model(model)
        fixup_null_statuses(model=model, model_contenttype=model_ct, status_model=status_model)


# From 0047_status_nonnullable
# Generated by Django 3.2.18 on 2023-05-19 18:05


class Migration(migrations.Migration):
    replaces = [
        ("dcim", "0046_fixup_null_statuses"),
        ("dcim", "0047_status_nonnullable"),
    ]

    dependencies = [
        ("dcim", "0045_ipam__namespaces"),
    ]

    operations = [
        migrations.RunPython(migrate_null_statuses, migrations.RunPython.noop),
        migrations.RunPython(fixup_null_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cable",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="cables", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                on_delete=django.db.models.deletion.PROTECT, related_name="devices", to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="devices", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="deviceredundancygroup",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="device_redundancy_groups", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="interfaces", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="locations", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="powerfeed",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="power_feeds", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="racks", to="extras.status"
            ),
        ),
    ]
