# Generated by Django 3.2.20 on 2023-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0045_remove_slugs_and_change_device_primary_ip_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
