# Generated by Django 3.2.18 on 2023-05-19 18:05

from django.db import migrations
import django.db.models.deletion

import nautobot.extras.models.roles
import nautobot.extras.models.statuses


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0084_rename_computed_field_slug_to_key"),
        ("dcim", "0046_fixup_null_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cable",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="cables", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                on_delete=django.db.models.deletion.PROTECT, related_name="devices", to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="devices", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="deviceredundancygroup",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="device_redundancy_groups", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="interfaces", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="locations", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="powerfeed",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="power_feeds", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="racks", to="extras.status"
            ),
        ),
    ]
