from django.db import migrations, models
from nautobot.core.utils.migrations import check_for_duplicates_with_natural_key_fields_in_migration
import django.db.models.deletion


# From 0048_ensure_virtual_chassis_names_are_unique_and_add_uniqueness_constraint
# Generated by Django 3.2.18 on 2023-06-06 21:12




def ensure_virtual_chassis_names_are_all_unique(apps, schema_editor):
    VirtualChassis = apps.get_model("dcim", "VirtualChassis")
    check_for_duplicates_with_natural_key_fields_in_migration(VirtualChassis, ["name"])

# From 0049_remove_slugs_and_change_device_primary_ip_fields
# Generated by Django 3.2.18 on 2023-06-12 22:19


class Migration(migrations.Migration):

    replaces = [
        ("dcim", "0048_ensure_virtual_chassis_names_are_unique_and_add_uniqueness_constraint"),
        ("dcim", "0049_remove_slugs_and_change_device_primary_ip_fields"),
    ]

    dependencies = [
        ("dcim", "0047_status_nonnullable"),
    ]

    operations = [
        migrations.RunPython(ensure_virtual_chassis_names_are_all_unique, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="virtualchassis",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),

        migrations.RemoveField(
            model_name="location",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="locationtype",
            name="slug",
        ),
        migrations.AlterUniqueTogether(
            name="devicetype",
            unique_together={("manufacturer", "model")},
        ),
        migrations.AlterUniqueTogether(
            name="rackgroup",
            unique_together={("location", "name")},
        ),
        migrations.RemoveField(
            model_name="devicetype",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="rackgroup",
            name="slug",
        ),
        migrations.AlterField(
            model_name="device",
            name="primary_ip4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_ip4_for",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="primary_ip6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_ip6_for",
                to="ipam.ipaddress",
            ),
        ),
    ]
