from django.db import migrations
from nautobot.extras.management import clear_status_choices, populate_status_choices
from django.db import migrations, models
import nautobot.core.models.fields
import nautobot.core.models.ordering
import uuid
import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.tree_queries
import nautobot.extras.models.mixins
import nautobot.extras.models.roles
import nautobot.extras.models.statuses
import nautobot.extras.utils


# From 0055_softwareimage_softwareversion_data_migration

# From 0056_update_all_charfields_max_length_to_255
# Generated by Django 3.2.24 on 2024-02-29 07:45

# From 0057_controller_models
# Generated by Django 3.2.24 on 2024-03-22 15:36

# From 0058_controller_data_migration

# From 0059_add_role_field_to_interface_models
# Generated by Django 3.2.25 on 2024-04-01 13:36

# From 0060_alter_cable_status_alter_consoleport__path_and_more
# Generated by Django 4.2.9 on 2024-01-17 18:52

# From 0055_softwareimage_softwareversion_data_migration
def populate_software_status_choices(apps, schema_editor):
    """Create default Status records for the SoftwareImageFile and SoftwareVersion models."""
    populate_status_choices(apps, schema_editor, models=["dcim.SoftwareImageFile", "dcim.SoftwareVersion"])


def clear_software_status_choices(apps, schema_editor):
    """Remove default Status records for the SoftwareImageFile and SoftwareVersion models."""
    clear_status_choices(apps, schema_editor, models=["dcim.SoftwareImageFile", "dcim.SoftwareVersion"])

# From 0058_controller_data_migration
def populate_controller_status_choices(apps, schema_editor):
    """Create default Status records for the Controller model."""
    populate_status_choices(apps, schema_editor, models=["dcim.Controller"])


def clear_controller_status_choices(apps, schema_editor):
    """Remove default Status records for the Controller model."""
    clear_status_choices(apps, schema_editor, models=["dcim.Controller"])


class Migration(migrations.Migration):

    replaces = [
        ("dcim", "0055_softwareimage_softwareversion_data_migration"),
        ("dcim", "0056_update_all_charfields_max_length_to_255"),
        ("dcim", "0057_controller_models"),
        ("dcim", "0058_controller_data_migration"),
        ("dcim", "0059_add_role_field_to_interface_models"),
        ("dcim", "0060_alter_cable_status_alter_consoleport__path_and_more"),
    ]

    dependencies = [
        ("contenttypes", "0001_initial"),
        ("extras", "0001_initial_part_1"),
        ("dcim", "0054_softwareimage_softwareversion"),
    ]

    operations = [

        migrations.RunPython(populate_software_status_choices, clear_software_status_choices),


        migrations.AlterField(
            model_name="cable",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="device",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deviceredundancygroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="deviceredundancygroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="model",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="part_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="devicefamily",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicefamily",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="interface",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize_interface,
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interface",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interface",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfaceredundancygroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfaceredundancygroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="interfaceredundancygroup",
            name="protocol_group_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize_interface,
            ),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="part_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="facility",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="locationtype",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="locationtype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="napalm_driver",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="platform",
            name="network_driver",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerfeed",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="powerpanel",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rack",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rack",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rackgroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rackgroup",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rackreservation",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="virtualchassis",
            name="domain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="virtualchassis",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),


        migrations.CreateModel(
            name="Controller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "controller_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controllers",
                        to="dcim.device",
                    ),
                ),
                (
                    "controller_device_redundancy_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controllers",
                        to="dcim.deviceredundancygroup",
                    ),
                ),
                (
                    "external_integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controllers",
                        to="extras.externalintegration",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="controllers", to="dcim.location"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controllers",
                        to="dcim.platform",
                    ),
                ),
                (
                    "role",
                    nautobot.extras.models.roles.RoleField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controllers",
                        to="extras.role",
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="controllers", to="extras.status"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controllers",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),
        migrations.CreateModel(
            name="ControllerManagedDeviceGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("weight", models.PositiveIntegerField(default=1000)),
                (
                    "controller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controller_managed_device_groups",
                        to="dcim.controller",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dcim.controllermanageddevicegroup",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("weight",),
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
            managers=[
                ("objects", nautobot.core.models.tree_queries.TreeManager()),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="controller_managed_device_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="dcim.controllermanageddevicegroup",
            ),
        ),


        migrations.RunPython(populate_controller_status_choices, clear_controller_status_choices),


        migrations.AddField(
            model_name="interface",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interfaces",
                to="extras.role",
            ),
        ),


        migrations.AlterField(
            model_name="cable",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.cablepath"
            ),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.cablepath"
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="controller",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="controller",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="local_config_context_data_owner_content_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True,
                default=None,
                limit_choices_to=nautobot.extras.utils.FeatureQuery("config_context_owners"),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="local_config_context_schema",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.configcontextschema"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="role",
            field=nautobot.extras.models.roles.RoleField(on_delete=django.db.models.deletion.PROTECT, to="extras.role"),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="deviceredundancygroup",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.cablepath"
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="interfaceredundancygroup",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="powerfeed",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.cablepath"
            ),
        ),
        migrations.AlterField(
            model_name="powerfeed",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.cablepath"
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.cablepath"
            ),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.device"
            ),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="softwareimagefile",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="softwareversion",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
    ]
