# Generated by Django 3.2.23 on 2024-01-22 19:30

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0055_softwareimage_softwareversion_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItemToSoftwareImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_image_mappings",
                        to="dcim.inventoryitem",
                    ),
                ),
                (
                    "software_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_item_mappings",
                        to="dcim.softwareimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item to Software Image mapping",
                "verbose_name_plural": "Inventory Item to Software Image mappings",
                "unique_together": {("inventory_item", "software_image")},
            },
        ),
        migrations.CreateModel(
            name="DeviceTypeToSoftwareImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_image_mappings",
                        to="dcim.devicetype",
                    ),
                ),
                (
                    "software_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_type_mappings",
                        to="dcim.softwareimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Type to Software Image mapping",
                "verbose_name_plural": "Device Type to Software Image mappings",
                "unique_together": {("device_type", "software_image")},
            },
        ),
        migrations.AddField(
            model_name="devicetype",
            name="software_images",
            field=models.ManyToManyField(
                blank=True,
                related_name="device_types",
                through="dcim.DeviceTypeToSoftwareImage",
                to="dcim.SoftwareImage",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="software_images",
            field=models.ManyToManyField(
                blank=True,
                related_name="inventory_items",
                through="dcim.InventoryItemToSoftwareImage",
                to="dcim.SoftwareImage",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="software_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="dcim.softwareimage",
            ),
        ),
    ]
