# Generated by Django 3.2.24 on 2024-02-29 07:45

from django.db import migrations, models

import nautobot.core.models.fields
import nautobot.core.models.ordering


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0055_softwareimage_softwareversion_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cable",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consoleserverporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="device",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebay",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicebaytemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deviceredundancygroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="deviceredundancygroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="model",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="part_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="frontporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="devicefamily",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="devicefamily",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="interface",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize_interface,
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interface",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interface",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfaceredundancygroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfaceredundancygroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="interfaceredundancygroup",
            name="protocol_group_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize_interface,
            ),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="interfacetemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="part_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="facility",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="locationtype",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="locationtype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="napalm_driver",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="platform",
            name="network_driver",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerfeed",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="poweroutlettemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="powerpanel",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rack",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rack",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rackgroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rackgroup",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rackreservation",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize,
            ),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name", blank=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize
            ),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rearporttemplate",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="virtualchassis",
            name="domain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="virtualchassis",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
