# Generated by Django 4.2.15 on 2024-10-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wireless", "0001_initial"),
        ("dcim", "0064_virtualdevicecontext_status_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="access_point_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="wireless.accesspointgroup",
            ),
        ),
    ]
