# Generated by Django 4.2.16 on 2024-11-05 13:48

from django.db import migrations, models

import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0064_virtualdevicecontext_status_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="capabilities",
            field=nautobot.core.models.fields.JSONArrayField(base_field=models.CharField(), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controllermanageddevicegroup",
            name="capabilities",
            field=nautobot.core.models.fields.JSONArrayField(base_field=models.CharField(), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controllermanageddevicegroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
