# Generated by Django 4.2.15 on 2024-09-17 06:04

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0064_virtualdevicecontext_status_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interface",
            name="virtual_device_contexts",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="dcim.virtualdevicecontext",
            ),
        ),
        migrations.CreateModel(
            name="VirtualDeviceContextInterfaceAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_device_context_assignments",
                        to="dcim.interface",
                    ),
                ),
                (
                    "virtual_device_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface_assignments",
                        to="dcim.virtualdevicecontext",
                    ),
                ),
            ],
            options={
                "ordering": ["virtual_device_context", "interface"],
                "unique_together": {("virtual_device_context", "interface")},
            },
        ),
        migrations.AddField(
            model_name="virtualdevicecontext",
            name="interfaces",
            field=models.ManyToManyField(
                blank=True,
                related_name="virtual_device_contexts",
                through="dcim.VirtualDeviceContextInterfaceAssignment",
                to="dcim.virtualdevicecontext",
            ),
        ),
    ]
