# Generated by Django 4.2.16 on 2024-10-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0064_virtualdevicecontext_status_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllermanageddevicegroup',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
