# Generated by Django 4.2.16 on 2024-10-25 16:13

from django.db import migrations, models

import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0065_device_access_point_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="capabilities",
            field=nautobot.core.models.fields.JSONArrayField(base_field=models.CharField(), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controllermanageddevicegroup",
            name="capabilities",
            field=nautobot.core.models.fields.JSONArrayField(base_field=models.CharField(), blank=True, null=True),
        ),
    ]
