from django.db import migrations, models
import django.db.models.deletion

# From 0066_controllermanageddevicegroup_radio_profiles_and_more
# Generated by Django 4.2.16 on 2024-11-05 13:48

# From 0067_controllermanageddevicegroup_tenant
# Generated by Django 4.2.16 on 2024-11-21 12:35


class Migration(migrations.Migration):
    replaces = [
        ("dcim", "0066_controllermanageddevicegroup_radio_profiles_and_more"),
        ("dcim", "0067_controllermanageddevicegroup_tenant"),
    ]

    dependencies = [
        ("wireless", "0001_initial"),
        ("dcim", "0065_controller_capabilities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controllermanageddevicegroup",
            name="radio_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="controller_managed_device_groups",
                through="wireless.ControllerManagedDeviceGroupRadioProfileAssignment",
                to="wireless.radioprofile",
            ),
        ),
        migrations.AddField(
            model_name="controllermanageddevicegroup",
            name="wireless_networks",
            field=models.ManyToManyField(
                blank=True,
                related_name="controller_managed_device_groups",
                through="wireless.ControllerManagedDeviceGroupWirelessNetworkAssignment",
                to="wireless.wirelessnetwork",
            ),
        ),
        migrations.AddField(
            model_name="controllermanageddevicegroup",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="controller_managed_device_groups",
                to="tenancy.tenant",
            ),
        ),
    ]
