# Generated by Django 4.2.16 on 2024-10-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0065_controllermanageddevicegroup_description'),
        ('wireless', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllermanageddevicegroup',
            name='radio_profiles',
            field=models.ManyToManyField(blank=True, related_name='controller_managed_device_groups', through='wireless.ControllerManagedDeviceGroupRadioProfileAssignment', to='wireless.radioprofile'),
        ),
        migrations.AddField(
            model_name='controllermanageddevicegroup',
            name='wireless_networks',
            field=models.ManyToManyField(blank=True, related_name='controller_managed_device_groups', through='wireless.ControllerManagedDeviceGroupWirelessNetworkAssignment', to='wireless.wirelessnetwork'),
        ),
    ]
