# Generated by Django 4.2.15 on 2024-09-17 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0065_alter_interface_virtual_device_contexts_and_more"),
    ]

    operations = []
