# Generated by Django 4.2.15 on 2024-09-17 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0066_vdc_interface_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interface",
            name="obsolete_vdcs",
        ),
    ]
