# Generated by Django 4.2.19 on 2025-03-06 19:34

from django.db import migrations

import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0067_controllermanageddevicegroup_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softwareimagefile",
            name="download_url",
            field=nautobot.core.models.fields.LaxURLField(blank=True),
        ),
    ]
