from django.db import migrations
import nautobot.core.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import django.core.serializers.json
import nautobot.extras.models.mixins
import nautobot.core.models.query_functions
import django.core.validators
from decimal import Decimal


# From 0068_alter_softwareimagefile_download_url
# Generated by Django 4.2.19 on 2025-03-06 19:34

# From 0069_softwareimagefile_external_integration
# Generated by Django 4.2.20 on 2025-03-11 19:10

# From 0070_modulefamily_models
# Generated by Django 4.2.19 on 2025-03-18 17:22

# From 0071_alter_consoleport_options_and_more
# Generated by Django 4.2.20 on 2025-07-17 20:24

# From 0072_alter_powerfeed_options_and_more
# Generated by Django 4.2.23 on 2025-08-11 21:07

# From 0073_alter_powerport_power_factor_and_more
# Generated by Django 4.2.23 on 2025-08-22 21:03

# From 0074_alter_rack_u_height
# Generated by Django 4.2.24 on 2025-09-17 08:28

class Migration(migrations.Migration):

    replaces = [
        ("dcim", "0068_alter_softwareimagefile_download_url"),
        ("dcim", "0069_softwareimagefile_external_integration"),
        ("dcim", "0070_modulefamily_models"),
        ("dcim", "0071_alter_consoleport_options_and_more"),
        ("dcim", "0072_alter_powerfeed_options_and_more"),
        ("dcim", "0073_alter_powerport_power_factor_and_more"),
        ("dcim", "0074_alter_rack_u_height"),
    ]

    dependencies = [
        ("dcim", "0067_controllermanageddevicegroup_tenant"),
    ]

    operations = [

        migrations.AlterField(
            model_name="softwareimagefile",
            name="download_url",
            field=nautobot.core.models.fields.LaxURLField(blank=True),
        ),


        migrations.AddField(
            model_name="softwareimagefile",
            name="external_integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="software_image_files",
                to="extras.externalintegration",
            ),
        ),


        migrations.AddField(
            model_name="modulebay",
            name="requires_first_party_modules",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modulebaytemplate",
            name="requires_first_party_modules",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ModuleFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name_plural": "module families",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="modulebay",
            name="module_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="module_bays",
                to="dcim.modulefamily",
            ),
        ),
        migrations.AddField(
            model_name="modulebaytemplate",
            name="module_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="module_bay_templates",
                to="dcim.modulefamily",
            ),
        ),
        migrations.AddField(
            model_name="moduletype",
            name="module_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="module_types",
                to="dcim.modulefamily",
            ),
        ),


        migrations.AlterModelOptions(
            name="consoleport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="consoleserverport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="frontport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="interface",
            options={"ordering": ("device", "module__id", nautobot.core.models.query_functions.CollateAsChar("_name"))},
        ),
        migrations.AlterModelOptions(
            name="poweroutlet",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="powerport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="rearport",
            options={"ordering": ("device", "module__id", "_name")},
        ),


        migrations.AlterModelOptions(
            name="powerfeed",
            options={"ordering": ["power_panel", "breaker_position", "name"]},
        ),
        migrations.AlterUniqueTogether(
            name="powerfeed",
            unique_together={("power_panel", "name")},
        ),
        migrations.AddField(
            model_name="powerfeed",
            name="breaker_pole_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="powerfeed",
            name="breaker_position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="powerfeed",
            name="destination_panel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feeders",
                to="dcim.powerpanel",
            ),
        ),
        migrations.AddField(
            model_name="powerfeed",
            name="power_path",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="powerpanel",
            name="breaker_position_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="powerpanel",
            name="panel_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="powerpanel",
            name="power_path",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="powerport",
            name="power_factor",
            field=models.DecimalField(
                decimal_places=2,
                default="0.95",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="powerporttemplate",
            name="power_factor",
            field=models.DecimalField(
                decimal_places=2,
                default="0.95",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="powerfeed",
            unique_together={("power_panel", "breaker_position"), ("power_panel", "name")},
        ),
        migrations.AddIndex(
            model_name="powerfeed",
            index=models.Index(fields=["power_panel", "breaker_position"], name="dcim_powerf_power_p_b4d96d_idx"),
        ),


        migrations.AlterField(
            model_name="powerport",
            name="power_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.95"),
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="powerporttemplate",
            name="power_factor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.95"),
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),


        migrations.AlterField(
            model_name="rack",
            name="u_height",
            field=models.PositiveSmallIntegerField(
                default=42,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)],
            ),
        ),
    ]
