# Generated by Django 4.2.19 on 2025-03-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0068_modulefamily_modulebay_module_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulebaytemplate",
            name="module_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="module_bay_templates",
                to="dcim.modulefamily",
            ),
        ),
    ]
