# Generated by Django 5.2.4 on 2025-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0069_softwareimagefile_external_integration"),
        ("wireless", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controllermanageddevicegroup",
            name="radio_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="controller_managed_device_groups",
                through="wireless.ControllerManagedDeviceGroupRadioProfileAssignment",
                through_fields=("controller_managed_device_group", "radio_profile"),
                to="wireless.radioprofile",
            ),
        ),
        migrations.AlterField(
            model_name="controllermanageddevicegroup",
            name="wireless_networks",
            field=models.ManyToManyField(
                blank=True,
                related_name="controller_managed_device_groups",
                through="wireless.ControllerManagedDeviceGroupWirelessNetworkAssignment",
                through_fields=("controller_managed_device_group", "wireless_network"),
                to="wireless.wirelessnetwork",
            ),
        ),
    ]
