# Generated by Django 4.2.21 on 2025-06-13 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0069_softwareimagefile_external_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_redundancy_group_priority',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
