# Generated by Django 4.2.20 on 2025-07-17 20:24

from django.db import migrations

import nautobot.core.models.query_functions


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0070_modulefamily_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consoleport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="consoleserverport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="frontport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="interface",
            options={"ordering": ("device", "module__id", nautobot.core.models.query_functions.CollateAsChar("_name"))},
        ),
        migrations.AlterModelOptions(
            name="poweroutlet",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="powerport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="rearport",
            options={"ordering": ("device", "module__id", "_name")},
        ),
    ]
