import uuid

from constance.models import Constance
from django.db import migrations, models
import django.db.models.deletion

from nautobot.core.utils.config import get_settings_or_config
from nautobot.dcim.choices import DeviceUniquenessChoices

# From 0075_interface_duplex_interface_speed_and_more
# Generated by Django 4.2.25 on 2025-11-01 22:09

# From 0076_add_deviceclusterassignment

# From 0077_device_cluster_to_clusters_data_migration

# From 0078_remove_device_cluster

# From 0079_remove_device_location_tenant_name_uniqueness
# Generated by Django 4.2.24 on 2025-10-07 07:18

# From 0080_device_name_data_migration
# Generated by Django 4.2.24 on 2025-10-07 07:18


# From 0077_device_cluster_to_clusters_data_migration
def migrate_device_cluster_assignments(apps, schema_editor):
    """
    Migrate existing device cluster assignments from the old ForeignKey field
    to the new many-to-many relationship through DeviceClusterAssignment.
    """
    Device = apps.get_model("dcim", "Device")
    DeviceClusterAssignment = apps.get_model("dcim", "DeviceClusterAssignment")
    devices_with_clusters = Device.objects.filter(cluster__isnull=False).select_related("cluster")
    assignments_to_create = []
    for device in devices_with_clusters:
        assignments_to_create.append(DeviceClusterAssignment(device=device, cluster=device.cluster))
    if assignments_to_create:
        DeviceClusterAssignment.objects.bulk_create(assignments_to_create, batch_size=1000)


def reverse_migrate_device_cluster_assignments(apps, schema_editor):
    """
    Reverse migration - restore the cluster field from DeviceClusterAssignment records.
    Note: This can only restore one cluster per device if multiple exist.
    """
    DeviceClusterAssignment = apps.get_model("dcim", "DeviceClusterAssignment")

    # For each device, get the first cluster assignment and set it as the device's cluster
    for assignment in DeviceClusterAssignment.objects.select_related("device", "cluster"):
        if not assignment.device.cluster:
            assignment.device.cluster = assignment.cluster
            assignment.device.save(update_fields=["cluster"])


# From 0080_device_name_data_migration
def migrate_device_uniqueness_setting(apps, schema_editor):
    """
    Migrate deprecated DEVICE_NAME_AS_NATURAL_KEY setting to DEVICE_UNIQUENESS and DEVICE_NAME_REQUIRED.
    """
    try:
        old_value = get_settings_or_config("DEVICE_NAME_AS_NATURAL_KEY")
    except AttributeError:
        old_value = False
    new_value = DeviceUniquenessChoices.NAME if old_value else DeviceUniquenessChoices.LOCATION_TENANT_NAME

    # Update or create DEVICE_UNIQUENESS in Constance
    Constance.objects.update_or_create(
        key="DEVICE_UNIQUENESS",
        defaults={"value": new_value},
    )

    # cleanup: remove deprecated setting entry if it exists
    Constance.objects.filter(key="DEVICE_NAME_AS_NATURAL_KEY").delete()


def reverse_migrate_device_uniqueness_setting(apps, schema_editor):
    """
    Reverse migration set DEVICE_NAME_AS_NATURAL_KEY based on DEVICE_UNIQUENESS.
    """
    try:
        device_uniqueness = Constance.objects.get(key="DEVICE_UNIQUENESS").value
    except Constance.DoesNotExist:
        return

    if device_uniqueness == DeviceUniquenessChoices.NAME:
        Constance.objects.update_or_create(key="DEVICE_NAME_AS_NATURAL_KEY", defaults={"value": True})
    else:
        Constance.objects.update_or_create(key="DEVICE_NAME_AS_NATURAL_KEY", defaults={"value": False})

    # cleanup: remove DEVICE_UNIQUENESS setting entry if it exists
    Constance.objects.filter(key="DEVICE_UNIQUENESS").delete()


class Migration(migrations.Migration):
    replaces = [
        ("dcim", "0075_interface_duplex_interface_speed_and_more"),
        ("dcim", "0076_add_deviceclusterassignment"),
        ("dcim", "0077_device_cluster_to_clusters_data_migration"),
        ("dcim", "0078_remove_device_cluster"),
        ("dcim", "0079_remove_device_location_tenant_name_uniqueness"),
        ("dcim", "0080_device_name_data_migration"),
    ]

    dependencies = [
        ("dcim", "0074_alter_rack_u_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="duplex",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="interface",
            name="speed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interfacetemplate",
            name="duplex",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="interfacetemplate",
            name="speed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DeviceClusterAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_assignments",
                        to="virtualization.cluster",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_assignments",
                        to="dcim.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device", "cluster"],
                "unique_together": {("device", "cluster")},
            },
        ),
        migrations.AddField(
            model_name="device",
            name="clusters",
            field=models.ManyToManyField(
                blank=True, related_name="devices", through="dcim.DeviceClusterAssignment", to="virtualization.cluster"
            ),
        ),
        migrations.RunPython(migrate_device_cluster_assignments, reverse_migrate_device_cluster_assignments),
        migrations.RemoveField(
            model_name="device",
            name="cluster",
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("rack", "position", "face"), ("virtual_chassis", "vc_position")},
        ),
        migrations.RunPython(
            migrate_device_uniqueness_setting,
            reverse_migrate_device_uniqueness_setting,
        ),
    ]
