# Generated by Django 4.2.24 on 2025-10-07 07:18

from django.db import migrations


def migrate_device_uniqueness_setting(apps, schema_editor):
    """
    Migrate deprecated DEVICE_NAME_AS_NATURAL_KEY setting to DEVICE_UNIQUENESS and DEVICE_NAME_REQUIRED.
    """
    from constance import config
    from constance.models import Constance

    old_value = getattr(config, "DEVICE_NAME_AS_NATURAL_KEY", None)

    new_value = "name" if old_value else "location_tenant_name"

    # Update or create DEVICE_UNIQUENESS in Constance
    Constance.objects.update_or_create(
        key="DEVICE_UNIQUENESS",
        defaults={"value": new_value},
    )

    # cleanup: remove deprecated setting entry if it exists
    Constance.objects.filter(key="DEVICE_NAME_AS_NATURAL_KEY").delete()


def reverse_migrate_device_uniqueness_setting(apps, schema_editor):
    """
    Reverse migration set DEVICE_NAME_AS_NATURAL_KEY based on DEVICE_UNIQUENESS.
    """
    from constance.models import Constance

    try:
        device_uniqueness = Constance.objects.get(key="DEVICE_UNIQUENESS").value
    except Constance.DoesNotExist:
        return

    if device_uniqueness == "name":
        Constance.objects.update_or_create(key="DEVICE_NAME_AS_NATURAL_KEY", defaults={"value": True})
    else:
        Constance.objects.update_or_create(key="DEVICE_NAME_AS_NATURAL_KEY", defaults={"value": False})


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0078_alter_device_unique_together"),
    ]

    operations = [
        migrations.RunPython(
            migrate_device_uniqueness_setting,
            reverse_migrate_device_uniqueness_setting,
        ),
    ]
