# Generated by Django 4.2.24 on 2025-10-07 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0078_remove_device_cluster"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("rack", "position", "face"), ("virtual_chassis", "vc_position")},
        ),
    ]
