# Generated by Django 4.2.25 on 2025-11-05 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0080_device_name_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_redundancy_group_priority",
            field=models.PositiveIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="interfaceredundancygroupassociation",
            name="priority",
            field=models.PositiveIntegerField(),
        ),
    ]
