# Generated by Django 4.2.26 on 2025-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interface",
            name="port_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="interfacetemplate",
            name="port_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
