# Generated by Django 4.2.29 on 2026-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0083_alter_controllermanageddevicegroup_radio_profiles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduletype",
            name="front_image",
            field=models.ImageField(blank=True, upload_to="moduletype-images"),
        ),
        migrations.AddField(
            model_name="moduletype",
            name="rear_image",
            field=models.ImageField(blank=True, upload_to="moduletype-images"),
        ),
    ]
