# Generated by Django 5.2.14 on 2026-05-28 22:11

from django.db import migrations

OLD_VALUE = "128gfc-sfp28"
NEW_VALUE = "128gfc-qsfp28"


def correct_interface_types(apps, schema_editor):
    """
    Correct existing database records using the incorrect '128gfc-sfp28'
    value to the corrected '128gfc-qsfp28' slug.
    """
    Interface = apps.get_model("dcim", "Interface")
    InterfaceTemplate = apps.get_model("dcim", "InterfaceTemplate")

    # Update both runtime interfaces and device-type interface templates
    Interface.objects.filter(type=OLD_VALUE).update(type=NEW_VALUE)
    InterfaceTemplate.objects.filter(type=OLD_VALUE).update(type=NEW_VALUE)


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0084_add_module_type_image_support"),
    ]

    operations = [
        migrations.RunPython(
            code=correct_interface_types,
            reverse_code=migrations.RunPython.noop,  # Safe to no-op on rollback
        ),
    ]
