# Generated by Django 5.2.13 on 2026-04-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0084_add_module_type_image_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualdevicecontext",
            name="controller_managed_device_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="virtual_device_contexts",
                to="dcim.controllermanageddevicegroup",
            ),
        ),
    ]
