# Generated by Django 5.2.16 on 2026-07-15 14:08

import nautobot.core.models.query_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0085_fix_128gfc_qsfp28_typo'),
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('ipam', '0056_alter_vrfdeviceassignment_ordering_vrfprefixassignment_ordering'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interface',
            index=models.Index(models.F('device'), models.F('module'), nautobot.core.models.query_functions.CollateAsChar('_name'), name='dcim_interface_order_idx'),
        ),
    ]
