# Generated by Django 5.2.14 on 2026-05-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0086_populate_default_cable_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualdevicecontext",
            name="controller_managed_device_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="virtual_device_contexts",
                to="dcim.controllermanageddevicegroup",
            ),
        ),
    ]
