# Generated by Django 5.2.14 on 2026-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0090_cablepath_add_lane_fields"),
        ("extras", "0146_computedfield_output_type"),
        ("ipam", "0055_rename_ipaddress_ip_version_host_mask_length_ipam_ipaddr_ip_vers_d82ba5_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="consoleport",
            name="dcim_consoleport_device_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="consoleport",
            name="dcim_consoleport_module_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="consoleserverport",
            name="dcim_consoleserverport_device_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="consoleserverport",
            name="dcim_consoleserverport_module_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="frontport",
            name="dcim_frontport_device_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="frontport",
            name="dcim_frontport_module_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="interface",
            name="dcim_interface_device_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="interface",
            name="dcim_interface_module_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="modulebay",
            name="dcim_modulebay_parent_device_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="modulebay",
            name="dcim_modulebay_parent_module_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="poweroutlet",
            name="dcim_poweroutlet_device_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="poweroutlet",
            name="dcim_poweroutlet_module_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="powerport",
            name="dcim_powerport_device_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="powerport",
            name="dcim_powerport_module_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="rearport",
            name="dcim_rearport_device_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="rearport",
            name="dcim_rearport_module_name_unique",
        ),
        migrations.AddConstraint(
            model_name="consoleport",
            constraint=models.UniqueConstraint(
                fields=("device", "module", "name"), name="dcim_consoleport_device_model_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="consoleserverport",
            constraint=models.UniqueConstraint(
                fields=("device", "module", "name"), name="dcim_consoleserverport_device_model_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="frontport",
            constraint=models.UniqueConstraint(
                fields=("device", "module", "name"), name="dcim_frontport_device_model_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="interface",
            constraint=models.UniqueConstraint(
                fields=("device", "module", "name"), name="dcim_interface_device_model_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="modulebay",
            constraint=models.UniqueConstraint(
                fields=("parent_device", "parent_module", "name"), name="dcim_modulebay_parent_device_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="poweroutlet",
            constraint=models.UniqueConstraint(
                fields=("device", "module", "name"), name="dcim_poweroutlet_device_model_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="powerport",
            constraint=models.UniqueConstraint(
                fields=("device", "module", "name"), name="dcim_powerport_device_model_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="rearport",
            constraint=models.UniqueConstraint(
                fields=("device", "module", "name"), name="dcim_rearport_device_model_name_unique"
            ),
        ),
    ]
