# Generated by Django 5.2.14 on 2026-06-16 14:50

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0092_backpopulate_device_on_modular_component'),
        ('extras', '0146_computedfield_output_type'),
        ('ipam', '0055_rename_ipaddress_ip_version_host_mask_length_ipam_ipaddr_ip_vers_d82ba5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consoleport',
            name='dcim_consoleport_device_model_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='consoleserverport',
            name='dcim_consoleserverport_device_model_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='frontport',
            name='dcim_frontport_device_model_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='interface',
            name='dcim_interface_device_model_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='poweroutlet',
            name='dcim_poweroutlet_device_model_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='powerport',
            name='dcim_powerport_device_model_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='rearport',
            name='dcim_rearport_device_model_name_unique',
        ),
        migrations.AddField(
            model_name='consoleport',
            name='_device_name_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('device_id', output_field=models.CharField()), models.Value('')), models.Value('||'), models.F('name'), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='consoleport',
            name='_module_name_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(module_id__isnull=False, then=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast('module_id', output_field=models.CharField()), models.Value('||'), models.F('name'), output_field=models.CharField())), default=django.db.models.functions.comparison.Cast('id', output_field=models.CharField()), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='consoleserverport',
            name='_device_name_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('device_id', output_field=models.CharField()), models.Value('')), models.Value('||'), models.F('name'), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='consoleserverport',
            name='_module_name_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(module_id__isnull=False, then=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast('module_id', output_field=models.CharField()), models.Value('||'), models.F('name'), output_field=models.CharField())), default=django.db.models.functions.comparison.Cast('id', output_field=models.CharField()), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='frontport',
            name='_device_name_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('device_id', output_field=models.CharField()), models.Value('')), models.Value('||'), models.F('name'), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='frontport',
            name='_module_name_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(module_id__isnull=False, then=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast('module_id', output_field=models.CharField()), models.Value('||'), models.F('name'), output_field=models.CharField())), default=django.db.models.functions.comparison.Cast('id', output_field=models.CharField()), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='interface',
            name='_device_name_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('device_id', output_field=models.CharField()), models.Value('')), models.Value('||'), models.F('name'), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='interface',
            name='_module_name_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(module_id__isnull=False, then=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast('module_id', output_field=models.CharField()), models.Value('||'), models.F('name'), output_field=models.CharField())), default=django.db.models.functions.comparison.Cast('id', output_field=models.CharField()), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='poweroutlet',
            name='_device_name_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('device_id', output_field=models.CharField()), models.Value('')), models.Value('||'), models.F('name'), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='poweroutlet',
            name='_module_name_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(module_id__isnull=False, then=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast('module_id', output_field=models.CharField()), models.Value('||'), models.F('name'), output_field=models.CharField())), default=django.db.models.functions.comparison.Cast('id', output_field=models.CharField()), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='powerport',
            name='_device_name_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('device_id', output_field=models.CharField()), models.Value('')), models.Value('||'), models.F('name'), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='powerport',
            name='_module_name_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(module_id__isnull=False, then=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast('module_id', output_field=models.CharField()), models.Value('||'), models.F('name'), output_field=models.CharField())), default=django.db.models.functions.comparison.Cast('id', output_field=models.CharField()), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='rearport',
            name='_device_name_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('device_id', output_field=models.CharField()), models.Value('')), models.Value('||'), models.F('name'), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddField(
            model_name='rearport',
            name='_module_name_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(module_id__isnull=False, then=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast('module_id', output_field=models.CharField()), models.Value('||'), models.F('name'), output_field=models.CharField())), default=django.db.models.functions.comparison.Cast('id', output_field=models.CharField()), output_field=models.CharField()), output_field=models.CharField()),
        ),
        migrations.AddConstraint(
            model_name='consoleport',
            constraint=models.UniqueConstraint(fields=('_device_name_key',), name='dcim_consoleport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='consoleport',
            constraint=models.UniqueConstraint(fields=('_module_name_key',), name='dcim_consoleport_module_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='consoleserverport',
            constraint=models.UniqueConstraint(fields=('_device_name_key',), name='dcim_consoleserverport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='consoleserverport',
            constraint=models.UniqueConstraint(fields=('_module_name_key',), name='dcim_consoleserverport_module_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='frontport',
            constraint=models.UniqueConstraint(fields=('_device_name_key',), name='dcim_frontport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='frontport',
            constraint=models.UniqueConstraint(fields=('_module_name_key',), name='dcim_frontport_module_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('_device_name_key',), name='dcim_interface_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('_module_name_key',), name='dcim_interface_module_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='poweroutlet',
            constraint=models.UniqueConstraint(fields=('_device_name_key',), name='dcim_poweroutlet_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='poweroutlet',
            constraint=models.UniqueConstraint(fields=('_module_name_key',), name='dcim_poweroutlet_module_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='powerport',
            constraint=models.UniqueConstraint(fields=('_device_name_key',), name='dcim_powerport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='powerport',
            constraint=models.UniqueConstraint(fields=('_module_name_key',), name='dcim_powerport_module_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='rearport',
            constraint=models.UniqueConstraint(fields=('_device_name_key',), name='dcim_rearport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='rearport',
            constraint=models.UniqueConstraint(fields=('_module_name_key',), name='dcim_rearport_module_name_unique'),
        ),
    ]
