# Generated by Django 5.2.14 on 2026-06-29 19:04

from django.db import migrations

import nautobot.core.models.query_functions


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0093_backpopulate_device_on_modular_component"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interface",
            options={
                "ordering": ("device_id", "module_id", nautobot.core.models.query_functions.CollateAsChar("_name"))
            },
        ),
    ]
