# Generated by Django 5.2.14 on 2026-06-29 20:22

from django.db import migrations

import nautobot.core.models.query_functions


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0094_alter_cable__abs_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consoleport",
            options={"ordering": ("device_id", "module_id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="consoleserverport",
            options={"ordering": ("device_id", "module_id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="frontport",
            options={"ordering": ("device_id", "module_id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="interface",
            options={
                "ordering": ("device_id", "module_id", nautobot.core.models.query_functions.CollateAsChar("_name"))
            },
        ),
        migrations.AlterModelOptions(
            name="poweroutlet",
            options={"ordering": ("device_id", "module_id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="powerport",
            options={"ordering": ("device_id", "module_id", "_name")},
        ),
        migrations.AlterModelOptions(
            name="rearport",
            options={"ordering": ("device_id", "module_id", "_name")},
        ),
    ]
