# Generated by Django 5.2.15 on 2026-07-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0095_alter_consoleport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cablepath",
            name="destination_fans_out",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cablepath",
            name="origin_fans_out",
            field=models.BooleanField(default=False),
        ),
    ]
