# Generated by Django 5.2.15 on 2026-07-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0096_cablepath_add_fans_out_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetype",
            name="breakout_subinterface_name_pattern",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
