# Generated by Django 5.2.17 on 2026-09-11 21:47

from django.db import migrations, models


def check_device_interface_names(apps, schema_editor):
    Interface = apps.get_model("dcim", "Interface")
    duplicates = (
        Interface.objects.using(schema_editor.connection.alias)
        .filter(module__isnull=True, device__isnull=False)
        .values("device_id", "name")
        .annotate(count=models.Count("pk"))
        .filter(count__gt=1)
    )
    if duplicates.exists():
        raise RuntimeError(
            "Cannot enforce device-interface name uniqueness: duplicate names exist among interfaces "
            "attached directly to the same device. Resolve these duplicates and rerun the migration. "
            "Names repeated across different modules are permitted. No interface records were changed."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0097_virtualdevicecontext_controller_managed_device_group"),
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
        ("ipam", "0058_iprange_role_data"),
    ]

    operations = [
        migrations.RunPython(check_device_interface_names, migrations.RunPython.noop),
        migrations.AddField(
            model_name="interface",
            name="_device_name_scope",
            field=models.GeneratedField(
                expression=models.Case(
                    models.When(module__isnull=True, then=models.Value(1)), output_field=models.IntegerField()
                ),
                output_field=models.IntegerField(),
                db_persist=True,
                null=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="interface",
            constraint=models.UniqueConstraint(
                fields=("device", "name", "_device_name_scope"),
                name="dcim_interface_device_name_unique",
                violation_error_message="An interface with this name already exists directly on this device.",
            ),
        ),
    ]
