"""Nautobot template tags."""

from nautobot.core.templatetags.bootstrapped_goodies_tags import (
    custom_field_rendering,
    fieldset_column_width,
    form_fieldset_column_width,
    language_selector,
    render_app_description,
    render_app_label,
    render_app_name,
    render_with_template_if_exist,
)
from nautobot.core.templatetags.buttons import (
    add_button,
    clone_button,
    delete_button,
    edit_button,
    export_button,
    import_button,
)
from nautobot.core.templatetags.form_helpers import (
    render_custom_fields,
    render_field,
    render_form,
    render_relationships,
    widget_type,
)
from nautobot.core.templatetags.helpers import (
    add_html_id,
    as_range,
    badge,
    bettertitle,
    custom_branding_or_static,
    divide,
    fgcolor,
    filter_form_modal,
    get_attr,
    get_docs_url,
    get_item,
    has_one_or_more_perms,
    has_perms,
    humanize_speed,
    hyperlinked_object,
    hyperlinked_object_with_color,
    is_new_ui_ready,
    meta,
    meters_to_feet,
    modal_form_as_dialog,
    percentage,
    placeholder,
    queryset_to_pks,
    querystring,
    quote_string,
    render_boolean,
    render_json,
    render_markdown,
    render_yaml,
    settings_or_config,
    split,
    table_config_form,
    tag,
    tzoffset,
    utilization_graph,
    utilization_graph_raw_data,
    validated_viewname,
    viewname,
)
from nautobot.core.templatetags.perms import can_add, can_change, can_delete, can_view
from nautobot.extras.templatetags.computed_fields import computed_fields, has_computed_fields
from nautobot.extras.templatetags.custom_links import custom_links
from nautobot.extras.templatetags.job_buttons import job_buttons
from nautobot.extras.templatetags.log_levels import log_level
from nautobot.extras.templatetags.registry import do_registry


__all__ = (
    "add_button",
    "add_html_id",
    "as_range",
    "badge",
    "bettertitle",
    "can_add",
    "can_change",
    "can_delete",
    "can_view",
    "clone_button",
    "computed_fields",
    "custom_branding_or_static",
    "custom_field_rendering",
    "custom_links",
    "delete_button",
    "divide",
    "do_registry",
    "edit_button",
    "export_button",
    "fgcolor",
    "fieldset_column_width",
    "filter_form_modal",
    "form_fieldset_column_width",
    "get_attr",
    "get_docs_url",
    "get_item",
    "has_computed_fields",
    "has_one_or_more_perms",
    "has_perms",
    "humanize_speed",
    "hyperlinked_object",
    "hyperlinked_object_with_color",
    "import_button",
    "is_new_ui_ready",
    "job_buttons",
    "language_selector",
    "log_level",
    "meta",
    "meters_to_feet",
    "modal_form_as_dialog",
    "percentage",
    "placeholder",
    "queryset_to_pks",
    "querystring",
    "quote_string",
    "render_app_description",
    "render_app_label",
    "render_app_name",
    "render_boolean",
    "render_custom_fields",
    "render_field",
    "render_form",
    "render_json",
    "render_markdown",
    "render_relationships",
    "render_with_template_if_exist",
    "render_yaml",
    "settings_or_config",
    "split",
    "table_config_form",
    "tag",
    "tzoffset",
    "utilization_graph",
    "utilization_graph_raw_data",
    "validated_viewname",
    "viewname",
    "widget_type",
)
