# Generated by Django 2.2.6 on 2019-12-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0006_custom_tag_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrole',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
