#!/bin/sh
# Create a link to this file at .git/hooks/pre-commit to
# force PEP8 and Black style validation prior to committing

exec 1>&2

EXIT=0
RED='\033[0;31m'
NOCOLOR='\033[0m'

if [ -d ./venv/ ]; then
    VENV="$PWD/venv"
    if [ -e $VENV/bin/python ]; then
        PATH=$VENV/bin:$PATH
    elif [ -e $VENV/Scripts/python.exe ]; then
        PATH=$VENV/Scripts:$PATH
    fi
fi

echo "Validating PEP8 compliance..."
invoke flake8 || EXIT=1

echo "Check that all files conform to Black..."
invoke black || EXIT=1

echo "Checking for missing migrations..."
invoke check-migrations || EXIT=1

if [ "$INVOKE_NAUTOBOT_LOCAL" = "True" ] && [ ! -x "$(command -v hadolint)" ]; then
    echo "Skipping Dockerfile check: hadolint must be installed to run"
else
    echo "Checking Dockerfile..."
    invoke hadolint || EXIT=1
fi

if [ "$INVOKE_NAUTOBOT_LOCAL" = "True" ] && [ ! -x "$(command -v markdownlint)" ]; then
    echo "Skipping Markdownlint check: markdownlint must be installed to run"
else
    echo "Checking Markdown files..."
    invoke markdownlint || EXIT=1
fi

if [ $EXIT != 0 ]; then
	printf "${RED}COMMIT FAILED${NOCOLOR}\n"
fi

exit $EXIT
