# Generated by Django 3.1.13 on 2021-08-03 04:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("circuits", "0002_initial_part_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuittype",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
    ]
