# Generated by Django 3.2.12 on 2022-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circuits", "0007_circuitterminations_primary_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providernetwork",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
