# Generated by Django 3.2.13 on 2022-06-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0013_location_location_type"),
        ("circuits", "0008_add_natural_indexing"),
    ]

    operations = [
        migrations.AddField(
            model_name="circuittermination",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="circuit_terminations",
                to="dcim.location",
            ),
        ),
    ]
