# Generated by Django 3.2.15 on 2022-08-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0009_circuittermination_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuittermination',
            name='_cable_peer_id',
        ),
        migrations.RemoveField(
            model_name='circuittermination',
            name='_cable_peer_type',
        ),
        migrations.AddField(
            model_name='circuittermination',
            name='cable_side',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
