# Generated by Django 3.2.16 on 2023-01-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0023_alter_interface_mac_address"),
        ("circuits", "0009_circuittermination_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="circuit",
            old_name="termination_a",
            new_name="circuit_termination_a",
        ),
        migrations.RenameField(
            model_name="circuit",
            old_name="termination_z",
            new_name="circuit_termination_z",
        ),
        migrations.RenameField(
            model_name="circuit",
            old_name="type",
            new_name="circuit_type",
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="circuit_terminations",
                to="dcim.cablepath",
            ),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="circuit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="circuit_terminations", to="circuits.circuit"
            ),
        ),
    ]
