from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations


# From 0010_rename_foreign_keys_and_related_names
# Generated by Django 3.2.16 on 2023-01-26 15:24

# From 0011_remove_site_foreign_key_from_circuit_termination_class
# Generated by Django 3.2.16 on 2023-01-31 04:16


class Migration(migrations.Migration):

    replaces = [
        ("circuits", "0010_rename_foreign_keys_and_related_names"),
        ("circuits", "0011_remove_site_foreign_key_from_circuit_termination_class"),
    ]

    dependencies = [
        ("dcim", "0035_rename_path_end_point_related_name"),
        ("circuits", "0009_circuittermination_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="circuit",
            old_name="termination_a",
            new_name="circuit_termination_a",
        ),
        migrations.RenameField(
            model_name="circuit",
            old_name="termination_z",
            new_name="circuit_termination_z",
        ),
        migrations.RenameField(
            model_name="circuit",
            old_name="type",
            new_name="circuit_type",
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="circuits_circuittermination_related",
                to="dcim.cablepath",
            ),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="circuit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="circuit_terminations", to="circuits.circuit"
            ),
        ),

        migrations.RemoveField(
            model_name="circuittermination",
            name="site",
        ),
    ]
