# Generated by Django 3.2.16 on 2023-01-11 22:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("circuits", "0009_circuittermination_location"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="circuit",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="circuittermination",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="provider",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="providernetwork",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
            ],
            database_operations=[],
        )
    ]
