# Generated by Django 3.2.17 on 2023-02-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circuits", "0011_remove_site_foreign_key_from_circuit_termination_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuit",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="circuittype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="providernetwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
