from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
import nautobot.extras.models.statuses

# From 0012_created_datetime
# Generated by Django 3.2.17 on 2023-02-14 19:29

# From 0013_alter_circuittermination__path
# Generated by Django 3.2.17 on 2023-02-17 17:21

# From 0014_related_name_changes
# Generated by Django 3.2.18 on 2023-02-23 21:44

# From 0015_remove_circuittype_provider_slug
# Generated by Django 3.2.18 on 2023-03-15 12:27


class Migration(migrations.Migration):
    replaces = [
        ("circuits", "0012_created_datetime"),
        ("circuits", "0013_alter_circuittermination__path"),
        ("circuits", "0014_related_name_changes"),
        ("circuits", "0015_remove_circuittype_provider_slug"),
    ]

    dependencies = [
        ("circuits", "0011_remove_site_foreign_key_from_circuit_termination_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuit",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="circuittype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="providernetwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="circuit_terminations",
                to="dcim.cablepath",
            ),
        ),
        migrations.AlterField(
            model_name="circuit",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="circuits", to="extras.status"
            ),
        ),
        migrations.RemoveField(
            model_name="circuittype",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="slug",
        ),
    ]
