# Generated by Django 3.2.17 on 2023-02-17 17:21

from django.db import migrations
import django.db.models.deletion
import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0037_created_datetime"),
        ("circuits", "0012_created_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuittermination",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="circuit_terminations",
                to="dcim.cablepath",
            ),
        ),
    ]
