# Generated by Django 3.2.18 on 2023-03-15 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circuits", "0014_related_name_changes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circuittype",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="slug",
        ),
    ]
