from django.db import migrations
import nautobot.core.models.fields
from nautobot.extras.utils import fixup_null_statuses
import django.db.models.deletion
import nautobot.extras.models.statuses


# From 0016_tagsfield
# Generated by Django 3.2.18 on 2023-04-21 13:59

# From 0017_fixup_null_statuses
def migrate_null_statuses(apps, schema):
    status_model = apps.get_model("extras", "Status")
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model_name in ("Circuit",):
        model = apps.get_model("circuits", model_name)
        model_ct = ContentType.objects.get_for_model(model)
        fixup_null_statuses(model=model, model_contenttype=model_ct, status_model=status_model)

# From 0018_status_nonnullable
# Generated by Django 3.2.18 on 2023-05-19 18:05

# From 0019_remove_providernetwork_slug
# Generated by Django 3.2.18 on 2023-06-12 22:19


class Migration(migrations.Migration):

    replaces = [
        ("circuits", "0016_tagsfield"),
        ("circuits", "0017_fixup_null_statuses"),
        ("circuits", "0018_status_nonnullable"),
        ("circuits", "0019_remove_providernetwork_slug"),
    ]

    dependencies = [
        ("extras", "0080_tagsfield"),
        ("circuits", "0015_remove_circuittype_provider_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuit",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="providernetwork",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),

        migrations.RunPython(migrate_null_statuses, migrations.RunPython.noop),

        migrations.AlterField(
            model_name="circuit",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="circuits", to="extras.status"
            ),
        ),

        migrations.RemoveField(
            model_name="providernetwork",
            name="slug",
        ),
    ]
