from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
import nautobot.extras.models.statuses

# From 0020_update_all_charfields_max_length_to_255
# Generated by Django 3.2.24 on 2024-02-29 07:45

# From 0021_alter_circuit_status_alter_circuittermination__path
# Generated by Django 4.2.9 on 2024-01-17 18:52

# From 0022_circuittermination_cloud_network
# Generated by Django 4.2.14 on 2024-07-18 16:08


class Migration(migrations.Migration):
    replaces = [
        ("circuits", "0020_update_all_charfields_max_length_to_255"),
        ("circuits", "0021_alter_circuit_status_alter_circuittermination__path"),
        ("circuits", "0022_circuittermination_cloud_network"),
    ]

    dependencies = [
        ("circuits", "0019_remove_providernetwork_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuit",
            name="cid",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="circuit",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="pp_info",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="xconnect_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittype",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="account",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="providernetwork",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="providernetwork",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuit",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="_path",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.cablepath"
            ),
        ),
        migrations.AddField(
            model_name="circuittermination",
            name="cloud_network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="circuit_terminations",
                to="cloud.cloudnetwork",
            ),
        ),
    ]
