# Generated by Django 3.2.24 on 2024-02-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circuits", "0019_remove_providernetwork_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuit",
            name="cid",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="circuit",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="pp_info",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittermination",
            name="xconnect_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittype",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="circuittype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="account",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="providernetwork",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="providernetwork",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
