---
# MD007 - Unordered list indentation
# Sets nested list indents to 4 spaces instead of the default of 2.
# Required for proper ReadTheDocs rendering.
MD007:
    indent: 4

# MD010 - No hard tabs
# No hard tabs allowed in docs. Use 4 spaces instead.
# This is disabled inline when used. E.g. docs/development/getting-started.md
MD010: true

# MD013 - Line length
# Defaults to 80 characters.
MD013: false

# MD014 - Dollar signs used before commands without showing output
# Ignores terminal examples using dollar signs without any output examples after.
# These occur in multiple places throughout our docs.
MD014: false

# MD024 - Multiple headings with the same content
# Multiple identical headings in the document are not allowed
# This is disabled on all of the release notes pages in docs/release-notes
MD024: true

# MD033 - Inline HTML
# Triggered when raw HTML is used in a markdown document
# Used/disabled in a few files. E.g. docs/user-guides/graphql.md
MD033: true

# MD041 - First line in a file should be a top-level heading
# This requires a top-level heading as the first line in every doc.
# This is only ignored inline in docs/index.md, but enabled globally elsewhere.
MD041: true

# MD046 - Code block style
# This rule is triggered when unwanted or different code block styles are used in the same document.
# However this conflicts with how ReadTheDocs renders "warning", "note", etc boxes, as those use indentation
#  but code blocks do not.
MD046: false