---
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python in the build environment.
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - mkdir -p $HOME/.nautobot
    - mkdir -p _readthedocs/html/
    - cp development/rtd_nautobot_config.py $HOME/.nautobot/nautobot_config.py
    - mkdocs build --no-directory-urls
    - cp --recursive  nautobot/project-static/docs/* _readthedocs/html/

# MKDocs configuration file
mkdocs:
  configuration: "mkdocs.yml"
  # fail_on_warning: true
