# Generated by Django 4.2.25 on 2025-10-21 15:46

from django.db import migrations

import nautobot.extras.management


def populate_default_status_and_role_choices_for_vpn(apps, schema_editor):
    """Create/link default Status and Role records for the VPNTunnel and VPNTunnelEndpoint content-type"""
    nautobot.extras.management.populate_status_choices(apps, schema_editor, models=["vpn.VPNTunnel"])
    nautobot.extras.management.populate_role_choices(apps, schema_editor, models=["vpn.VPNTunnelEndpoint"])


def clear_default_status_and_role_choices_for_vpn(apps, schema_editor):
    """De-link/delete all Status and Role records from the VPNTunnel and VPNTunnelEndpoint content-type."""
    nautobot.extras.management.clear_status_choices(apps, schema_editor, models=["vpn.VPNTunnel"])
    nautobot.extras.management.clear_role_choices(apps, schema_editor, models=["vpn.VPNTunnelEndpoint"])


def populate_default_vpn_profiles(apps, schema_editor):
    """Create default profiles."""
    try:
        VPNPhase1Policy = apps.get_model("vpn.VPNPhase1Policy")
        VPNPhase2Policy = apps.get_model("vpn.VPNPhase2Policy")
        VPNProfile = apps.get_model("vpn.VPNProfile")
    except LookupError:
        raise LookupError(
            "Could not find vpn.VPNPhase1Policy and/or vpn.VPNPhase2Policy and/or vpn.VPNProfile. Please make sure the correct migration dependencies are set before using this method"
        )
    for ph1_policy, ph2_policy, profile in [
        (
            {
                "name": "Standard Policy",
                "description": "Standard Phase 1 Policy dedicated for Standard Site-to-Site VPN",
                "ike_version": "IKEv2",
                "encryption_algorithm": [
                    "AES-256-CBC",
                ],
                "integrity_algorithm": [
                    "SHA256",
                ],
                "dh_group": [
                    "14",
                ],
                "lifetime_seconds": 86400,
            },
            {
                "name": "Standard Policy",
                "description": "Standard Phase 2 Policy dedicated for Standard Site-to-Site VPN",
                "encryption_algorithm": [
                    "AES-256-CBC",
                ],
                "integrity_algorithm": [
                    "SHA256",
                ],
                "pfs_group": [
                    "14",
                ],
                "lifetime": 3600,
            },
            {
                "name": "Standard Site-to-Site VPN",
                "description": "Standard Site-to-Site VPN",
                "keepalive_enabled": True,
                "keepalive_interval": 10,
                "keepalive_retries": 3,
            },
        ),
        (
            {
                "name": "Remote Access",
                "description": "Policy dedicated for Remote Access VPN (IKEv2)",
                "ike_version": "IKEv2",
                "encryption_algorithm": [
                    "AES-256-CBC",
                ],
                "integrity_algorithm": [
                    "SHA256",
                ],
                "dh_group": [
                    "19",
                ],
                "lifetime_seconds": 28800,
            },
            {
                "name": "Remote Access",
                "description": "Policy dedicated for Remote Access VPN (IKEv2)",
                "encryption_algorithm": [
                    "AES-256-CBC",
                ],
                "integrity_algorithm": [
                    "SHA256",
                ],
                "pfs_group": [
                    "19",
                ],
                "lifetime": 3600,
            },
            {
                "name": "Remote Access VPN (IKEv2)",
                "description": "Remote Access VPN (IKEv2)",
                "keepalive_enabled": True,
                "keepalive_interval": 30,
                "keepalive_retries": 5,
            },
        ),
        (
            {
                "name": "Performance-Oriented",
                "description": "Performance-Oriented for Site-to-Site",
                "ike_version": "IKEv2",
                "encryption_algorithm": [
                    "AES-128-CBC",
                ],
                "integrity_algorithm": [
                    "SHA256",
                ],
                "dh_group": [
                    "5",
                ],
                "lifetime_seconds": 86400,
            },
            {
                "name": "Performance-Oriented",
                "description": "Performance-Oriented for Site-to-Site",
                "encryption_algorithm": [
                    "AES-128-CBC",
                ],
                "integrity_algorithm": [
                    "SHA256",
                ],
                "lifetime": 3600,
            },
            {
                "name": "Performance-Oriented Site-to-Site",
                "description": "Performance-Oriented Site-to-Site",
                "keepalive_enabled": True,
                "keepalive_interval": 5,
                "keepalive_retries": 2,
            },
        ),
        (
            {
                "name": "High-Security",
                "description": "High-Security Policy for Site-to-Site",
                "ike_version": "IKEv2",
                "encryption_algorithm": [
                    "AES-256-GCM",
                ],
                "integrity_algorithm": [
                    "SHA512",
                ],
                "dh_group": [
                    "21",
                ],
                "lifetime_seconds": 86400,
            },
            {
                "name": "High-Security",
                "description": "High-Security Policy for Site-to-Site",
                "encryption_algorithm": [
                    "AES-256-GCM",
                ],
                "integrity_algorithm": [
                    "SHA512",
                ],
                "pfs_group": [
                    "21",
                ],
                "lifetime": 1800,
            },
            {
                "name": "High-Security Site-to-Site",
                "description": "High-Security Site-to-Site",
                "keepalive_enabled": True,
                "keepalive_interval": 15,
                "keepalive_retries": 4,
            },
        ),
    ]:
        phase1_policy, _ = VPNPhase1Policy.objects.get_or_create(**ph1_policy)
        phase2_policy, _ = VPNPhase2Policy.objects.get_or_create(**ph2_policy)
        profile, _ = VPNProfile.objects.get_or_create(**profile)
        profile.vpn_phase1_policies.set([phase1_policy])
        profile.vpn_phase2_policies.set([phase2_policy])


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_default_status_and_role_choices_for_vpn,
            reverse_code=clear_default_status_and_role_choices_for_vpn,
        ),
        migrations.RunPython(code=populate_default_vpn_profiles, reverse_code=lambda *args: None),
    ]
