# Generated by Django 4.2.20 on 2025-04-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0068_alter_softwareimagefile_download_url"),
        ("vpn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpntunnelendpoint",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vpn_tunnel_endpoints",
                to="dcim.device",
            ),
        ),
    ]
