# Generated by Django 4.2.28 on 2026-03-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0133_alter_approvalworkflowstageresponse_options_and_more"),
        ("vpn", "0002_populate_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpntunnel",
            name="secrets_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vpn_tunnels",
                to="extras.secretsgroup",
            ),
        ),
    ]
