# Generated by Django 4.2.20 on 2025-04-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0068_alter_softwareimagefile_download_url'),
        ('vpn', '0002_remove_vpntunnelendpoint_vpn_tunnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpntunnelendpoint',
            name='source_interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vpn_tunnel_endpoints_src_int', to='dcim.interface'),
        ),
    ]
