# Generated by Django 4.2.20 on 2025-04-23 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0002_vpntunnelendpoint_device"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vpnphase1policy",
            options={"verbose_name": "VPN Phase 1 Policy", "verbose_name_plural": "VPN Phase 1 Policies"},
        ),
        migrations.AlterModelOptions(
            name="vpnphase2policy",
            options={"verbose_name": "VPN Phase 2 Policy", "verbose_name_plural": "VPN Phase 2 Policies"},
        ),
    ]
