# Generated by Django 4.2.23 on 2025-09-15 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0002_populate_status_roles_defaults"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vpntunnelendpoint",
            name="vpn_profile",
        ),
    ]
