# Generated by Django 4.2.29 on 2026-04-03 11:23

import uuid

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0133_alter_approvalworkflowstageresponse_options_and_more"),
        ("ipam", "0054_namespace_tenant"),
        ("virtualization", "0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more"),
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
        ("vpn", "0003_vpntunnel_secrets_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpn",
            name="extra_attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="vpn",
            name="service_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vpn",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.CreateModel(
            name="VPNTermination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_terminations",
                        to="dcim.interface",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "vlan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_terminations",
                        to="ipam.vlan",
                    ),
                ),
                (
                    "vm_interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_terminations",
                        to="virtualization.vminterface",
                    ),
                ),
                (
                    "vpn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="terminations", to="vpn.vpn"
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Termination",
                "verbose_name_plural": "VPN Terminations",
                "ordering": ("vpn__name",),
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="vpntermination",
            constraint=models.UniqueConstraint(fields=("vlan",), name="vpn_vpntermination_unique_vlan"),
        ),
        migrations.AddConstraint(
            model_name="vpntermination",
            constraint=models.UniqueConstraint(fields=("interface",), name="vpn_vpntermination_unique_interface"),
        ),
        migrations.AddConstraint(
            model_name="vpntermination",
            constraint=models.UniqueConstraint(fields=("vm_interface",), name="vpn_vpntermination_unique_vm_interface"),
        ),
    ]
