# Generated by Django 4.2.23 on 2025-09-15 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0003_remove_vpntunnelendpoint_vpn_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vpntunnel",
            old_name="vpn_profile",
            new_name="_vpn_profile",
        ),
    ]
