# Generated by Django 4.2.27 on 2026-01-28 06:20

import django.core.serializers.json
from django.db import migrations, models
import nautobot.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_alter_approvalworkflowstageresponse_options_and_more'),
        ('vpn', '0003_add_l2vpn_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2vpntermination',
            name='_custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='l2vpntermination',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='l2vpntermination',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='l2vpntermination',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
