# Generated by Django 5.2.16 on 2026-07-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0096_cablepath_add_fans_out_flags"),
        ("vpn", "0004_vpn_overlay_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpntunnelendpoint",
            name="source_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vpn_tunnel_endpoints_src_int",
                to="dcim.interface",
            ),
        ),
    ]
