# Generated by Django 4.2.20 on 2025-05-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0069_softwareimagefile_external_integration'),
        ('vpn', '0004_vpnphase1policy_tenant_vpnphase2policy_tenant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpntunnelendpoint',
            old_name='destination_fqdn',
            new_name='source_fqdn',
        ),
        migrations.RemoveField(
            model_name='vpntunnelendpoint',
            name='destination_ipaddress',
        ),
        migrations.AlterField(
            model_name='vpntunnelendpoint',
            name='source_interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vpn_tunnel_endpoints_src_int', to='dcim.interface'),
        ),
    ]
