# Generated by Django 3.2.12 on 2022-03-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="token",
            options={"ordering": ["created"]},
        ),
    ]
