# Generated by Django 3.2.15 on 2022-10-07 02:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0047_enforce_custom_field_slug'),
        ('users', '0002_token_ordering_by_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOBackend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('backend', models.CharField(max_length=100, unique=True)),
                ('_backend_name', models.CharField(editable=False, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SSO Backend',
                'verbose_name_plural': 'SSO Backends',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSOBackendConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='text', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ssobackend')),
                ('secret', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.secret')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ssobackend',
            name='configuration',
            field=models.ManyToManyField(through='users.SSOBackendConfiguration', to='extras.Secret'),
        ),
    ]
