# Generated by Django 3.2.16 on 2023-01-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_token_ordering_by_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="users", related_query_name="user", to="auth.Group"),
        ),
    ]
