# Generated by Django 3.2.18 on 2023-03-14 19:40

from django.db import migrations
import nautobot.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", nautobot.users.models.UserManager()),
            ],
        ),
    ]
