# Generated by Django 3.2.23 on 2024-01-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_objectpermission_object_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectpermission",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="objectpermission",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
