# Generated by Django 3.2.24 on 2024-02-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_make_object_permission_a_changelogged_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectpermission",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="objectpermission",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
