# Generated by Django 3.2.25 on 2024-04-29 16:58

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_update_all_charfields_max_length_to_255'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('view', models.CharField(max_length=255)),
                ('table_config', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pagination_count', models.IntegerField(blank=True, default=50)),
                ('filter_params', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('sort_order', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved view',
                'verbose_name_plural': 'saved views',
                'ordering': ['owner', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
