# Generated by Django 4.2.14 on 2024-07-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0113_saved_views"),
        ("users", "0009_update_all_charfields_max_length_to_255"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_saved_views",
            field=models.ManyToManyField(
                blank=True, related_name="users", through="extras.UserSavedViewAssociation", to="extras.savedview"
            ),
        ),
    ]
