# Generated by Django 4.2.13 on 2024-06-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0010_savedview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectpermission",
            name="object_types",
            field=models.ManyToManyField(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(
                            ("app_label__in", ["admin", "auth", "contenttypes", "sessions", "taggit", "users"]),
                            _negated=True,
                        ),
                        models.Q(("app_label", "admin"), ("model__in", ["logentry"])),
                        models.Q(("app_label", "auth"), ("model__in", ["group"])),
                        models.Q(
                            ("app_label", "users"), ("model__in", ["objectpermission", "token", "user", "savedview"])
                        ),
                        _connector="OR",
                    )
                ),
                related_name="object_permissions",
                to="contenttypes.contenttype",
            ),
        ),
    ]
