# Generated by Django 5.2.12 on 2026-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_default_saved_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
