# Generated by Django 4.2.13 on 2024-06-19 22:39

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_objectpermission_object_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserToSavedView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("view_name", models.CharField(max_length=255)),
                (
                    "saved_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="users.savedview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_view_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "view_name")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="default_saved_views",
            field=models.ManyToManyField(
                blank=True, related_name="users", through="users.UserToSavedView", to="users.savedview"
            ),
        ),
    ]
