# Generated by Django 5.2 on 2026-09-25 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_default_saved_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objectpermission",
            options={"ordering": ["name"]},
        ),
    ]
