# Generated by Django 5.2.11 on 2026-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_token_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
