# Generated by Django 3.0.3 on 2020-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0013_deterministic_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustergroup',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clustertype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
