import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import netaddr

import nautobot.core.models.fields
import nautobot.ipam.fields

# From 0003_remove_max_length
# Generated by Django 3.1.8 on 2021-05-14 19:58


# From 0004_fixup_p2p_broadcast
def fixup_p2p_broadcast(apps, schema_editor):
    """Correct the "broadcast" field for /31 and /127, as per https://github.com/nautobot/nautobot/pull/509."""
    Aggregate = apps.get_model("ipam", "Aggregate")
    Prefix = apps.get_model("ipam", "Prefix")
    IPAddress = apps.get_model("ipam", "IPAddress")

    # If the above models were our actual fully-implemented IPAM model classes, we could simply
    # call model.prefix = model.prefix to force recalculation of the broadcast address,
    # but the models we have access to here do not have any custom methods available.
    # So we have to fixup the broadcast addresses ourselves.

    for prefixlen in (31, 127):
        for aggregate in Aggregate.objects.filter(prefix_length=prefixlen):
            network = netaddr.IPNetwork(f"{aggregate.network}/{aggregate.prefix_length}")
            # Last address in the network is our "broadcast" address.
            aggregate.broadcast = network[-1]
            aggregate.save()

        for prefix in Prefix.objects.filter(prefix_length=prefixlen):
            network = netaddr.IPNetwork(f"{prefix.network}/{prefix.prefix_length}")
            # Last address in the network is our "broadcast" address.
            prefix.broadcast = network[-1]
            prefix.save()

        for ipaddress in IPAddress.objects.filter(prefix_length=prefixlen):
            network = netaddr.IPNetwork(f"{ipaddress.host}/{ipaddress.prefix_length}")
            # Last address in the network is our "broadcast" address.
            ipaddress.broadcast = network[-1]
            ipaddress.save()


# From 0005_auto_slug
# Generated by Django 3.1.13 on 2021-08-05 19:24

# From 0006_ipaddress_nat_outside_list
# Generated by Django 3.1.14 on 2022-02-28 18:31

# From 0007_add_natural_indexing
# Generated by Django 3.2.12 on 2022-04-15 17:39

# From 0008_prefix_vlan_vlangroup_location
# Generated by Django 3.2.13 on 2022-06-15 14:00

# From 0009_alter_vlan_name
# Generated by Django 3.2.16 on 2023-01-26 19:03


class Migration(migrations.Migration):
    replaces = [
        ("ipam", "0003_remove_max_length"),
        ("ipam", "0004_fixup_p2p_broadcast"),
        ("ipam", "0005_auto_slug"),
        ("ipam", "0006_ipaddress_nat_outside_list"),
        ("ipam", "0007_add_natural_indexing"),
        ("ipam", "0008_prefix_vlan_vlangroup_location"),
        ("ipam", "0009_alter_vlan_name"),
    ]

    dependencies = [
        ("ipam", "0002_initial_part_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregate",
            name="broadcast",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True),
        ),
        migrations.AlterField(
            model_name="aggregate",
            name="network",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="broadcast",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="host",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="broadcast",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="network",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True),
        ),
        migrations.RunPython(
            code=fixup_p2p_broadcast,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="rir",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=None
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="nat_inside",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nat_outside_list",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="assigned_object_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="dns_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, hyphens, periods, and underscores are allowed in DNS names",
                        regex="^[0-9A-Za-z._-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="role",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="prefix",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prefixes",
                to="dcim.location",
            ),
        ),
        migrations.AddField(
            model_name="vlan",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vlans",
                to="dcim.location",
            ),
        ),
        migrations.AddField(
            model_name="vlangroup",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vlan_groups",
                to="dcim.location",
            ),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
