# Generated by Django 3.1.7 on 2021-02-24 03:56

from django.db import migrations, models
import django.db.models.expressions
import nautobot.ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0002_initial_part_2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prefix",
            options={
                "ordering": (
                    django.db.models.expressions.OrderBy(django.db.models.expressions.F("vrf__name"), nulls_first=True),
                    "network",
                    "prefix_length",
                ),
                "verbose_name_plural": "prefixes",
            },
        ),
        migrations.AddField(
            model_name="prefix",
            name="broadcast",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b"", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prefix",
            name="network",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b"", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prefix",
            name="prefix_length",
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="aggregate",
            options={"ordering": ("network", "broadcast", "pk")},
        ),
        migrations.AddField(
            model_name="aggregate",
            name="broadcast",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b"", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aggregate",
            name="network",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b"", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aggregate",
            name="prefix_length",
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="ipaddress",
            options={
                "ordering": ("host", "prefix_length", "pk"),
                "verbose_name": "IP address",
                "verbose_name_plural": "IP addresses",
            },
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="broadcast",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b"", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="host",
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b"", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="prefix_length",
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
