# Generated by Django 3.1.7 on 2021-02-24 05:59

from django.db import migrations, models
import nautobot.ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_auto_20210224_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregate',
            options={'ordering': ('network', 'broadcast', 'pk')},
        ),
        migrations.RemoveField(
            model_name='aggregate',
            name='prefix',
        ),
        migrations.AddField(
            model_name='aggregate',
            name='broadcast',
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b'', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregate',
            name='network',
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b'', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aggregate',
            name='prefix_length',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
