# Generated by Django 3.1.13 on 2021-08-05 19:24

from django.db import migrations
import nautobot.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0004_fixup_p2p_broadcast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rir",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="name", unique=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="name", unique=True),
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="slug",
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from="name", unique=None),
        ),
    ]
