# Generated by Django 3.1.7 on 2021-02-24 20:58

from django.db import migrations, models
import nautobot.ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_auto_20210224_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ('host', 'prefix_length', 'pk'), 'verbose_name': 'IP address', 'verbose_name_plural': 'IP addresses'},
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='broadcast',
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b'', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='host',
            field=nautobot.ipam.fields.VarbinaryIPField(db_index=True, default=b'', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='prefix_length',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
