# Generated by Django 3.1.14 on 2022-03-19 23:21

from django.db import migrations
import nautobot.extras.managers


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0031_tag_content_types"),
        ("ipam", "0005_auto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregate",
            name="tags",
            field=nautobot.extras.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="tags",
            field=nautobot.extras.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="tags",
            field=nautobot.extras.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="routetarget",
            name="tags",
            field=nautobot.extras.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="service",
            name="tags",
            field=nautobot.extras.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="tags",
            field=nautobot.extras.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="tags",
            field=nautobot.extras.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
    ]
