# Generated by Django 3.2.12 on 2022-04-15 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0006_ipaddress_nat_outside_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipaddress",
            name="assigned_object_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="dns_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, hyphens, periods, and underscores are allowed in DNS names",
                        regex="^[0-9A-Za-z._-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="role",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
