# Generated by Django 3.2.13 on 2022-06-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0013_location_location_type"),
        ("ipam", "0007_add_natural_indexing"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefix",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prefixes",
                to="dcim.location",
            ),
        ),
        migrations.AddField(
            model_name="vlan",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vlans",
                to="dcim.location",
            ),
        ),
        migrations.AddField(
            model_name="vlangroup",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vlan_groups",
                to="dcim.location",
            ),
        ),
    ]
