# Generated by Django 3.2.16 on 2023-01-11 22:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("ipam", "0008_prefix_vlan_vlangroup_location"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="aggregate",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="ipaddress",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="prefix",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="routetarget",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="service",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="vlan",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="vrf",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
            ],
            database_operations=[],
        )
    ]
