from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.roles
from nautobot.extras.utils import migrate_role_data
from nautobot.ipam.choices import IPAddressRoleChoices


# From 0010_alter_ipam_role_add_new_role
# Generated by Django 3.2.16 on 2022-11-23 12:27

# From 0011_migrate_ipam_role_data
# Generated by Django 3.2.16 on 2022-11-23 12:27



def migrate_data_from_legacy_role_to_new_role(apps, schema):
    """Migrate VLAN/Prefix/IPAddress data from legacy_role to new_role."""
    to_role_model = apps.get_model("extras", "Role")
    ipam_role_model = apps.get_model("ipam", "Role")
    for model_to_migrate, from_role_model, from_role_choiceset in [
        (apps.get_model("ipam", "VLAN"), ipam_role_model, None),
        (apps.get_model("ipam", "Prefix"), ipam_role_model, None),
        (apps.get_model("ipam", "IPAddress"), None, IPAddressRoleChoices),
    ]:
        migrate_role_data(
            model_to_migrate=model_to_migrate,
            from_role_field_name="legacy_role",
            from_role_model=from_role_model,
            to_role_field_name="new_role",
            from_role_choiceset=from_role_choiceset,
            to_role_model=to_role_model,
        )


def migrate_data_from_new_role_to_legacy_role(apps, schema):
    """Migrate VLAN/Prefix/IPAddress data from new_role to legacy_role."""
    to_role_model = apps.get_model("extras", "Role")
    ipam_role_model = apps.get_model("ipam", "Role")
    for model_to_migrate, from_role_model, from_role_choiceset in [
        (apps.get_model("ipam", "VLAN"), ipam_role_model, None),
        (apps.get_model("ipam", "Prefix"), ipam_role_model, None),
        (apps.get_model("ipam", "IPAddress"), None, IPAddressRoleChoices),
    ]:
        migrate_role_data(
            model_to_migrate=model_to_migrate,
            from_role_field_name="new_role",
            from_role_model=to_role_model,
            to_role_field_name="legacy_role",
            to_role_model=from_role_model,
            to_role_choiceset=from_role_choiceset,
        )

# From 0012_rename_ipam_roles
# Generated by Django 3.2.16 on 2022-11-23 12:27


class Migration(migrations.Migration):

    replaces = [
        ("ipam", "0010_alter_ipam_role_add_new_role"),
        ("ipam", "0011_migrate_ipam_role_data"),
        ("ipam", "0012_rename_ipam_roles"),
    ]

    dependencies = [
        ("extras", "0062_collect_roles_from_related_apps_roles"),
        ("ipam", "0009_alter_vlan_name"),
    ]

    operations = [
        ####################
        # Prefix
        ####################
        migrations.RenameField(
            model_name="prefix",
            old_name="role",
            new_name="legacy_role",
        ),
        migrations.AddField(
            model_name="prefix",
            name="new_role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipam_prefix_related",
                to="extras.role",
            ),
        ),
        ####################
        # VLAN
        ####################
        migrations.RenameField(
            model_name="vlan",
            old_name="role",
            new_name="legacy_role",
        ),
        migrations.AddField(
            model_name="vlan",
            name="new_role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipam_vlan_related",
                to="extras.role",
            ),
        ),
        ####################
        # IPAddress
        ####################
        migrations.RenameField(
            model_name="ipaddress",
            old_name="role",
            new_name="legacy_role",
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="new_role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipam_ipaddress_related",
                to="extras.role",
            ),
        ),

        migrations.RunPython(migrate_data_from_legacy_role_to_new_role, migrate_data_from_new_role_to_legacy_role),

        ####################
        # Prefix
        ####################
        migrations.RemoveField(
            model_name="prefix",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="prefix",
            old_name="new_role",
            new_name="role",
        ),
        ####################
        # VLAN
        ####################
        migrations.RemoveField(
            model_name="vlan",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="vlan",
            old_name="new_role",
            new_name="role",
        ),
        ####################
        # IPAddress
        ####################
        migrations.RemoveField(
            model_name="ipaddress",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="ipaddress",
            old_name="new_role",
            new_name="role",
        ),
    ]
