# Generated by Django 3.2.16 on 2022-11-23 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0011_migrate_ipam_role_data"),
    ]

    operations = [
        ####################
        # Prefix
        ####################
        migrations.RemoveField(
            model_name="prefix",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="prefix",
            old_name="new_role",
            new_name="role",
        ),
        ####################
        # VLAN
        ####################
        migrations.RemoveField(
            model_name="vlan",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="vlan",
            old_name="new_role",
            new_name="role",
        ),
        ####################
        # IPAddress
        ####################
        migrations.RemoveField(
            model_name="ipaddress",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="ipaddress",
            old_name="new_role",
            new_name="role",
        ),
    ]
