# Generated by Django 3.2.16 on 2022-12-16 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0012_rename_ipam_roles"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
