from django.db import migrations, models

# From 0013_delete_role
# Generated by Django 3.2.16 on 2022-12-16 16:44

# From 0014_rename_foreign_keys_and_related_names
# Generated by Django 3.2.16 on 2023-01-11 15:54


class Migration(migrations.Migration):
    replaces = [
        ("ipam", "0013_delete_role"),
        ("ipam", "0014_rename_foreign_keys_and_related_names"),
        ("ipam", "0015_prefix_add_type"),
    ]

    dependencies = [
        ("ipam", "0012_rename_ipam_roles"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.AlterModelOptions(
            name="vlan",
            options={"ordering": ("site", "vlan_group", "vid"), "verbose_name": "VLAN", "verbose_name_plural": "VLANs"},
        ),
        migrations.RenameField(
            model_name="service",
            old_name="ipaddresses",
            new_name="ip_addresses",
        ),
        migrations.RenameField(
            model_name="vlan",
            old_name="group",
            new_name="vlan_group",
        ),
        migrations.AlterUniqueTogether(
            name="vlan",
            unique_together={("vlan_group", "vid"), ("vlan_group", "name")},
        ),
        migrations.AddField(
            model_name="prefix",
            name="type",
            field=models.CharField(default="network", max_length=50),
        ),
    ]
