# Generated by Django 3.2.17 on 2023-02-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0018_remove_site_foreign_key_from_ipam_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="rir",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="routetarget",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
