# Generated by Django 3.2.18 on 2023-03-07 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0036_remove_region_and_site"),
        ("virtualization", "0018_related_name_changes"),
        ("ipam", "0020_related_name_changes"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAddressToInterface",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.BooleanField(default=False)),
                ("destination", models.BooleanField(default=False)),
                ("default", models.BooleanField(default=False)),
                ("preferred", models.BooleanField(default=False)),
                ("primary", models.BooleanField(default=False)),
                ("secondary", models.BooleanField(default=False)),
                ("standby", models.BooleanField(default=False)),
                ("primary_for_device", models.BooleanField(default=False)),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.interface"
                    ),
                ),
                ("ip_address", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ipam.ipaddress")),
                (
                    "vm_interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtualization.vminterface",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
