# Generated by Django 3.2.16 on 2023-02-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0020_related_name_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefix",
            name="date_allocated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prefix",
            name="rir",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prefixes",
                to="ipam.rir",
            ),
        ),
        migrations.AddField(
            model_name="aggregate",
            name="migrated_to_prefix",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="migrated_aggregates",
                to="ipam.prefix",
            ),
        ),
    ]
