# Generated by Django 3.2.18 on 2023-03-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0029_ipam__namespaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefix",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="ipam.prefix",
            ),
        ),
        migrations.AlterIndexTogether(
            name="prefix",
            index_together={
                ("network", "broadcast", "prefix_length"),
                ("namespace", "network", "broadcast", "prefix_length"),
            },
        ),
    ]
