import sys

from django.db import migrations, models
import django.db.models.deletion

import nautobot.extras.models.statuses
from nautobot.extras.utils import fixup_null_statuses
import nautobot.ipam.utils.migrations
from nautobot.ipam.utils.migrations import increment_names_of_records_with_similar_names

# From 0031_ipam___data_migrations
# Generated by Django 3.2.18 on 2023-03-22 16:10


def reverse_it(apps, schema_editor):
    """Reverse Namespace migrations."""
    Namespace = apps.get_model("ipam", "Namespace")
    VRF = apps.get_model("ipam", "VRF")
    VRFDeviceAssignment = apps.get_model("ipam", "VRFDeviceAssignment")
    IPAddress = apps.get_model("ipam", "IPAddress")
    Prefix = apps.get_model("ipam", "Prefix")
    Interface = apps.get_model("dcim", "Interface")
    VMInterface = apps.get_model("virtualization", "VMInterface")

    ns_global = Namespace.objects.get(name="Global")
    Prefix.objects.update(namespace=ns_global)
    VRF.objects.update(namespace=ns_global)
    Namespace.objects.exclude(name=ns_global.name).delete()

    # Reset VRF-to-device/VM assignments.
    VRFDeviceAssignment.objects.all().delete()

    # Clear vrf from [VM]Interface objects.
    Interface.objects.update(vrf=None)
    VMInterface.objects.update(vrf=None)

    # Clear parenting.
    IPAddress.objects.update(parent=None, ip_version=None)
    Prefix.objects.update(parent=None, ip_version=None)

    # Remove objects created by migrations.
    Prefix.objects.filter(description__startswith="Created by Nautobot").delete()
    for vrf in VRF.objects.filter(description__startswith="Created by Nautobot"):
        original_vrf = (
            VRF.objects.exclude(description__startswith="Created by Nautobot")
            .filter(name=vrf.name, rd=vrf.rd, tenant=vrf.tenant)
            .first()
        )
        Prefix.objects.filter(vrf=vrf).update(vrf=original_vrf)
        vrf.delete()


def migrate_ipaddress_status_to_type(apps, schema_editor):
    """Migrate IPAddress.status DHCP/SLAAC to types."""
    Status = apps.get_model("extras", "Status")
    IPAddress = apps.get_model("ipam", "IPAddress")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ips_dhcp = IPAddress.objects.filter(status__name="DHCP")
    ips_slaac = IPAddress.objects.filter(status__name="SLAAC")
    ipaddress_ct = ContentType.objects.get_for_model(IPAddress)

    # First, update update type on any IPs with status DHCP/SLAAC.
    if any([ips_dhcp.exists(), ips_slaac.exists()]):
        status_migrated, _ = Status.objects.get_or_create(
            name="Migrated",
            defaults={
                "color": "ff0000",
                "description": "DHCP/SLAAC status replaced with `type` of same name by Nautobot 2.0 data migrations.",
            },
        )
        status_migrated.content_types.add(ipaddress_ct)

        # Update all objects of status=DHCP to type=DHCP & status=Migrated.
        if "test" not in sys.argv:
            print(">>> Migrating IPAddresses with status DHCP to type DHCP...")

        ips_dhcp.update(type="dhcp", status=status_migrated)

        # Update all objects of status=SLAAC to type=SLAAC & status=Migrated.
        if "test" not in sys.argv:
            print(">>> Migrating IPAddresses with status SLAAC to type SLAAC...")

        ips_slaac.update(type="slaac", status=status_migrated)

    # Then, delete the legacy status objects.
    for status_name in ("DHCP", "SLAAC"):
        try:
            status = Status.objects.get(name=status_name)
            # Clear the IPAddress content-type no matter what.
            status.content_types.remove(ipaddress_ct)
            if not status.content_types.exists():
                print(f">>> Deleting Status {status_name}")
                status.delete()
        except (models.ProtectedError, Status.DoesNotExist):
            pass


def revert_ipaddress_type_to_status(apps, schema_editor):
    """Revert IPAddress.type DHCP/SLAAC to status."""
    Status = apps.get_model("extras", "Status")
    IPAddress = apps.get_model("ipam", "IPAddress")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ipaddress_ct = ContentType.objects.get_for_model(IPAddress)
    defaults = {"color": "4caf50"}
    type_map = {
        "DHCP": "Dynamically assigned IPv4/IPv6 address",
        "SLAAC": "Dynamically assigned IPv6 address",
    }

    # Recreate the DHCP/SLAAC statuses.
    for type_name, description in type_map.items():
        ips = IPAddress.objects.filter(type=type_name.lower())
        if ips.exists():
            defaults["description"] = description
            status, _ = Status.objects.get_or_create(name=type_name, defaults=defaults)
            status.content_types.add(ipaddress_ct)
            ips.update(status=status)


# From 0032_ipam__namespaces_finish
# Generated by Django 3.2.18 on 2023-05-30 19:06


# From 0033_fixup_null_statuses
def migrate_null_statuses(apps, schema):
    status_model = apps.get_model("extras", "Status")
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model_name in (
        "IPAddress",
        "Prefix",
        "VLAN",
    ):
        model = apps.get_model("ipam", model_name)
        model_ct = ContentType.objects.get_for_model(model)
        fixup_null_statuses(model=model, model_contenttype=model_ct, status_model=status_model)


# From 0034_status_nonnullable
# Generated by Django 3.2.18 on 2023-05-19 18:05

# From 0035_ensure_all_services_fit_uniqueness_constraint
# Generated by Django 3.2.18 on 2023-06-06 14:57


def make_sure_service_name_is_unique(service_list, parent, cache):
    """
    Args:
        service_list (list): Service instances that are associated to Devices or Virtual Machines.
        parent (str): could be either "device" or "virtual_machine".
        cache (dict): dictionary that contains Device/Virtual Machine instances as Key and associated Service instances' names as Value.
    """
    for service in service_list:
        host = getattr(service, parent)
        service_names = cache.setdefault(host, set())
        count = 1
        service_name = service.name
        while service_name in service_names:
            appendage = f"_{count}"
            len_appendage = len(appendage)
            length_overflow = len(service_name) + len_appendage - 100
            if length_overflow > 0:
                service_name = service_name[: len(service_name) - length_overflow]
            service_name += appendage
            count += 1

        if service_name != service.name:
            print(f'    Service instance {service.id} is being renamed to "{service_name}" for uniqueness')
            service.name = service_name
            service.save()
        cache[host].add(service_name)


def ensure_all_existing_services_fit_uniqueness_constraints(apps, schema_editor):
    """
    Migration function to ensure that all existing Service instances fit the uniqueness constraints [name, device] or [name, vm]
    By enumerating Service instances associated with a device/vm and appending unique indices to names of the Service instances.
    """
    Service = apps.get_model("ipam", "Service")
    device_services = Service.objects.filter(device__isnull=False)
    device_to_service = {}
    make_sure_service_name_is_unique(device_services, "device", device_to_service)

    vm_services = Service.objects.filter(virtual_machine__isnull=False)
    vm_to_service = {}
    make_sure_service_name_is_unique(vm_services, "virtual_machine", vm_to_service)


# From 0036_add_uniqueness_constraints_to_service
# Generated by Django 3.2.18 on 2023-06-06 17:44

# From 0037_data_migration_vlan_group_name_uniqueness
# Generated by Django 3.2.18 on 2023-06-07 16:31


DEFAULT_VLAN_GROUP_BASENAME = "Default VLAN Group"


def vlan_group_name_uniqueness_constraints(apps, schema_editor):
    VLANGroup = apps.get_model("ipam", "vlangroup")

    increment_names_of_records_with_similar_names(VLANGroup)


# From 0038_vlan_group_name_unique_remove_slug
# Generated by Django 3.2.18 on 2023-06-07 16:24


class Migration(migrations.Migration):
    replaces = [
        ("ipam", "0031_ipam___data_migrations"),
        ("ipam", "0032_ipam__namespaces_finish"),
        ("ipam", "0033_fixup_null_statuses"),
        ("ipam", "0034_status_nonnullable"),
        ("ipam", "0035_ensure_all_services_fit_uniqueness_constraint"),
        ("ipam", "0036_add_uniqueness_constraints_to_service"),
        ("ipam", "0037_data_migration_vlan_group_name_uniqueness"),
        ("ipam", "0038_vlan_group_name_unique_remove_slug"),
    ]

    dependencies = [
        ("ipam", "0030_ipam__namespaces"),
        ("dcim", "0045_ipam__namespaces"),
        ("virtualization", "0023_ipam__namespaces"),
    ]

    operations = [
        migrations.RunPython(
            code=nautobot.ipam.utils.migrations.process_namespaces,
            reverse_code=reverse_it,
        ),
        migrations.RunPython(
            code=migrate_ipaddress_status_to_type,
            reverse_code=revert_ipaddress_type_to_status,
        ),
        migrations.AlterUniqueTogether(
            name="vrf",
            unique_together={("namespace", "rd")},
        ),
        migrations.AlterUniqueTogether(
            name="prefix",
            unique_together={("namespace", "network", "prefix_length")},
        ),
        migrations.AlterUniqueTogether(
            name="ipaddress",
            unique_together={("parent", "host")},
        ),
        migrations.RemoveField(
            model_name="ipaddress",
            name="broadcast",
        ),
        migrations.RemoveField(
            model_name="ipaddress",
            name="vrf",
        ),
        migrations.RenameField(
            model_name="ipaddress",
            old_name="prefix_length",
            new_name="mask_length",
        ),
        migrations.AlterModelOptions(
            name="ipaddress",
            options={
                "ordering": ("ip_version", "host", "mask_length"),
                "verbose_name": "IP address",
                "verbose_name_plural": "IP addresses",
            },
        ),
        migrations.RemoveField(
            model_name="prefix",
            name="vrf",
        ),
        migrations.RemoveField(
            model_name="vrf",
            name="enforce_unique",
        ),
        migrations.RenameField(
            model_name="vrf",
            old_name="prefixes_m2m",
            new_name="prefixes",
        ),
        migrations.AlterField(
            model_name="vrf",
            name="prefixes",
            field=models.ManyToManyField(related_name="vrfs", through="ipam.VRFPrefixAssignment", to="ipam.Prefix"),
        ),
        migrations.RunPython(migrate_null_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ipaddress",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="ip_addresses", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="prefixes", to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, related_name="vlans", to="extras.status"
            ),
        ),
        migrations.RunPython(ensure_all_existing_services_fit_uniqueness_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(fields=("name", "device"), name="unique_device_service_name"),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("name", "virtual_machine"), name="unique_virtual_machine_service_name"
            ),
        ),
        migrations.RunPython(
            vlan_group_name_uniqueness_constraints,
            migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="vlangroup",
            unique_together={},
        ),
        migrations.RemoveField(
            model_name="vlangroup",
            name="slug",
        ),
    ]
