# Generated by Django 3.2.18 on 2023-03-30 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0032_ipam__ipaddress__add_parent"),
    ]

    operations = []
