# Generated by Django 3.2.18 on 2023-06-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("ipam", "0035_vlan_vlan_group_default_values")]

    operations = [
        migrations.AlterField(
            model_name="vlan",
            name="vlan_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="vlans", to="ipam.vlangroup"
            ),
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="vlangroup",
            unique_together={("location", "slug")},
        ),
    ]
