# Generated by Django 3.2.18 on 2023-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ipam", "0037_data_migration_vlan_group_name_uniqueness")]

    operations = [
        migrations.AlterField(
            model_name="vlangroup",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="vlangroup",
            unique_together={},
        ),
        migrations.RemoveField(
            model_name="vlangroup",
            name="slug",
        ),
    ]
