# Generated by Django 3.2.23 on 2023-12-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0038_vlan_group_name_unique_remove_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipaddresstointerface",
            name="ip_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="interface_assignments", to="ipam.ipaddress"
            ),
        ),
    ]
