from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.db import migrations
from django.db.models.functions import Length
from nautobot.ipam.choices import IPAddressVersionChoices
from nautobot.ipam.constants import IPV4_BYTE_LENGTH, IPV6_BYTE_LENGTH
import nautobot.extras.models.roles
import nautobot.extras.models.statuses


# From 0039_alter_ipaddresstointerface_ip_address
# Generated by Django 3.2.23 on 2023-12-01 14:09

# From 0040_vlan_prefix_locations
# Generated by Django 3.2.23 on 2024-01-03 17:59

# From 0041_vlan_prefix_locations_data_migration
# Generated by Django 3.2.23 on 2024-01-03 17:59

# From 0042_remove_location_from_vlan_and_prefix
# Generated by Django 3.2.23 on 2024-01-11 12:29

# From 0043_fixup_null_ip_version
# Generated by Django 3.2.24 on 2024-02-12 19:57

# From 0044_ip_version_nonnullable
# Generated by Django 3.2.24 on 2024-02-12 19:58

# From 0045_alter_vlangroup_options
# Generated by Django 3.2.24 on 2024-02-14 14:03

# From 0046_update_all_charfields_max_length_to_255
# Generated by Django 3.2.24 on 2024-02-29 07:45

# From 0047_alter_ipaddress_role_alter_ipaddress_status_and_more
# Generated by Django 4.2.9 on 2024-01-17 18:52

# From 0041_vlan_prefix_locations_data_migration
def migrate_location_into_locations(apps, schema):
    VLAN = apps.get_model("ipam", "VLAN")
    Prefix = apps.get_model("ipam", "Prefix")

    for vlan in VLAN.objects.filter(location__isnull=False):
        vlan.locations.add(vlan.location)

    for prefix in Prefix.objects.filter(location__isnull=False):
        prefix.locations.add(prefix.location)

# From 0043_fixup_null_ip_version
def fixup_null_ip_version_values(apps, schema):
    IPAddress = apps.get_model("ipam", "IPAddress")
    Prefix = apps.get_model("ipam", "Prefix")

    ips_to_fixup = IPAddress.objects.filter(ip_version__isnull=True).annotate(host_length=Length("host"))
    ips_to_fixup.filter(host_length=IPV4_BYTE_LENGTH).update(ip_version=IPAddressVersionChoices.VERSION_4)
    ips_to_fixup.filter(host_length=IPV6_BYTE_LENGTH).update(ip_version=IPAddressVersionChoices.VERSION_6)

    prefixes_to_fixup = Prefix.objects.filter(ip_version__isnull=True).annotate(network_length=Length("network"))
    prefixes_to_fixup.filter(network_length=IPV4_BYTE_LENGTH).update(ip_version=IPAddressVersionChoices.VERSION_4)
    prefixes_to_fixup.filter(network_length=IPV6_BYTE_LENGTH).update(ip_version=IPAddressVersionChoices.VERSION_6)


class Migration(migrations.Migration):

    replaces = [
        ("ipam", "0039_alter_ipaddresstointerface_ip_address"),
        ("ipam", "0040_vlan_prefix_locations"),
        ("ipam", "0041_vlan_prefix_locations_data_migration"),
        ("ipam", "0042_remove_location_from_vlan_and_prefix"),
        ("ipam", "0043_fixup_null_ip_version"),
        ("ipam", "0044_ip_version_nonnullable"),
        ("ipam", "0045_alter_vlangroup_options"),
        ("ipam", "0046_update_all_charfields_max_length_to_255"),
        ("ipam", "0047_alter_ipaddress_role_alter_ipaddress_status_and_more"),
    ]

    dependencies = [
        ("ipam", "0038_vlan_group_name_unique_remove_slug"),
    ]

    operations = [

        migrations.AlterField(
            model_name="ipaddresstointerface",
            name="ip_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="interface_assignments", to="ipam.ipaddress"
            ),
        ),


        migrations.CreateModel(
            name="VLANLocationAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vlan_assignments", to="dcim.location"
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="location_assignments", to="ipam.vlan"
                    ),
                ),
            ],
            options={
                "unique_together": {("vlan", "location")},
                "ordering": ["vlan", "location"],
            },
        ),
        migrations.CreateModel(
            name="PrefixLocationAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefix_assignments",
                        to="dcim.location",
                    ),
                ),
                (
                    "prefix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_assignments",
                        to="ipam.prefix",
                    ),
                ),
            ],
            options={
                "unique_together": {("prefix", "location")},
                "ordering": ["prefix", "location"],
            },
        ),
        migrations.AddField(
            model_name="prefix",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="prefixes", through="ipam.PrefixLocationAssignment", to="dcim.Location"
            ),
        ),
        migrations.AddField(
            model_name="vlan",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="vlans", through="ipam.VLANLocationAssignment", to="dcim.Location"
            ),
        ),


        migrations.RunPython(migrate_location_into_locations, migrations.RunPython.noop),


        migrations.AlterModelOptions(
            name="vlan",
            options={"ordering": ("vlan_group", "vid"), "verbose_name": "VLAN", "verbose_name_plural": "VLANs"},
        ),
        migrations.RemoveField(
            model_name="vlan",
            name="location",
        ),
        migrations.RemoveField(
            model_name="prefix",
            name="location",
        ),

migrations.RunPython(fixup_null_ip_version_values, migrations.RunPython.noop),


        migrations.AlterField(
            model_name="ipaddress",
            name="ip_version",
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="ip_version",
            field=models.IntegerField(db_index=True, editable=False),
        ),


        migrations.AlterModelOptions(
            name="vlangroup",
            options={"ordering": ("name",), "verbose_name": "VLAN group", "verbose_name_plural": "VLAN groups"},
        ),


        migrations.AlterField(
            model_name="ipaddress",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="namespace",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rir",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rir",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="routetarget",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vlangroup",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vrfdeviceassignment",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),


        migrations.AlterField(
            model_name="ipaddress",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
    ]
