# Generated by Django 3.2.23 on 2024-01-11 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0052_fix_interface_redundancy_group_created"),
        ("ipam", "0041_vlan_prefix_locations_data_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vlan",
            options={"ordering": ("vlan_group", "vid"), "verbose_name": "VLAN", "verbose_name_plural": "VLANs"},
        ),
        migrations.RemoveField(
            model_name="vlan",
            name="location",
        ),
        migrations.RemoveField(
            model_name="prefix",
            name="location",
        ),
    ]
