# Generated by Django 3.2.24 on 2024-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0043_fixup_null_ip_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipaddress",
            name="ip_version",
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="prefix",
            name="ip_version",
            field=models.IntegerField(db_index=True, editable=False),
        ),
    ]
