# Generated by Django 3.2.24 on 2024-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0056_softwareimage_m2m_and_device_fk"),
        ("ipam", "0044_ip_version_nonnullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefix",
            name="locations",
            field=models.ManyToManyField(blank=True, related_name="prefixes", to="dcim.Location"),
        ),
    ]
