# Generated by Django 3.2.24 on 2024-02-13 15:53

from django.db import migrations


def migrate_location_into_locations(apps, schema):
    Prefix = apps.get_model("ipam", "Prefix")
    for prefix in Prefix.objects.filter(location__isnull=False):
        prefix.locations.add(prefix.location)


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0045_prefix_add_locations"),
    ]

    operations = [
        migrations.RunPython(migrate_location_into_locations, migrations.RunPython.noop),
    ]
