from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.statuses
from nautobot.extras.management import clear_status_choices, populate_status_choices


# From 0048_vrf_status
# Generated by Django 4.2.15 on 2024-08-26 17:20

# From 0049_vrf_data_migration
# Generated by Django 4.2.15 on 2024-08-26 18:05

# From 0049_vrf_data_migration
def populate_vrf_status_choices(apps, schema_editor):
    """Create default Status records for the VRF model."""
    populate_status_choices(apps, schema_editor, models=["ipam.VRF"])


def clear_vrf_status_choices(apps, schema_editor):
    """Remove default Status records for the VRF model."""
    clear_status_choices(apps, schema_editor, models=["ipam.VRF"])


class Migration(migrations.Migration):

    replaces = [
        ("ipam", "0048_vrf_status"),
        ("ipam", "0049_vrf_data_migration"),
    ]

    dependencies = [
        ("extras", "0114_computedfield_grouping"),
        ("ipam", "0047_alter_ipaddress_role_alter_ipaddress_status_and_more"),
    ]

    operations = [

        migrations.AddField(
            model_name="vrf",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),


        migrations.RunPython(populate_vrf_status_choices, clear_vrf_status_choices),
    ]
