# Generated by Django 4.2.15 on 2024-08-21 19:32

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.statuses
import uuid

def add_status_association(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Status = apps.get_model("extras", "Status")

    # Get the ContentType for ipam.vrf
    vrf_content_type = ContentType.objects.get(app_label="ipam", model="vrf")

    # Specify the statuses you want to associate with ipam.vrf
    statuses = ["Active", "Planned", "Deprecated"]  # replace with your statuses

    for status_name in statuses:
        status = Status.objects.get(name=status_name)
        status.content_types.add(vrf_content_type)

class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0114_computedfield_grouping'),
        ('ipam', '0047_alter_ipaddress_role_alter_ipaddress_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrf',
            name='status',
            field=nautobot.extras.models.statuses.StatusField(default=uuid.UUID('213c9792-9830-4164-944b-ecde42b44116'), on_delete=django.db.models.deletion.PROTECT, to='extras.status'),
        ),
        migrations.RunPython(add_status_association),
    ]
