# Generated by Django 4.2.15 on 2024-09-12 11:59

from django.db import migrations
import nautobot.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0047_alter_ipaddress_role_alter_ipaddress_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlangroup',
            name='range',
            field=nautobot.core.models.fields.PositiveRangeNumberTextField(default='1-4094'),
        ),
    ]
