# Generated by Django 3.2.24 on 2024-02-29 11:27

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0055_softwareimage_softwareversion_data_migration"),
        ("ipam", "0048_alter_vlangroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefix",
            name="locations",
            field=models.ManyToManyField(blank=True, related_name="_prefixes", to="dcim.Location"),
        ),
        migrations.AlterField(
            model_name="vlan",
            name="locations",
            field=models.ManyToManyField(blank=True, related_name="_vlans", to="dcim.Location"),
        ),
        migrations.CreateModel(
            name="VLANLocationAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vlan_assignments", to="dcim.location"
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="ipam.vlan"),
                ),
            ],
            options={
                "unique_together": {("vlan", "location")},
            },
        ),
        migrations.CreateModel(
            name="PrefixLocationAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefix_assignments",
                        to="dcim.location",
                    ),
                ),
                (
                    "prefix",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="ipam.prefix"),
                ),
            ],
            options={
                "unique_together": {("prefix", "location")},
            },
        ),
        migrations.AddField(
            model_name="prefix",
            name="_locations",
            field=models.ManyToManyField(
                blank=True, related_name="prefixes", through="ipam.PrefixLocationAssignment", to="dcim.Location"
            ),
        ),
        migrations.AddField(
            model_name="vlan",
            name="_locations",
            field=models.ManyToManyField(
                blank=True, related_name="vlans", through="ipam.VLANLocationAssignment", to="dcim.Location"
            ),
        ),
    ]
