# Generated by Django 3.2.24 on 2024-02-29 11:27

from django.db import migrations


def migrate_prefix_vlan_locations_records(apps, schema):
    Prefix = apps.get_model("ipam", "Prefix")
    VLAN = apps.get_model("ipam", "VLAN")
    # Location = apps.get_model("dcim", "Location")
    # PrefixLocationAssignment = apps.get_model("ipam", "PrefixLocationAssignment")
    # VLANLocationAssignment = apps.get_model("ipam", "VLANLocationAssignment")

    for model in (Prefix, VLAN):
        for instance in model.objects.filter(locations__isnull=False):
            instance._locations.set(instance.locations.all())


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0049_create_vlan_location_and_prefix_location_through_models"),
    ]

    operations = [migrations.RunPython(migrate_prefix_vlan_locations_records, migrations.RunPython.noop)]
