from django.db import migrations, models
import django.db.models.deletion

# From 0051_added_optional_vrf_relationship_to_vdc
# Generated by Django 4.2.19 on 2025-02-24 21:20

# From 0052_alter_ipaddress_index_together_and_more
# Generated by Django 4.2.20 on 2025-07-17 16:10

# From 0053_alter_vrfdeviceassignment_options_and_more
# Generated by Django 4.2.23 on 2025-09-17 16:07


class Migration(migrations.Migration):
    replaces = [
        ("ipam", "0051_added_optional_vrf_relationship_to_vdc"),
        ("ipam", "0052_alter_ipaddress_index_together_and_more"),
        ("ipam", "0053_alter_vrfdeviceassignment_options_and_more"),
    ]

    dependencies = [
        ("virtualization", "0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more"),
        ("dcim", "0067_controllermanageddevicegroup_tenant"),
        ("ipam", "0050_vlangroup_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="vrf",
            name="virtual_device_contexts",
            field=models.ManyToManyField(
                related_name="vrfs", through="ipam.VRFDeviceAssignment", to="dcim.virtualdevicecontext"
            ),
        ),
        migrations.AddField(
            model_name="vrfdeviceassignment",
            name="virtual_device_context",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vrf_assignments",
                to="dcim.virtualdevicecontext",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vrfdeviceassignment",
            unique_together={
                ("vrf", "virtual_device_context"),
                ("vrf", "virtual_machine"),
                ("vrf", "device"),
            },
        ),
        migrations.AlterIndexTogether(
            name="ipaddress",
            index_together={("ip_version", "host", "mask_length")},
        ),
        migrations.AlterIndexTogether(
            name="prefix",
            index_together={
                ("namespace", "ip_version", "network", "prefix_length"),
                ("namespace", "network", "broadcast", "prefix_length"),
                ("network", "broadcast", "prefix_length"),
            },
        ),
        migrations.AlterIndexTogether(
            name="vrf",
            index_together={("namespace", "name", "rd")},
        ),
        migrations.AlterModelOptions(
            name="vrfdeviceassignment",
            options={"verbose_name": "VRF-device assignment"},
        ),
        migrations.AlterModelOptions(
            name="vrfprefixassignment",
            options={"verbose_name": "VRF-prefix assignment"},
        ),
    ]
