# Generated by Django 3.2.24 on 2024-02-29 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0050_migrate_vlan_prefix_logations_records_into_through_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prefix",
            name="locations",
        ),
        migrations.RemoveField(
            model_name="vlan",
            name="locations",
        ),
    ]
