# Generated by Django 4.2.20 on 2025-07-17 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0051_added_optional_vrf_relationship_to_vdc"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="ipaddress",
            index_together={("ip_version", "host", "mask_length")},
        ),
        migrations.AlterIndexTogether(
            name="prefix",
            index_together={
                ("namespace", "ip_version", "network", "prefix_length"),
                ("namespace", "network", "broadcast", "prefix_length"),
                ("network", "broadcast", "prefix_length"),
            },
        ),
        migrations.AlterIndexTogether(
            name="vrf",
            index_together={("namespace", "name", "rd")},
        ),
    ]
