# Generated by Django 5.2.4 on 2025-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0070_alter_controllermanageddevicegroup_radio_profiles_and_more"),
        ("ipam", "0051_added_optional_vrf_relationship_to_vdc"),
        ("virtualization", "0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="prefix",
            new_name="ipam_prefix_namespa_ec3758_idx",
            old_fields=("namespace", "network", "broadcast", "prefix_length"),
        ),
        migrations.RenameIndex(
            model_name="prefix",
            new_name="ipam_prefix_network_e89faf_idx",
            old_fields=("network", "broadcast", "prefix_length"),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="devices",
            field=models.ManyToManyField(
                related_name="vrfs",
                through="ipam.VRFDeviceAssignment",
                through_fields=("vrf", "device"),
                to="dcim.device",
            ),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="virtual_device_contexts",
            field=models.ManyToManyField(
                related_name="vrfs",
                through="ipam.VRFDeviceAssignment",
                through_fields=("vrf", "virtual_device_context"),
                to="dcim.virtualdevicecontext",
            ),
        ),
        migrations.AlterField(
            model_name="vrf",
            name="virtual_machines",
            field=models.ManyToManyField(
                related_name="vrfs",
                through="ipam.VRFDeviceAssignment",
                through_fields=("vrf", "virtual_machine"),
                to="virtualization.virtualmachine",
            ),
        ),
    ]
