# Generated by Django 4.2.23 on 2025-09-17 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0052_alter_ipaddress_index_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vrfdeviceassignment",
            options={"verbose_name": "VRF-device assignment"},
        ),
        migrations.AlterModelOptions(
            name="vrfprefixassignment",
            options={"verbose_name": "VRF-prefix assignment"},
        ),
    ]
