# Generated by Django 4.2.23 on 2025-08-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
        ("ipam", "0053_alter_vrfdeviceassignment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="namespace",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="namespaces",
                to="tenancy.tenant",
            ),
        ),
    ]
