# Generated by Django 5.2.9 on 2026-05-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0055_rename_ipaddress_ip_version_host_mask_length_ipam_ipaddr_ip_vers_d82ba5_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vrfdeviceassignment",
            options={
                "ordering": ["vrf_id", "device_id", "virtual_machine_id", "virtual_device_context_id"],
                "verbose_name": "VRF-device assignment",
            },
        ),
        migrations.AlterModelOptions(
            name="vrfprefixassignment",
            options={
                "ordering": ["vrf_id", "prefix_id"],
                "verbose_name": "VRF-prefix assignment",
            },
        ),
    ]
