# Generated by Django 5.2.14 on 2026-06-11 13:04

import uuid

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.roles
import nautobot.extras.models.statuses
import nautobot.ipam.fields


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0146_computedfield_output_type"),
        ("ipam", "0056_alter_vrfdeviceassignment_ordering_vrfprefixassignment_ordering"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPRange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("start_host", nautobot.ipam.fields.VarbinaryIPField(db_index=True)),
                ("end_host", nautobot.ipam.fields.VarbinaryIPField(db_index=True)),
                ("ip_version", models.IntegerField(db_index=True, editable=False)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("count_as_utilized", models.BooleanField(default=False)),
                ("is_exclusive", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ip_ranges",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "role",
                    nautobot.extras.models.roles.RoleField(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        on_delete=django.db.models.deletion.PROTECT, to="extras.status"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ip_ranges",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Range",
                "verbose_name_plural": "IP Ranges",
                "ordering": ("parent__namespace", "ip_version", "start_host"),
                "indexes": [
                    models.Index(fields=["ip_version", "start_host", "end_host"], name="ipam_iprang_ip_vers_a40084_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("parent", "start_host"), name="unique_iprange_parent_start")
                ],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
