apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: media-root
  name: media-root
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
