---
dev_addr: "127.0.0.1:8001"
site_dir: "example_plugin/static/example_plugin/docs"
site_name: "Example Plugin Documentation"
copyright: "Copyright &copy; The Authors"
theme:
  name: "material"
  navigation_depth: 4
  custom_dir: "docs/assets/overrides"
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "navigation.tracking"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "search.suggest"
    - "search.highlight"
    - "search.share"
  favicon: "assets/favicon.ico"
  logo: "assets/nautobot_logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
extra_css:
  - "assets/extra.css"
extra:
  generator: false
  ntc_sponsor: true
  social:
    - icon: "fontawesome/solid/rss"
      link: "https://blog.networktocode.com/blog/tags/nautobot"
      name: "NetworkToCode Blog"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/playlist?list=PLjA0bhxgryJ2Ts4GJMDA-tPzVWEncv4pb"
      name: "Nautobot Videos"
    - icon: "fontawesome/brands/slack"
      link: "https://www.networktocode.com/community/"
      name: "NetworkToCode Community"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/nautobot/nautobot"
      name: "GitHub Repo"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/networktocode"
      name: "NetworkToCode Twitter"
markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "md_in_html"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
plugins:
  - "search"
  - "include-markdown"

nav:
  - Introduction: "index.md"
