dev_addr: '127.0.0.1:8001'
site_dir: example_plugin/static/example_plugin/docs
site_name: Example Plugin Documentation
theme:
    name: readthedocs
    navigation_depth: 4
    hljs_languages:
        - django
        - yaml
markdown_extensions:
    - admonition:
    - toc:
        permalink: true
plugins:
    - search
    - include-markdown
nav:
    - Introduction: 'index.md'
