---
name: ✨ Feature Request Beta
description: Propose a new Nautobot feature or enhancement
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: >
        **NOTE:** IF YOUR ISSUE DOES NOT FOLLOW THIS TEMPLATE, YOU WILL BE REQUIRED TO
        UPDATE THE ISSUE IN ORDER TO HAVE IT REVIEWED. This form is only for proposing
        specific new features or enhancements. If you have a general idea or question,
        please start a [discussion](https://github.com/nautobot/nautobot/discussions) instead.
  - type: dropdown
    id: persona
    attributes:
      label: As a ___WHO, the user persona___,
      description: Please choose the appropriate [persona](https://github.com/nautobot/nautobot/wiki/Personas)
      multiple: false
      options:
        - "Ozzie - Operator"
        - "Nelly - Network Engineer"
        - "Austin - Network Automation Engineer"
        - "Tammy - Tools Integrator"
        - "Mary - Manager"
        - "Patti - Platform Admin"
        - "Isabella - Infrastructure Owner"
        - "Dan - Data Owner"
        - "P.D. - Plugin Developer"
        - "Cora - Coder"
    validations:
      required: true
  - type: input
    id: what
    attributes:
      label: I want ___WHAT, the desired functionality to be implemented___,
      description: Please enter the desired functionality
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: So that ___WHY, the reason or value of the implemented functionality___.
      description: Please enter the reason for the desired functionality
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: I know this is done when... ___HOW.
      description: The requirements/acceptance criteria (a list) as to how this functionality should be implemented.
    validations:
      required: true
  - type: checkboxes
    id: pertains_to
    attributes:
      label: Optional - Feature groups this request pertains to.
      description: Please choose all feature groups this request pertains to.
      options:
        - label: Automation
        - label: Circuits
        - label: DCIM
        - label: IPAM
        - label: Misc (including Data Sources)
        - label: Organization
        - label: Plugins (and other Extensibility)
        - label: Security (Secrets, etc)
        - label: Image Management
        - label: UI/UX
        - label: Documentation
        - label: Other (not directly a platform feature)
  - type: textarea
    id: database_changes
    attributes:
      label: Database Changes
      description: >
        To support this new feature, does the necessary data already exist, or would new
        models need to be created or additional fields on existing models need to be added?

        It is OK to state you are unsure if this would or would not require changes.
  - type: textarea
    id: external_dependencies
    attributes:
      label: External Dependencies
      description: >
        To support this new feature, would it require changing or introducing new dependencies
        on external libraries or services?

        It is OK to suggest an external library that could pose as a reference implementation
        or be installed directly.