# Generated by Django 4.2.20 on 2025-04-03 18:14

import uuid

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
        ("extras", "0121_alter_team_contacts"),
        ("cloud", "0001_initial"),
        ("dcim", "0067_controllermanageddevicegroup_tenant"),
        ("ipam", "0050_vlangroup_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("certificate_type", models.CharField(blank=True, max_length=255)),
                ("certificate_file_path", models.CharField(blank=True, max_length=255)),
                ("chain_file_path", models.CharField(blank=True, max_length=255)),
                ("key_file_path", models.CharField(blank=True, max_length=255)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("cipher", models.CharField(blank=True, max_length=255)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate_profiles",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Profile",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HealthCheckMonitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("interval", models.PositiveIntegerField(blank=True, null=True)),
                ("retry", models.PositiveIntegerField(blank=True, null=True)),
                ("timeout", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65535)]
                    ),
                ),
                ("health_check_type", models.CharField(blank=True, max_length=255)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_check_monitors",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Check Monitor",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="LoadBalancerPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255)),
                ("load_balancing_algorithm", models.CharField(max_length=255)),
                (
                    "health_check_monitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_balancer_pools",
                        to="load_balancers.healthcheckmonitor",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_balancer_pools",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Load Balancer Pool",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="LoadBalancerPoolMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("port", models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
                ("ssl_offload", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Load Balancer Pool Member",
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VirtualServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65535)]
                    ),
                ),
                ("protocol", models.CharField(blank=True, max_length=255)),
                ("source_nat_type", models.CharField(blank=True, max_length=255)),
                ("load_balancer_type", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("ssl_offload", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Virtual Server",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VirtualServerCertificateProfileAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "certificate_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_server_assignments",
                        to="load_balancers.certificateprofile",
                    ),
                ),
                (
                    "virtual_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_profile_assignments",
                        to="load_balancers.virtualserver",
                    ),
                ),
            ],
            options={
                "ordering": ["virtual_server", "certificate_profile"],
                "unique_together": {("virtual_server", "certificate_profile")},
            },
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="certificate_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="virtual_servers",
                through="load_balancers.VirtualServerCertificateProfileAssignment",
                to="load_balancers.certificateprofile",
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="cloud_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_servers",
                to="cloud.cloudservice",
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_servers",
                to="dcim.device",
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="device_redundancy_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_servers",
                to="dcim.deviceredundancygroup",
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="health_check_monitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_servers",
                to="load_balancers.healthcheckmonitor",
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="load_balancer_pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_servers",
                to="load_balancers.loadbalancerpool",
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="source_nat_pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_servers",
                to="ipam.prefix",
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_servers",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="vip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="virtual_servers", to="ipam.ipaddress"
            ),
        ),
        migrations.AddField(
            model_name="virtualserver",
            name="virtual_chassis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_servers",
                to="dcim.virtualchassis",
            ),
        ),
        migrations.CreateModel(
            name="LoadBalancerPoolMemberCertificateProfileAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "certificate_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_balancer_pool_member_assignments",
                        to="load_balancers.certificateprofile",
                    ),
                ),
                (
                    "load_balancer_pool_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_profile_assignments",
                        to="load_balancers.loadbalancerpoolmember",
                    ),
                ),
            ],
            options={
                "ordering": ["load_balancer_pool_member", "certificate_profile"],
                "unique_together": {("load_balancer_pool_member", "certificate_profile")},
            },
        ),
        migrations.AddField(
            model_name="loadbalancerpoolmember",
            name="certificate_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="load_balancer_pool_members",
                through="load_balancers.LoadBalancerPoolMemberCertificateProfileAssignment",
                to="load_balancers.certificateprofile",
            ),
        ),
        migrations.AddField(
            model_name="loadbalancerpoolmember",
            name="health_check_monitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="load_balancer_pool_members",
                to="load_balancers.healthcheckmonitor",
            ),
        ),
        migrations.AddField(
            model_name="loadbalancerpoolmember",
            name="ip_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="load_balancer_pool_members",
                to="ipam.ipaddress",
            ),
        ),
        migrations.AddField(
            model_name="loadbalancerpoolmember",
            name="load_balancer_pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="load_balancer_pool_members",
                to="load_balancers.loadbalancerpool",
            ),
        ),
        migrations.AddField(
            model_name="loadbalancerpoolmember",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AddField(
            model_name="loadbalancerpoolmember",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="loadbalancerpoolmember",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="load_balancer_pool_members",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="virtualserver",
            unique_together={("vip", "port", "protocol")},
        ),
        migrations.AlterUniqueTogether(
            name="loadbalancerpoolmember",
            unique_together={("ip_address", "port", "load_balancer_pool")},
        ),
    ]
