# Generated by Django 4.2.19 on 2025-02-13 03:05

from django.db import migrations

from nautobot.extras.management import clear_status_choices, populate_status_choices


def populate_load_balancer_pool_member_status_choices(apps, schema_editor):
    """Populate the status choices for the LoadBalancerPoolMember model."""

    populate_status_choices(apps, schema_editor, models=["load_balancers.LoadBalancerPoolMember"])


def clear_load_balancer_pool_member_status_choices(apps, schema_editor):
    """Clear the status choices for the LoadBalancerPoolMember model."""
    clear_status_choices(apps, schema_editor, models=["load_balancers.LoadBalancerPoolMember"])


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0001_initial"),
        ("extras", "0001_initial_part_1"),
        ("load_balancers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_load_balancer_pool_member_status_choices,
            reverse_code=clear_load_balancer_pool_member_status_choices,
        ),
    ]
