# Generated by Django 5.2.16 on 2026-07-27 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0097_virtualdevicecontext_controller_managed_device_group'),
        ('load_balancers', '0002_create_default_statuses_pool_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualserver',
            name='virtual_device_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_context', to='dcim.virtualdevicecontext'),
        ),
    ]
