---
name: "Build Nautobot Image"
description: "Builds and pushes Nautobot image"
inputs:
  branch:
    description: "Branch Name Used In Tag"
    required: true
  image:
    description: "Produced Image Name"
    required: true
  latest:
    description: "Whether To Tag As Latest"
    required: true
  push:
    description: "Whether To Push"
    required: true
  python-version:
    description: "Python Version"
    required: true
  target:
    description: "Target Stage Name"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup Metadata"
      id: "metadata"
      uses: "docker/metadata-action@v4"
      with:
        images: "${{ inputs.image }}"
        flavor: |
          latest=false
        tags: |
          type=raw,value=${{ inputs.branch }}-py${{ inputs.python-version }}
          type=raw,value=${{ inputs.branch }}-{{sha}}-{{date 'X'}}-py${{ inputs.python-version }}
          type=raw,value=${{ inputs.branch }},enable=${{ inputs.latest }}
          type=raw,value=${{ inputs.branch }}-{{sha}}-{{date 'X'}},enable=${{ inputs.latest }}
          type=raw,value=latest,enable=${{ inputs.latest }}
          type=raw,value=latest-py${{ inputs.python-version }},enable=${{ inputs.latest }}
        labels: |
          org.opencontainers.image.title=Nautobot
    - name: "Build Dev"
      env:
        INVOKE_NAUTOBOT_PYTHON_VER: "${{ inputs.python-version }}"
      uses: "docker/build-push-action@v4"
      with:
        push: "${{ inputs.push }}"
        target: "${{ inputs.target }}"
        file: "docker/Dockerfile"
        platforms: "linux/amd64,linux/arm64"
        tags: "${{ steps.metadata.outputs.tags }}"
        labels: "${{ steps.metadata.outputs.labels }}"
        cache-from: "type=gha,scope=nautobot-${{ inputs.branch }}-${{ inputs.python-version }}"
        cache-to: "type=gha,mode=max,scope=nautobot-${{ inputs.branch }}-${{ inputs.python-version }}"
        context: "."
        build-args: |
          PYTHON_VER=${{ inputs.python-version }}
          DEPENDENCIES_BASE_BRANCH=${{ inputs.branch }}
          POETRY_PARALLEL=true
