from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
import nautobot.core.models.ordering
import nautobot.core.models.query_functions
from nautobot.extras.management import clear_status_choices, populate_status_choices
import nautobot.extras.models.roles
import nautobot.extras.models.statuses
from nautobot.extras.utils import migrate_role_data
from nautobot.virtualization.choices import VMInterfaceStatusChoices

# From 0002_virtualmachine_local_context_schema
# Generated by Django 3.1.12 on 2021-06-16 02:42

# From 0003_vminterface_verbose_name
# Generated by Django 3.1.13 on 2021-08-16 13:48

# From 0004_auto_slug
# Generated by Django 3.1.13 on 2021-08-05 03:23

# From 0005_add_natural_indexing
# Generated by Django 3.2.12 on 2022-04-15 17:39

# From 0006_vminterface_status
# Generated by Django 3.2.13 on 2022-05-04 21:21

# From 0007_vminterface_status_data_migration
# Generated by Django 3.1.14 on 2022-03-19 23:21


def populate_vminterface_status(apps, schema_editor):
    """
    Create/link default Status records for the VMInterface content-type; default all VMInterfaces to "active" status.
    """
    # Create VMInterface Statuses and add dcim.VMInterface to its content_types
    populate_status_choices(apps, schema_editor, models=["virtualization.VMInterface"])

    Status = apps.get_model("extras.Status")
    VMInterface = apps.get_model("virtualization.VMInterface")

    # populate existing interfaces status
    active_status = Status.objects.get(slug=VMInterfaceStatusChoices.STATUS_ACTIVE)
    for interface in VMInterface.objects.all():
        interface.status = active_status
        interface.save()


def clear_vminterface_status(apps, schema_editor):
    """
    Clear the status field on all VMInterfaces; de-link/delete all Status records from the VMInterface content-type.
    """
    VMInterface = apps.get_model("virtualization.VMInterface")

    for interface in VMInterface.objects.filter(status__isnull=False):
        interface.status = None
        interface.save()

    clear_status_choices(apps, schema_editor, models=["virtualization.VMInterface"])


# From 0008_vminterface_parent
# Generated by Django 3.2.12 on 2022-04-18 11:34

# From 0009_cluster_location
# Generated by Django 3.2.13 on 2022-06-15 14:00


# From 0010_vminterface_mac_address_data_migration
def null_macaddress_to_empty(apps, schema_editor):
    """Change null mac_address values to empty strings instead."""
    VMInterface = apps.get_model("virtualization.vminterface")
    VMInterface.objects.filter(mac_address__isnull=True).update(mac_address="")


# From 0011_alter_vminterface_mac_address
# Generated by Django 3.2.16 on 2022-12-22 19:10

# From 0012_alter_virtualmachine_role_add_new_role
# Generated by Django 3.2.16 on 2022-11-23 12:27

# From 0013_migrate_virtualmachine_role_data
# Generated by Django 3.2.16 on 2022-11-23 12:27


def migrate_data_from_legacy_role_to_new_role(apps, schema):
    """Migrate DeviceRole data from legacy_role to new_role."""
    model = apps.get_model("virtualization", "VirtualMachine")
    from_role_model = apps.get_model("dcim", "DeviceRole")
    to_role_model = apps.get_model("extras", "Role")
    migrate_role_data(
        model_to_migrate=model,
        from_role_field_name="legacy_role",
        from_role_model=from_role_model,
        to_role_field_name="new_role",
        to_role_model=to_role_model,
    )


def reverse_role_data_migrate(apps, schema):
    """Migrate DeviceRole data from new_role to legacy_role."""
    model = apps.get_model("virtualization", "VirtualMachine")
    from_role_model = apps.get_model("extras", "Role")
    to_role_model = apps.get_model("dcim", "DeviceRole")
    migrate_role_data(
        model_to_migrate=model,
        from_role_field_name="new_role",
        from_role_model=from_role_model,
        to_role_field_name="legacy_role",
        to_role_model=to_role_model,
    )


# From 0014_rename_virtualmachine_roles
# Generated by Django 3.2.16 on 2022-11-23 12:27


class Migration(migrations.Migration):
    replaces = [
        ("virtualization", "0002_virtualmachine_local_context_schema"),
        ("virtualization", "0003_vminterface_verbose_name"),
        ("virtualization", "0004_auto_slug"),
        ("virtualization", "0005_add_natural_indexing"),
        ("virtualization", "0006_vminterface_status"),
        ("virtualization", "0007_vminterface_status_data_migration"),
        ("virtualization", "0008_vminterface_parent"),
        ("virtualization", "0009_cluster_location"),
        ("virtualization", "0010_vminterface_mac_address_data_migration"),
        ("virtualization", "0011_alter_vminterface_mac_address"),
        ("virtualization", "0012_alter_virtualmachine_role_add_new_role"),
        ("virtualization", "0013_migrate_virtualmachine_role_data"),
        ("virtualization", "0014_rename_virtualmachine_roles"),
    ]

    dependencies = [
        ("extras", "0007_configcontextschema"),
        ("virtualization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualmachine",
            name="local_context_schema",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.configcontextschema"
            ),
        ),
        migrations.AlterModelOptions(
            name="vminterface",
            options={
                "ordering": ("virtual_machine", nautobot.core.models.query_functions.CollateAsChar("_name")),
                "verbose_name": "VM interface",
            },
        ),
        migrations.AlterField(
            model_name="clustergroup",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="clustertype",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=100,
                naturalize_function=nautobot.core.models.ordering.naturalize_interface,
            ),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vminterface",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtualization_vminterface_related",
                to="extras.status",
            ),
        ),
        migrations.RunPython(populate_vminterface_status, clear_vminterface_status),
        migrations.AddField(
            model_name="vminterface",
            name="parent_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_interfaces",
                to="virtualization.vminterface",
            ),
        ),
        migrations.AddField(
            model_name="vminterface",
            name="bridge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bridged_interfaces",
                to="virtualization.vminterface",
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clusters",
                to="dcim.location",
            ),
        ),
        migrations.RunPython(null_macaddress_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="vminterface",
            name="mac_address",
            field=nautobot.core.models.fields.MACAddressCharField(blank=True, default=""),
        ),
        migrations.RenameField(
            model_name="virtualmachine",
            old_name="role",
            new_name="legacy_role",
        ),
        migrations.AddField(
            model_name="virtualmachine",
            name="new_role",
            field=nautobot.extras.models.roles.RoleField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtualization_virtualmachine_related",
                to="extras.role",
            ),
        ),
        migrations.RunPython(migrate_data_from_legacy_role_to_new_role, reverse_role_data_migrate),
        migrations.RemoveField(
            model_name="virtualmachine",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="virtualmachine",
            old_name="new_role",
            new_name="role",
        ),
    ]
