# Generated by Django 3.1.13 on 2021-08-03 04:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("virtualization", "0002_virtualmachine_local_context_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clustergroup",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="clustertype",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
    ]
