# Generated by Django 3.1.14 on 2022-03-19 23:21

from django.db import migrations
import nautobot.extras.models.tags


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0031_tag_content_types"),
        ("virtualization", "0004_auto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="tags",
            field=nautobot.extras.models.tags.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="tags",
            field=nautobot.extras.models.tags.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="tags",
            field=nautobot.extras.models.tags.TaggableManager(
                related_name="vminterface", through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
    ]
