# Generated by Django 3.2.13 on 2022-05-07 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("virtualization", "0006_vminterface_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vminterface",
            name="parent_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_interfaces",
                to="virtualization.vminterface",
            ),
        ),
    ]
