# Generated by Django 3.2.16 on 2022-12-22 19:10

from django.db import migrations
import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("virtualization", "0010_vminterface_mac_address_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vminterface",
            name="mac_address",
            field=nautobot.core.models.fields.MACAddressCharField(blank=True, default=""),
        ),
    ]
