# Generated by Django 3.2.16 on 2023-01-11 22:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("virtualization", "0011_alter_vminterface_mac_address"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="cluster",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="virtualmachine",
                    name="tags",
                    field=taggit.managers.TaggableManager(through="core.TaggedItem", to="core.Tag"),
                ),
                migrations.AlterField(
                    model_name="vminterface",
                    name="tags",
                    field=taggit.managers.TaggableManager(
                        related_name="vminterface", through="core.TaggedItem", to="core.Tag"
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
