# Generated by Django 3.2.16 on 2022-11-23 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("virtualization", "0013_migrate_virtualmachine_role_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtualmachine",
            name="legacy_role",
        ),
        migrations.RenameField(
            model_name="virtualmachine",
            old_name="new_role",
            new_name="role",
        ),
    ]
