# Generated by Django 3.2.17 on 2023-02-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtualization", "0016_remove_site_foreign_key_from_cluster_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="clustergroup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="clustertype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
