# Generated by Django 3.2.18 on 2023-03-15 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("virtualization", "0019_vminterface_ip_addresses_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clustergroup",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="clustertype",
            name="slug",
        ),
    ]
