from django.db import migrations, models
import nautobot.core.models.fields
from django.db import migrations


# From 0021_tagsfield_and_vminterface_to_primarymodel
# Generated by Django 3.2.18 on 2023-04-21 13:59

# From 0022_vminterface_timestamps_data_migration
def zero_out_vminterface_timestamps(apps, schema_editor):
    """Set initial created/last_updated fields of existing VMInterfaces to None, rather than the time of migration."""
    VMInterface = apps.get_model("virtualization.vminterface")
    VMInterface.objects.all().update(created=None, last_updated=None)


class Migration(migrations.Migration):

    replaces = [
        ("virtualization", "0021_tagsfield_and_vminterface_to_primarymodel"),
        ("virtualization", "0022_vminterface_timestamps_data_migration"),
    ]

    dependencies = [
        ("extras", "0080_tagsfield"),
        ("virtualization", "0020_remove_clustergroup_clustertype_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="vminterface",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="vminterface",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),

        migrations.RunPython(zero_out_vminterface_timestamps, migrations.RunPython.noop),
    ]
