from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
import nautobot.core.models.ordering
import nautobot.extras.models.roles
import nautobot.extras.models.statuses
import nautobot.extras.utils

# From 0027_virtualmachine_software_image
# Generated by Django 3.2.23 on 2024-02-15 17:20

# From 0028_update_all_charfields_max_length_to_255
# Generated by Django 3.2.24 on 2024-02-29 07:45

# From 0029_add_role_field_to_interface_models
# Generated by Django 3.2.25 on 2024-04-01 13:36

# From 0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more
# Generated by Django 4.2.9 on 2024-01-17 18:52


class Migration(migrations.Migration):
    replaces = [
        ("virtualization", "0027_virtualmachine_software_image"),
        ("virtualization", "0028_update_all_charfields_max_length_to_255"),
        ("virtualization", "0029_add_role_field_to_interface_models"),
        ("virtualization", "0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more"),
    ]

    dependencies = [
        ("dcim", "0054_softwareimage_softwareversion"),
        ("virtualization", "0026_change_virtualmachine_primary_ip_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualmachine",
            name="software_image_files",
            field=models.ManyToManyField(blank=True, related_name="virtual_machines", to="dcim.SoftwareImageFile"),
        ),
        migrations.AddField(
            model_name="virtualmachine",
            name="software_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="virtual_machines",
                to="dcim.softwareversion",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="clustergroup",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="clustergroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="clustertype",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="clustertype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="_name",
            field=nautobot.core.models.fields.NaturalOrderingField(
                "name",
                blank=True,
                db_index=True,
                max_length=255,
                naturalize_function=nautobot.core.models.ordering.naturalize_interface,
            ),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vminterface",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vm_interfaces",
                to="extras.role",
            ),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="local_config_context_data_owner_content_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True,
                default=None,
                limit_choices_to=nautobot.extras.utils.FeatureQuery("config_context_owners"),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="local_config_context_schema",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.configcontextschema"
            ),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="virtualmachine",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="role",
            field=nautobot.extras.models.roles.RoleField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="vminterface",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
    ]
