# Generated by Django 4.2.20 on 2025-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_data_validation_engine", "0008_update_data_validation_engine_job_module_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minmaxvalidationrule",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="regularexpressionvalidationrule",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="requiredvalidationrule",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="uniquevalidationrule",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
