# Generated by Django 4.2.19 on 2025-03-10 20:47

from django.db import migrations


def update_data_validation_engine_job_module_name(apps, schema_editor):
    """
    Update the `module_name` for the Jobs to match the new location of the data validation engine.
    """
    Job = apps.get_model("extras", "Job")
    dve_jobs = Job.objects.filter(module_name="nautobot_data_validation_engine.jobs")
    dve_jobs.update(module_name="nautobot.nautobot_data_validation_engine.jobs")


def revert_data_validation_engine_job_module_name(apps, schema_editor):
    """
    Revert the `module_name` for the Jobs to match the old location of the data validation engine.
    """
    Job = apps.get_model("extras", "Job")
    dve_jobs = Job.objects.filter(module_name="nautobot.nautobot_data_validation_engine.jobs")
    dve_jobs.update(module_name="nautobot.nautobot_data_validation_engine.jobs").update(
        module_name="nautobot_data_validation_engine.jobs"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_data_validation_engine", "0007_alter_datacompliance_compliance_class_name_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_data_validation_engine_job_module_name,
            revert_data_validation_engine_job_module_name,
        ),
    ]
