[feature_toggles]
enable = nestedFolders,correlations,vizAndWidgetSplit

[dashboards]
# Set to the uid of the dashboard you want as the home dashboard
default_home_dashboard_path = /etc/grafana/provisioning/dashboards/Nautobot.json

[auth.anonymous]
enabled = true
org_name = Main Org.
org_role = Viewer
