# Generated by Django 3.0.3 on 2020-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0017_circuittype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='circuittermination',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='circuittype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
