# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0002_auto_20160620_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='admin_contact',
            field=models.TextField(blank=True, verbose_name=b'Admin contact'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='noc_contact',
            field=models.TextField(blank=True, verbose_name=b'NOC contact'),
        ),
    ]
