# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:24
import dcim.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0002_auto_20160622_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='asn',
            field=dcim.fields.ASNField(blank=True, null=True, verbose_name=b'ASN'),
        ),
    ]
