# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0006_terminations'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
