# Generated by Django 3.1 on 2020-10-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0021_cablepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuittermination',
            name='connected_endpoint',
        ),
    ]
