# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0044_virtualization'),
        ('virtualization', '0003_cluster_add_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_machines', to='dcim.DeviceRole'),
        ),
    ]
