# Generated by Django 2.2.8 on 2020-01-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0012_vm_name_nonunique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualmachine',
            options={'ordering': ('name', 'pk')},
        ),
    ]
