# Generated by Django 3.1.3 on 2021-02-17 21:29

import dcim.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0021_vm_add_local_context_data_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vminterface',
            name='mac_address',
            field=dcim.fields.MACAddressCharField(blank=True, null=True),
        ),
    ]
