# Generated by Django 3.1.3 on 2021-02-19 00:58

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0024_virtualmachine_status_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
