# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 15:44
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0008_prefix_change_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Active'), (2, b'Reserved'), (5, b'DHCP')], default=1, verbose_name=b'Status'),
        ),
    ]
