# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 19:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0017_ipaddress_roles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([]),
        ),
    ]
