# Generated by Django 3.0.3 on 2020-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0035_drop_ip_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='rir',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vlangroup',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aggregate',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vrf',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
