[tool.poetry]
name = "example_plugin_with_view_override"
version = "1.0.0"
description = "Nautobot plugin for testing override_views."
authors = ["Network to Code <opensource@networktocode.com>"]
license = "Apache-2.0"
packages = [
    {include = "example_plugin_with_view_override"}
]
