# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
