# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0002_auto_20160227_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='is_console_server',
            field=models.BooleanField(default=False, help_text=b'This type of device has console server ports', verbose_name=b'Is a console server'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='is_network_device',
            field=models.BooleanField(default=True, help_text=b'This type of device has network interfaces', verbose_name=b'Is a network device'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='is_pdu',
            field=models.BooleanField(default=False, help_text=b'This type of device has power outlets', verbose_name=b'Is a PDU'),
        ),
    ]
