# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:53
from __future__ import unicode_literals

from django.db import migrations
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0003_auto_20160628_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=True, null=True),
        ),
    ]
