# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 10:01
from __future__ import unicode_literals

from django.db import migrations, models
from ..fields import MACAddressField


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0003_auto_20160628_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='mac_address',
            field=MACAddressField(blank=True, null=True, verbose_name=b'MAC Address'),
        ),
    ]
