# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0004_auto_20160328_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['device__id', 'parent__id', 'name']},
        ),
    ]
