# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0008_auto_20160621_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 6, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 22, 14, 7, 52, 775280)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 6, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 22, 14, 8, 27, 534709)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 6, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 22, 14, 8, 37, 622017)),
            preserve_default=False,
        ),
    ]
