# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0038_wireless_interfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='mtu',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='MTU'),
        ),
    ]
