# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0057_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['site', 'group', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together=set([('group', 'name'), ('group', 'facility_id')]),
        ),
    ]
