# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0058_relax_rack_naming_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicetype',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
