# Generated by Django 2.0.8 on 2018-10-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0066_cables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='is_console_server',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='is_network_device',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='is_pdu',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='interface_ordering',
        ),
    ]
