# Generated by Django 2.0.9 on 2018-11-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0067_device_type_remove_qualifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='status',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
