# Generated by Django 2.2.6 on 2019-11-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0076_console_port_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweroutlet',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='poweroutlettemplate',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='powerport',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='powerporttemplate',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
