# Generated by Django 2.2.8 on 2020-01-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0088_powerfeed_available_power'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name', 'pk'), 'permissions': (('napalm_read', 'Read-only access to devices via NAPALM'), ('napalm_write', 'Read/write access to devices via NAPALM'))},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ('site', 'group', 'name', 'pk')},
        ),
    ]
