# Generated by Django 3.0.7 on 2020-06-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0106_role_default_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='label',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='interfacetemplate',
            name='label',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
