# Generated by Django 3.1 on 2020-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0114_update_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='powerfeed',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rack',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
