# Generated by Django 3.1 on 2020-10-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0120_cablepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consoleport',
            name='connected_endpoint',
        ),
        migrations.RemoveField(
            model_name='consoleport',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='consoleserverport',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='_connected_circuittermination',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='_connected_interface',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='powerfeed',
            name='connected_endpoint',
        ),
        migrations.RemoveField(
            model_name='powerfeed',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='poweroutlet',
            name='connection_status',
        ),
        migrations.RemoveField(
            model_name='powerport',
            name='_connected_powerfeed',
        ),
        migrations.RemoveField(
            model_name='powerport',
            name='_connected_poweroutlet',
        ),
        migrations.RemoveField(
            model_name='powerport',
            name='connection_status',
        ),
    ]
