# Generated by Django 3.1.3 on 2021-01-11 20:29

from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0057_status_field'),
        ('dcim', '0124_device_status_db'),
    ]

    operations = [
        # Remove: Device.status (old)
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        # Rename: Device.status_db -> Device.status
        migrations.RenameField(
            model_name='device',
            old_name='status_db',
            new_name='status',
        ),
    ]
