# Generated by Django 3.1.3 on 2021-02-05 22:04

from django.db import migrations
import django.db.models.deletion
import extras.models.statuses


def populate_site_status_db(apps, schema_editor):
    """
    Iterate existing Sites and populate `status_db` from `status` field.
    """
    Status = apps.get_model('extras.status')
    Site = apps.get_model('dcim.Site')
    ContentType = apps.get_model('contenttypes.contenttype')

    content_type = ContentType.objects.get_for_model(Site)
    custom_statuses = Status.objects.filter(content_types=content_type)

    for site in Site.objects.all():
        site.status_db = custom_statuses.get(slug=site.status)
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0057_status_field'),
        ('dcim', '0125_device_status_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status_db',
            field=extras.models.statuses.StatusField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dcim_site_related', to='extras.status'),
        ),
        migrations.RunPython(
            populate_site_status_db,
            migrations.RunPython.noop,
            hints={'model_name': 'site'},
        ),
    ]
