# Generated by Django 3.1.3 on 2021-02-17 21:29

import dcim.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0134_powerfeed_status_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='mac_address',
            field=dcim.fields.MACAddressCharField(blank=True, null=True),
        ),
    ]
