# Do not use this configuration in production.
# It is for demonstration purposes only.
# metrics_generator_enabled: true
# search_enabled: true

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

metrics_generator:
  ring:
    kvstore: {}
  processor:
    service_graphs: {}
    span_metrics: {}
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://mimir:9009/api/v1/push
        send_exemplars: true

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

overrides:
  metrics_generator_processors: ["service-graphs", "span-metrics"]
