# Generated by Django 3.0.3 on 2020-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_nested_tenantgroups_rebuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgroup',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
