# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
