# Generated by Django 2.1.7 on 2019-03-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0016_exporttemplate_add_cable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttemplate',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
