# Generated by Django 2.1.4 on 2019-02-20 07:38

from django.db import migrations, models
import utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0019_delete_taggit_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=utilities.fields.ColorField(max_length=6, default='9e9e9e'),
        ),
        migrations.AddField(
            model_name='tag',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
