# Generated by Django 2.2 on 2019-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0024_scripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectchange',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
