# Generated by Django 2.2 on 2019-08-09 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0027_webhook_additional_headers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopologyMap',
        ),
    ]
