# Generated by Django 3.0.7 on 2020-06-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0042_customfield_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        )
    ]
