# Generated by Django 3.1.3 on 2021-02-05 11:25

from django.db import migrations, models
import django.db.models.deletion
import extras.models.relationships
import extras.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0056_add_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(default='many-to-many', max_length=50)),
                ('source_label', models.CharField(blank=True, max_length=50)),
                ('source_hidden', models.BooleanField(default=False)),
                ('source_filter', models.JSONField(blank=True, null=True)),
                ('destination_label', models.CharField(blank=True, max_length=50)),
                ('destination_hidden', models.BooleanField(default=False)),
                ('destination_filter', models.JSONField(blank=True, null=True)),
                ('destination_type', models.ForeignKey(limit_choices_to=extras.utils.FeatureQuery('relationships'), on_delete=django.db.models.deletion.CASCADE, related_name='destination_relationships', to='contenttypes.contenttype')),
                ('source_type', models.ForeignKey(limit_choices_to=extras.utils.FeatureQuery('relationships'), on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', extras.models.relationships.RelationshipManager()),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('source_id', models.PositiveIntegerField()),
                ('destination_id', models.PositiveIntegerField()),
                ('destination_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='extras.relationship')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('relationship', 'source_type', 'source_id', 'destination_type', 'destination_id')},
            },
        ),
    ]
