# Generated by Django 3.1.3 on 2021-02-17 04:25

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0060_customlink_url_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
