# Generated by Django 3.1.13 on 2021-11-02 13:53

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dummy_plugin", "0002_anotherdummymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotherdummymodel",
            name="_custom_field_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
