# Generated by Django 3.1.13 on 2021-07-31 19:56

from django.db import migrations, models
import django.db.models.deletion
import dummy_plugin.models
import nautobot.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dummy_plugin", "0002_anotherdummymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoSlugModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("slug", nautobot.core.fields.AutoSlugField(max_length=10, populate_from="title")),
            ],
        ),
        migrations.CreateModel(
            name="CustomAutoSlugModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    nautobot.core.fields.AutoSlugField(
                        populate_from="title", slugify=dummy_plugin.models.custom_slugify
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UniqueAutoSlugModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", nautobot.core.fields.AutoSlugField(populate_from="title", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UniqueForAutoSlugModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    nautobot.core.fields.AutoSlugField(
                        populate_from="title",
                        unique_for_date="unique_date",
                        unique_for_month="unique_month",
                        unique_for_year="unique_year",
                    ),
                ),
                ("unique_date", models.DateField()),
                ("unique_month", models.DateField()),
                ("unique_year", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="UniqueForDateTimeAutoSlugModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", nautobot.core.fields.AutoSlugField(populate_from="title", unique_for_date="pub_datetime")),
                ("pub_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UniqueTogetherAutoSlugModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", nautobot.core.fields.AutoSlugField(populate_from="title")),
                ("field_1", models.CharField(max_length=10)),
                ("field_2", models.CharField(max_length=10)),
                ("field_3", models.CharField(max_length=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("slug", "field_2", "field_3"), ("slug", "field_1"), ("created", "field_1")},
            },
        ),
        migrations.CreateModel(
            name="Child1Model",
            fields=[
                (
                    "uniqueautoslugmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dummy_plugin.uniqueautoslugmodel",
                    ),
                ),
            ],
            bases=("dummy_plugin.uniqueautoslugmodel",),
        ),
        migrations.CreateModel(
            name="Child2Model",
            fields=[
                (
                    "uniqueautoslugmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dummy_plugin.uniqueautoslugmodel",
                    ),
                ),
            ],
            bases=("dummy_plugin.uniqueautoslugmodel",),
        ),
        migrations.CreateModel(
            name="ChildUniqueTogetherAutoSlugModel",
            fields=[
                (
                    "uniquetogetherautoslugmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dummy_plugin.uniquetogetherautoslugmodel",
                    ),
                ),
            ],
            bases=("dummy_plugin.uniquetogetherautoslugmodel",),
        ),
        migrations.CreateModel(
            name="MixedUniqueAutoSlugModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", nautobot.core.fields.AutoSlugField(populate_from="title", unique_for_date="unique_date")),
                ("unique_date", models.DateField()),
                ("field_1", models.CharField(max_length=10)),
            ],
            options={
                "unique_together": {("slug", "field_1")},
            },
        ),
    ]
