# Generated by Django 3.0.5 on 2020-04-21 20:13

from django.db import migrations
import nautobot.utilities.query_functions


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0104_correct_infiniband_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interface',
            options={'ordering': ('device', nautobot.utilities.query_functions.CollateAsChar('_name'))},
        ),
    ]
