# Generated by Django 3.1b1 on 2020-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0112_standardize_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consoleport',
            name='connection_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consoleserverport',
            name='connection_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='connection_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerfeed',
            name='connection_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poweroutlet',
            name='connection_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerport',
            name='connection_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
