# Generated by Django 3.1 on 2020-08-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0114_update_jsonfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rackreservation',
            options={'ordering': ['created', 'pk']},
        ),
    ]
