from django.conf import settings

DATE_FORMAT = settings.DATE_FORMAT
DATETIME_FORMAT = settings.DATETIME_FORMAT
SHORT_DATE_FORMAT = settings.SHORT_DATE_FORMAT
SHORT_DATETIME_FORMAT = settings.SHORT_DATETIME_FORMAT
TIME_FORMAT = settings.TIME_FORMAT
