from nautobot.core.apps import NavMenuAddButton, NavMenuGroup, NavMenuItem, NavMenuImportButton, NavMenuTab


menu_tabs = (
    NavMenuTab(
        name="Organization",
        weight=100,
        groups=(
            NavMenuGroup(
                name="Sites",
                weight=100,
                items=(
                    NavMenuItem(
                        link="dcim:site_list",
                        link_text="Sites",
                        weight=100,
                        permissions=[
                            "dcim.view_site",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:site_add",
                                permissions=[
                                    "dcim.add_site",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:site_import",
                                permissions=[
                                    "dcim.add_site",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:region_list",
                        link_text="Regions",
                        weight=200,
                        permissions=[
                            "dcim.view_region",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:region_add",
                                permissions=[
                                    "dcim.add_region",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:region_import",
                                permissions=[
                                    "dcim.add_region",
                                ],
                            ),
                        ),
                    ),
                ),
            ),
            NavMenuGroup(
                name="Racks",
                weight=200,
                items=(
                    NavMenuItem(
                        link="dcim:rack_list",
                        link_text="Racks",
                        weight=100,
                        permissions=[
                            "dcim.view_rack",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:rack_add",
                                permissions=[
                                    "dcim.add_rack",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:rack_import",
                                permissions=[
                                    "dcim.add_rack",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:rackgroup_list",
                        link_text="Rack Groups",
                        weight=200,
                        permissions=[
                            "dcim.view_rackgroup",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:rackgroup_add",
                                permissions=[
                                    "dcim.add_rackgroup",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:rackgroup_import",
                                permissions=[
                                    "dcim.add_rackgroup",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:rackrole_list",
                        link_text="Rack Roles",
                        weight=300,
                        permissions=[
                            "dcim.view_rackrole",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:rackrole_add",
                                permissions=[
                                    "dcim.add_rackrole",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:rackrole_import",
                                permissions=[
                                    "dcim.add_rackrole",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:rackreservation_list",
                        link_text="Reservations",
                        weight=400,
                        permissions=[
                            "dcim.view_rackreservation",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:rackreservation_add",
                                permissions=[
                                    "dcim.add_rackreservation",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:rackreservation_import",
                                permissions=[
                                    "dcim.add_rackreservation",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:rack_elevation_list",
                        link_text="Elevations",
                        weight=500,
                        permissions=[
                            "dcim.view_rack",
                        ],
                        buttons=(),
                    ),
                ),
            ),
        ),
    ),
    NavMenuTab(
        name="Devices",
        weight=200,
        groups=(
            NavMenuGroup(
                name="Devices",
                weight=100,
                items=(
                    NavMenuItem(
                        link="dcim:device_list",
                        link_text="Devices",
                        weight=100,
                        permissions=[
                            "dcim.view_device",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:device_add",
                                permissions=[
                                    "dcim.add_device",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:device_import",
                                permissions=[
                                    "dcim.add_device",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:devicerole_list",
                        link_text="Device Roles",
                        weight=200,
                        permissions=[
                            "dcim.view_devicerole",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:devicerole_add",
                                permissions=[
                                    "dcim.add_devicerole",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:devicerole_import",
                                permissions=[
                                    "dcim.add_devicerole",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:platform_list",
                        link_text="Platforms",
                        weight=300,
                        permissions=[
                            "dcim.view_platform",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:platform_add",
                                permissions=[
                                    "dcim.add_platform",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:platform_import",
                                permissions=[
                                    "dcim.add_platform",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:virtualchassis_list",
                        link_text="Virtual Chassis",
                        weight=400,
                        permissions=[
                            "dcim.view_virtualchassis",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:virtualchassis_add",
                                permissions=[
                                    "dcim.add_virtualchassis",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:virtualchassis_import",
                                permissions=[
                                    "dcim.add_virtualchassis",
                                ],
                            ),
                        ),
                    ),
                ),
            ),
            NavMenuGroup(
                name="Device Types",
                weight=200,
                items=(
                    NavMenuItem(
                        link="dcim:devicetype_list",
                        link_text="Device Types",
                        weight=100,
                        permissions=[
                            "dcim.view_devicetype",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:devicetype_add",
                                permissions=[
                                    "dcim.add_devicetype",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:devicetype_import",
                                permissions=[
                                    "dcim.add_devicetype",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:manufacturer_list",
                        link_text="Manufacturers",
                        weight=200,
                        permissions=[
                            "dcim.view_manufacturer",
                        ],
                        buttons=(
                            NavMenuAddButton(
                                link="dcim:manufacturer_add",
                                permissions=[
                                    "dcim.add_manufacturer",
                                ],
                            ),
                            NavMenuImportButton(
                                link="dcim:manufacturer_import",
                                permissions=[
                                    "dcim.add_manufacturer",
                                ],
                            ),
                        ),
                    ),
                ),
            ),
            NavMenuGroup(
                name="Connections",
                weight=300,
                items=(
                    NavMenuItem(
                        link="dcim:cable_list",
                        link_text="Cables",
                        weight=100,
                        permissions=[
                            "dcim.view_cable",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:cable_import",
                                permissions=[
                                    "dcim.add_cables",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:console_connections_list",
                        link_text="Console Connections",
                        weight=200,
                        permissions=[
                            "dcim.view_consoleport",
                            "dcim.view_consoleserverport",
                        ],
                        buttons=(),
                    ),
                    NavMenuItem(
                        link="dcim:power_connections_list",
                        link_text="Power Connections",
                        weight=300,
                        permissions=[
                            "dcim.view_powerport",
                            "dcim.view_poweroutlet",
                        ],
                        buttons=(),
                    ),
                    NavMenuItem(
                        link="dcim:interface_connections_list",
                        link_text="Interface Connections",
                        weight=400,
                        permissions=[
                            "dcim.view_interface",
                        ],
                        buttons=(),
                    ),
                ),
            ),
            NavMenuGroup(
                name="Device Components",
                weight=400,
                items=(
                    NavMenuItem(
                        link="dcim:interface_list",
                        link_text="Interfaces",
                        weight=100,
                        permissions=[
                            "dcim.view_interface",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:interface_import",
                                permissions=[
                                    "dcim.add_interface",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:frontport_list",
                        link_text="Front Ports",
                        weight=200,
                        permissions=[
                            "dcim.view_frontport",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:frontport_import",
                                permissions=[
                                    "dcim.add_frontport",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:rearport_list",
                        link_text="Rear Ports",
                        weight=300,
                        permissions=[
                            "dcim.view_rearport",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:rearport_import",
                                permissions=[
                                    "dcim.add_rearport",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:consoleport_list",
                        link_text="Console Ports",
                        weight=400,
                        permissions=[
                            "dcim.view_consoleport",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:consoleport_import",
                                permissions=[
                                    "dcim.add_consoleport",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:consoleserverport_list",
                        link_text="Console Server Ports",
                        weight=500,
                        permissions=[
                            "dcim.view_consoleserverport",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:consoleserverport_import",
                                permissions=[
                                    "dcim.add_consoleserverport",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:powerport_list",
                        link_text="Power Ports",
                        weight=600,
                        permissions=[
                            "dcim.view_powerport",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:powerport_import",
                                permissions=[
                                    "dcim.add_powerport",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:poweroutlet_list",
                        link_text="Power Outlets",
                        weight=700,
                        permissions=[
                            "dcim.view_poweroutlet",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:poweroutlet_import",
                                permissions=[
                                    "dcim.add_poweroutlet",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:devicebay_list",
                        link_text="Device Bays",
                        weight=800,
                        permissions=[
                            "dcim.view_devicebay",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:devicebay_import",
                                permissions=[
                                    "dcim.add_devicebay",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:inventoryitem_list",
                        link_text="Inventory Items",
                        weight=900,
                        permissions=[
                            "dcim.view_inventoryitem",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:inventoryitem_import",
                                permissions=[
                                    "dcim.add_inventoryitem",
                                ],
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    NavMenuTab(
        name="Power",
        weight=600,
        groups=(
            NavMenuGroup(
                name="Power",
                weight=100,
                items=(
                    NavMenuItem(
                        link="dcim:powerfeed_list",
                        link_text="Power Feeds",
                        permissions=[
                            "dcim.view_powerfeed",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:powerfeed_add",
                                permissions=[
                                    "dcim.add_powerfeed",
                                ],
                            ),
                            NavMenuAddButton(
                                link="dcim:powerfeed_import",
                                permissions=[
                                    "dcim.add_powerfeed",
                                ],
                            ),
                        ),
                    ),
                    NavMenuItem(
                        link="dcim:powerpanel_list",
                        link_text="Power Panels",
                        permissions=[
                            "dcim.view_powerpanel",
                        ],
                        buttons=(
                            NavMenuImportButton(
                                link="dcim:powerpanel_add",
                                permissions=[
                                    "dcim.add_powerpanel",
                                ],
                            ),
                            NavMenuAddButton(
                                link="dcim:powerpanel_import",
                                permissions=[
                                    "dcim.add_powerpanel",
                                ],
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)
