# Generated by Django 3.1.3 on 2020-12-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dummy_plugin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnotherDummyModel",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("number", models.IntegerField(default=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
