# Generated by Django 3.2.18 on 2023-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example_app", "0005_created_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anotherexamplemodel",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="examplemodel",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
