# Generated by Django 5.2.15 on 2026-06-27 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("example_app", "0007_update_all_charfields_max_length_to_255"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyExampleModel",
            fields=[],
            options={
                "verbose_name": "Proxy Example",
                "verbose_name_plural": "Proxy Examples",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("example_app.examplemodel",),
        ),
    ]
