# Generated by Django 3.0.3 on 2020-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0039_update_features_content_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcontext',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
