# Generated by Django 3.1rc1 on 2020-07-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0046_update_jsonfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
