# Generated by Django 3.1 on 2020-08-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0047_tag_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttemplate',
            name='template_language',
        ),
    ]
