# Generated by Django 3.1 on 2020-08-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0048_exporttemplate_remove_template_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graph',
        ),
    ]
