# Generated by Django 3.1.3 on 2021-02-19 00:19

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0061_status_custom_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
