"""Constants for Nautobot UI Framework."""

LAYOUT_2_OVER_1 = "2_over_1"
LAYOUT_DEFAULT = LAYOUT_2_OVER_1

LAYOUT_OPTIONS = [LAYOUT_2_OVER_1]

SECTION_LEFT_HALF = "left_half"
SECTION_RIGHT_HALF = "right_half"
SECTION_FULL_WIDTH = "full_width"

SECTION_OPTIONS = [SECTION_LEFT_HALF, SECTION_RIGHT_HALF, SECTION_FULL_WIDTH]
