# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tenancy', '0002_tenant_group_optional'), ('tenancy', '0003_unicode_literals')]

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenancy.TenantGroup'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.CharField(blank=True, help_text='Long-form name (optional)', max_length=100),
        ),
    ]
