# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.CharField(blank=True, help_text=b'Long-form name (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
