# Generated by Django 3.1.7 on 2021-03-29 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0003_populate_default_status_records"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customfield",
            name="choices",
        ),
        migrations.CreateModel(
            name="CustomFieldChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                (
                    "field",
                    models.ForeignKey(
                        limit_choices_to={"type": "select"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="extras.customfield",
                    ),
                ),
            ],
            options={
                "ordering": ["field", "weight", "value"],
                "unique_together": {("field", "value")},
            },
        ),
    ]
