# Generated by Django 3.1.7 on 2021-04-01 06:48

from django.db import migrations

import nautobot.extras.management


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0003_initial_part_3"),
    ]

    operations = [
        migrations.RunPython(
            nautobot.extras.management.populate_status_choices,
            migrations.RunPython.noop,
        ),
    ]
