import uuid

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import nautobot.extras.management
import nautobot.extras.utils

# From 0004_populate_default_status_records
# Generated by Django 3.1.7 on 2021-04-01 06:48


def populate_status_choices(apps, schema_editor):
    """Create/link default Status records for all of the Nautobot 1.0 models that support Statuses."""
    nautobot.extras.management.populate_status_choices(
        apps,
        schema_editor,
        models=[
            "circuits.Circuit",
            "dcim.Cable",
            "dcim.Device",
            "dcim.PowerFeed",
            "dcim.Rack",
            "ipam.IPAddress",
            "ipam.Prefix",
            "ipam.VLAN",
            "virtualization.VirtualMachine",
        ],
    )


# From 0005_configcontext_device_types
# Generated by Django 3.1.8 on 2021-05-13 14:13

# From 0006_graphqlquery
# Generated by Django 3.1.8 on 2021-05-26 15:59

# From 0007_configcontextschema
# Generated by Django 3.1.12 on 2021-06-16 02:40


class Migration(migrations.Migration):
    replaces = [
        ("extras", "0004_populate_default_status_records"),
        ("extras", "0005_configcontext_device_types"),
        ("extras", "0006_graphqlquery"),
        ("extras", "0007_configcontextschema"),
    ]

    dependencies = [
        ("circuits", "0002_initial_part_2"),
        ("dcim", "0004_initial_part_4"),
        ("extras", "0003_initial_part_3"),
        ("ipam", "0002_initial_part_2"),
        ("tenancy", "0001_initial"),
        ("virtualization", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_status_choices, migrations.RunPython.noop),
        migrations.AddField(
            model_name="configcontext",
            name="device_types",
            field=models.ManyToManyField(
                blank=True, related_name="_configcontext_device_types_+", to="dcim.DeviceType"
            ),
        ),
        migrations.CreateModel(
            name="GraphQLQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("query", models.TextField()),
                (
                    "variables",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
            ],
            options={
                "verbose_name": "GraphQL query",
                "verbose_name_plural": "GraphQL queries",
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="ConfigContextSchema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.CharField(max_length=200, blank=True)),
                ("slug", models.SlugField()),
                ("data_schema", models.JSONField()),
                ("owner_object_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "owner_content_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        limit_choices_to=nautobot.extras.utils.FeatureQuery("config_context_owners"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="configcontext",
            name="schema",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.configcontextschema"
            ),
        ),
    ]
