# Generated by Django 3.1.8 on 2021-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0004_initial_part_4"),
        ("extras", "0004_populate_default_status_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="configcontext",
            name="types",
            field=models.ManyToManyField(blank=True, related_name="_configcontext_types_+", to="dcim.DeviceType"),
        ),
    ]
