# Generated by Django 3.1.8 on 2021-08-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0004_populate_default_status_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshipassociation",
            name="created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="relationshipassociation",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
