# Generated by Django 3.1.12 on 2021-06-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0005_configcontext_device_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfield",
            name="validation_maximum",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="validation_minimum",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
