# Generated by Django 3.2.4 on 2021-06-14 05:24

from django.db import migrations, models
import nautobot.core.celery
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0005_configcontext_device_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("task", models.CharField(max_length=200)),
                ("job_class", models.CharField(max_length=255)),
                ("interval", models.CharField(max_length=255)),
                (
                    "args",
                    models.JSONField(blank=True, default=list, encoder=nautobot.core.celery.NautobotKombuJSONEncoder),
                ),
                (
                    "kwargs",
                    models.JSONField(blank=True, default=dict, encoder=nautobot.core.celery.NautobotKombuJSONEncoder),
                ),
                ("queue", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("one_off", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField()),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("total_run_count", models.PositiveIntegerField(default=0, editable=False)),
                ("date_changed", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduledJobs",
            fields=[
                ("ident", models.SmallIntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ("last_update", models.DateTimeField()),
            ],
        ),
    ]
