# Generated by Django 3.1.8 on 2021-05-26 15:59

import django.core.serializers.json
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0005_configcontext_device_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphQLQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("query", models.TextField()),
                (
                    "variables",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
            ],
            options={
                "verbose_name": "GraphQL query",
                "verbose_name_plural": "GraphQL queries",
                "ordering": ("slug",),
            },
        ),
    ]
