# Generated by Django 3.1.12 on 2021-07-01 13:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0007_configcontextschema"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="_custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
