# Generated by Django 3.1.13 on 2021-08-03 04:22

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0011_fileattachment_fileproxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computedfield",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="label", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="configcontextschema",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from="name"),
        ),
        migrations.AlterField(
            model_name="gitrepository",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="graphqlquery",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
