# Generated by Django 3.1.13 on 2021-08-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0011_fileattachment_fileproxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheckTestModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "health_check_db_testmodel",
            },
        ),
    ]
