# Generated by Django 3.1.14 on 2021-12-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0018_joblog_data_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="joblogentry",
            options={"get_latest_by": "created", "ordering": ["created"], "verbose_name_plural": "job log entries"},
        ),
        migrations.AlterField(
            model_name="joblogentry",
            name="job_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="extras.jobresult"
            ),
        ),
    ]
