# Generated by Django 3.1.14 on 2022-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0021_customfield_changelog_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfield",
            name="advanced_ui",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customfield",
            name="advanced_ui",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="relationship",
            name="advanced_ui",
            field=models.BooleanField(default=False),
        ),
    ]
