# Generated by Django 3.1.14 on 2022-02-14 14:23

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0021_customfield_changelog_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("source", models.CharField(max_length=32)),
                ("module_name", models.CharField(max_length=255)),
                ("job_class_name", models.CharField(max_length=100)),
                ("grouping", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("installed", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=False)),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["grouping", "name"],
                "managed": True,
                "unique_together": {("grouping", "name"), ("source", "module_name", "job_class_name")},
            },
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.AddField(
            model_name="jobresult",
            name="job_model",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.jobmodel"
            ),
        ),
    ]
