# Generated by Django 3.1.14 on 2022-02-18 17:25

from django.db import migrations, models
import nautobot.core.celery


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0021_customfield_changelog_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectchange",
            name="object_data_v2",
            field=models.JSONField(
                blank=True,
                editable=False,
                # The default DjangoJSONEncoder doesn't handle conversion of `set` objects to JSON
                encoder=nautobot.core.celery.NautobotKombuJSONEncoder,
                null=True,
            ),
        ),
    ]
