# Generated by Django 3.1.14 on 2022-02-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0023_jobresult_data_migration"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobModel",
            new_name="Job",
        ),
    ]
