# Generated by Django 3.1.14 on 2022-03-18 10:51

from django.db import migrations
import nautobot.extras.models.tags


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0030_tag_content_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitrepository',
            name='tags',
            field=nautobot.extras.models.tags.TaggableManagerField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=nautobot.extras.models.tags.TaggableManagerField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='tags',
            field=nautobot.extras.models.tags.TaggableManagerField(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
