# Generated by Django 3.1.14 on 2022-03-19 23:21

from django.db import migrations
import nautobot.extras.utils


def populate_existing_tags(app, schema):
    Tag = app.get_model("extras", "Tag")
    content_types = nautobot.extras.utils.ModelSubclassesQuery(
        "nautobot.core.models.generics.PrimaryModel"
    ).get_choices()

    for tag in Tag.objects.filter(content_types__isnull=True):
        for _, id in content_types:
            tag.content_types.add(id)


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0031_tag_content_types"),
    ]

    operations = [
        migrations.RunPython(populate_existing_tags),
    ]
