# Generated by Django 3.2.12 on 2022-04-05 02:26

from django.db import migrations, models
import nautobot.extras.utils


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0032_tag_content_types_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="content_types",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=nautobot.extras.utils.TaggableClassesQuery(),
                related_name="tags",
                to="contenttypes.ContentType",
            ),
        ),
    ]
