from django.db import migrations, models


# From 0034_alter_fileattachment_mimetype
# Generated by Django 3.2.13 on 2022-06-23 15:59

# From 0035_scheduledjob_crontab
# Generated by Django 3.2.14 on 2022-07-25 16:00

# From 0036_job_add_has_sensitive_variables
# Generated by Django 3.2.13 on 2022-07-31 14:57

# From 0037_configcontextschema__remove_name_unique__create_constraint_unique_name_owner
# Generated by Django 3.2.13 on 2022-06-01 14:16


class Migration(migrations.Migration):

    replaces = [
        ("extras", "0034_alter_fileattachment_mimetype"),
        ("extras", "0035_scheduledjob_crontab"),
        ("extras", "0036_job_add_has_sensitive_variables"),
        ("extras", "0037_configcontextschema__remove_name_unique__create_constraint_unique_name_owner"),
    ]

    dependencies = [
        ("extras", "0033_add__optimized_indexing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileattachment",
            name="mimetype",
            field=models.CharField(max_length=255),
        ),

        migrations.AddField(
            model_name="scheduledjob",
            name="crontab",
            field=models.CharField(blank=True, max_length=255),
        ),

        migrations.AddField(
            model_name="job",
            name="has_sensitive_variables",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="has_sensitive_variables_override",
            field=models.BooleanField(default=False),
        ),

        migrations.AlterField(
            model_name="configcontextschema",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name="configcontextschema",
            constraint=models.UniqueConstraint(
                fields=("name", "owner_content_type", "owner_object_id"), name="unique_name_owner"
            ),
        ),
    ]
