# Generated by Django 3.2.13 on 2022-06-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0013_locations"),
        ("extras", "0033_add__optimized_indexing"),
    ]

    operations = [
        migrations.AddField(
            model_name="configcontext",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="_extras_configcontext_locations_+", to="dcim.Location"
            ),
        ),
    ]
