# Generated by Django 3.2.13 on 2022-05-12 19:04

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.fields
import nautobot.extras.models.groups
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0033_add__optimized_indexing'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicGroupFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='name', unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('filter', models.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['content_type', 'name'],
            },
            bases=(nautobot.extras.models.groups.DynamicGroupFilteringMixin, models.Model, nautobot.extras.models.mixins.DynamicGroupMixin),
        ),
        migrations.CreateModel(
            name='DynamicGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(default='include', max_length=10)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.dynamicgroupfilter')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.dynamicgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dynamicgroup',
            name='filters',
            field=models.ManyToManyField(related_name='dynamic_groups', through='extras.DynamicGroupMembership', to='extras.DynamicGroupFilter'),
        ),
    ]
