# Generated by Django 3.2.13 on 2022-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0033_add__optimized_indexing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileattachment",
            name="mimetype",
            field=models.CharField(max_length=255),
        ),
    ]
