# Generated by Django 3.2.13 on 2022-07-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0033_add__optimized_indexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='atomic',
            field=models.BooleanField(default=True),
        ),
    ]
