# Generated by Django 3.2.13 on 2022-05-17 23:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0033_add__optimized_indexing'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('operator', models.CharField(max_length=12)),
                ('weight', models.PositiveSmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='extras.dynamicgroup')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_group_memberships', to='extras.dynamicgroup')),
            ],
            options={
                'ordering': ['parent_group', 'weight', 'group'],
            },
        ),
        migrations.AddField(
            model_name='dynamicgroup',
            name='groups',
            field=models.ManyToManyField(related_name='dynamic_groups', through='extras.DynamicGroupMembership', to='extras.DynamicGroup'),
        ),
        migrations.AddConstraint(
            model_name='dynamicgroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'parent_group'), name='group_to_filter_uniq'),
        ),
    ]
