# Generated by Django 3.2.13 on 2022-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0034_add_dynamicgroupfilter"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dynamicgroupmembership",
            name="group_to_filter_uniq",
        ),
        migrations.AddConstraint(
            model_name="dynamicgroupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "parent_group", "operator", "weight"), name="group_to_filter_uniq"
            ),
        ),
    ]
