# Generated by Django 3.2.13 on 2022-06-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0035_modify_dynamicgroupmembership_constraints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicgroup",
            name="groups",
        ),
        migrations.AddField(
            model_name="dynamicgroup",
            name="children",
            field=models.ManyToManyField(
                related_name="parents", through="extras.DynamicGroupMembership", to="extras.DynamicGroup"
            ),
        ),
    ]
