# Generated by Django 3.2.13 on 2022-06-29 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("extras", "0035_configcontextschema__remove_name_unique__create_constraint_unique_name_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("assigned_object_id", models.UUIDField(db_index=True)),
                ("user_name", models.CharField(editable=False, max_length=150)),
                ("name", models.CharField(max_length=150)),
                (
                    "slug",
                    nautobot.core.fields.AutoSlugField(blank=True, max_length=150, populate_from="name", unique=True),
                ),
                ("note", models.TextField()),
                (
                    "assigned_object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="note",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["created"],
            },
        ),
    ]
