# Generated by Django 3.2.13 on 2022-07-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0035_scheduledjob_crontab"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="has_sensitive_variables",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="has_sensitive_variables_override",
            field=models.BooleanField(default=False),
        ),
    ]
