# Generated by Django 3.2.14 on 2022-07-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0035_scheduledjob_custom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledjob",
            name="custom",
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="crontab",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
