# Generated by Django 3.2.13 on 2022-07-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0036_configcontext_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectchange",
            name="event_source",
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
