# Generated by Django 3.2.13 on 2022-06-09 15:09

from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.groups


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0036_modify_dynamicgroup_groups__children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicgroupmembership",
            name="group",
            field=models.ForeignKey(
                limit_choices_to=nautobot.extras.models.groups.limit_dynamic_group_by_parent_content_type,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="extras.dynamicgroup",
            ),
        ),
    ]
