# Generated by Django 3.2.13 on 2022-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0038_dynamicgroup__dynamicgroupmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_job_hook_receiver",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
