from django.db import migrations, models
import django.db.models.deletion
import uuid
import nautobot.core.celery
from django.conf import settings
import nautobot.core.models.fields
import django.core.serializers.json
import nautobot.extras.models.mixins
import nautobot.extras.utils
from nautobot.core.models.fields import slugify_dashes_to_underscores
from django.db import migrations


# From 0040_dynamicgroup__dynamicgroupmembership
# Generated by Django 3.2.13 on 2022-06-09 16:24

# From 0041_jobresult_job_kwargs
# Generated by Django 3.2.13 on 2022-07-04 08:19

# From 0042_job__add_is_job_hook_receiver
# Generated by Django 3.2.14 on 2022-07-21 18:49

# From 0043_note
# Generated by Django 3.2.14 on 2022-07-25 21:50

# From 0044_add_job_hook
# Generated by Django 3.2.14 on 2022-07-29 21:39

# From 0045_add_custom_field_slug
# Generated by Django 3.2.14 on 2022-08-01 18:52

# From 0046_populate_custom_field_slug_label
# Generated by Django 3.2.14 on 2022-08-01 18:52



def populate_custom_field_slugs_labels(apps, schema_editor):
    CustomField = apps.get_model("extras", "CustomField")
    for cf in CustomField.objects.all():
        cf.slug = slugify_dashes_to_underscores(cf.name)
        cf.save()
    CustomField.objects.filter(label="").update(label=models.F("name"))


def clear_custom_field_slugs_labels(apps, schema_editor):
    CustomField = apps.get_model("extras", "CustomField")
    CustomField.objects.all().update(slug="")
    CustomField.objects.filter(label=models.F("name")).update(label="")

# From 0047_enforce_custom_field_slug
# Generated by Django 3.2.14 on 2022-08-01 18:52

# From 0048_alter_objectchange_change_context_detail
# Generated by Django 3.2.15 on 2022-10-11 03:51

# From 0049_alter_tag_slug
# Generated by Django 3.2.15 on 2022-08-18 16:56

# From 0050_customfield_grouping
# Generated by Django 3.2.15 on 2022-08-26 17:08

# From 0051_add_job_task_queues
# Generated by Django 3.2.15 on 2022-09-12 17:38


class Migration(migrations.Migration):

    replaces = [
        ("extras", "0040_dynamicgroup__dynamicgroupmembership"),
        ("extras", "0041_jobresult_job_kwargs"),
        ("extras", "0042_job__add_is_job_hook_receiver"),
        ("extras", "0043_note"),
        ("extras", "0044_add_job_hook"),
        ("extras", "0045_add_custom_field_slug"),
        ("extras", "0046_populate_custom_field_slug_label"),
        ("extras", "0047_enforce_custom_field_slug"),
        ("extras", "0048_alter_objectchange_change_context_detail"),
        ("extras", "0049_alter_tag_slug"),
        ("extras", "0050_customfield_grouping"),
        ("extras", "0051_add_job_task_queues"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("extras", "0039_objectchange__add_change_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("operator", models.CharField(max_length=12)),
                ("weight", models.PositiveSmallIntegerField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="extras.dynamicgroup",
                    ),
                ),
                (
                    "parent_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_group_memberships",
                        to="extras.dynamicgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["parent_group", "weight", "group"],
            },
        ),
        migrations.AddField(
            model_name="dynamicgroup",
            name="children",
            field=models.ManyToManyField(
                related_name="parents", through="extras.DynamicGroupMembership", to="extras.DynamicGroup"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dynamicgroupmembership",
            unique_together={("group", "parent_group", "operator", "weight")},
        ),

        migrations.AddField(
            model_name="jobresult",
            name="job_kwargs",
            field=models.JSONField(blank=True, null=True, encoder=nautobot.core.celery.NautobotKombuJSONEncoder),
        ),

        migrations.AddField(
            model_name="job",
            name="is_job_hook_receiver",
            field=models.BooleanField(default=False, editable=False),
        ),

        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("assigned_object_id", models.UUIDField(db_index=True)),
                ("user_name", models.CharField(editable=False, max_length=150)),
                (
                    "slug",
                    nautobot.core.models.fields.AutoSlugField(
                        blank=True, max_length=100, populate_from="assigned_object", unique=True
                    ),
                ),
                ("note", models.TextField()),
                (
                    "assigned_object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="note",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),

        migrations.CreateModel(
            name="JobHook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    nautobot.core.models.fields.AutoSlugField(
                        blank=True, max_length=100, populate_from="name", unique=True
                    ),
                ),
                ("type_create", models.BooleanField(default=False)),
                ("type_delete", models.BooleanField(default=False)),
                ("type_update", models.BooleanField(default=False)),
                (
                    "content_types",
                    models.ManyToManyField(
                        limit_choices_to=nautobot.extras.utils.ChangeLoggedModelsQuery,
                        related_name="job_hooks",
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        limit_choices_to={"is_job_hook_receiver": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_hook",
                        to="extras.job",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),

        migrations.AddField(
            model_name="customfield",
            name="slug",
            field=models.CharField(blank=True, max_length=50),
        ),

        migrations.RunPython(populate_custom_field_slugs_labels, reverse_code=clear_custom_field_slugs_labels),

        migrations.AlterField(
            model_name="customfield",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=False, max_length=50, populate_from="label", unique=True
            ),
        ),

        migrations.AlterField(
            model_name="objectchange",
            name="change_context_detail",
            field=models.CharField(blank=True, editable=False, max_length=400),
        ),

        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True),
        ),

        migrations.AddField(
            model_name="customfield",
            name="grouping",
            field=models.CharField(blank=True, max_length=255),
        ),

        migrations.AddField(
            model_name="job",
            name="task_queues",
            field=nautobot.core.models.fields.JSONArrayField(
                base_field=models.CharField(max_length=100, blank=True), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="task_queues_override",
            field=models.BooleanField(default=False),
        ),
    ]
