# Generated by Django 3.2.15 on 2022-08-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0048_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="grouping",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
