# Generated by Django 3.2.15 on 2022-08-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0049_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="grouping",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
