# Generated by Django 3.2.16 on 2022-10-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0050_add_job_task_queues"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="required_side",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
    ]
