# Generated by Django 3.2.16 on 2022-10-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0018_device_redundancy_group"),
        ("extras", "0051_add_job_task_queues"),
    ]

    operations = [
        migrations.AddField(
            model_name="configcontext",
            name="device_redundancy_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="_extras_configcontext_device_redundancy_groups_+",
                to="dcim.DeviceRedundancyGroup",
            ),
        ),
    ]
