import uuid

from django.db import migrations, models
import django.db.models.deletion

import nautobot.extras.models.mixins
import nautobot.extras.models.models

# From 0052_configcontext_device_redundancy_groups
# Generated by Django 3.2.16 on 2022-10-28 17:25

# From 0053_relationship_required_on
# Generated by Django 3.2.16 on 2022-11-04 20:12


# From 0054_scheduledjob_kwargs_request_user_change
def rename_scheduled_job_kwargs_request_user(apps, schema_editor):
    """
    Rename ScheduledJob.kwargs["request"]["user"] to ScheduledJob.kwargs["request"]["_user_pk"]
    to support https://github.com/nautobot/nautobot/pull/3105 and prevent an AttributeError exception
    when the scheduled job runs.
    """
    ScheduledJob = apps.get_model("extras", "ScheduledJob")
    for sj in ScheduledJob.objects.all():
        if "request" in sj.kwargs:
            sj.kwargs["request"].setdefault("_user_pk", sj.kwargs["request"].pop("user", None))
            sj.save()


def reverse_rename_scheduled_job_kwargs_request_user(apps, schema_editor):
    ScheduledJob = apps.get_model("extras", "ScheduledJob")
    for sj in ScheduledJob.objects.all():
        if "request" in sj.kwargs:
            sj.kwargs["request"].setdefault("user", sj.kwargs["request"].pop("_user_pk", None))
            sj.save()


# From 0055_configcontext_dynamic_groups
# Generated by Django 3.2.18 on 2023-03-03 18:39

# From 0056_objectchange_add_reverse_time_idx
# Generated by Django 3.2.18 on 2023-03-10 21:50

# From 0057_jobbutton
# Generated by Django 3.2.18 on 2023-03-14 18:07

# From 0058_jobresult_add_time_status_idxs
# Generated by Django 3.2.18 on 2023-05-01 18:36


class Migration(migrations.Migration):
    replaces = [
        ("extras", "0052_configcontext_device_redundancy_groups"),
        ("extras", "0053_relationship_required_on"),
        ("extras", "0054_scheduledjob_kwargs_request_user_change"),
        ("extras", "0055_configcontext_dynamic_groups"),
        ("extras", "0056_objectchange_add_reverse_time_idx"),
        ("extras", "0057_jobbutton"),
        ("extras", "0058_jobresult_add_time_status_idxs"),
    ]

    dependencies = [
        ("dcim", "0018_device_redundancy_group"),
        ("extras", "0051_add_job_task_queues"),
    ]

    operations = [
        migrations.AddField(
            model_name="configcontext",
            name="device_redundancy_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="_extras_configcontext_device_redundancy_groups_+",
                to="dcim.DeviceRedundancyGroup",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="required_on",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.RunPython(
            rename_scheduled_job_kwargs_request_user, reverse_code=reverse_rename_scheduled_job_kwargs_request_user
        ),
        migrations.AddField(
            model_name="configcontext",
            name="dynamic_groups",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=nautobot.extras.models.models.limit_dynamic_group_choices,
                related_name="_extras_configcontext_dynamic_groups_+",
                to="extras.DynamicGroup",
            ),
        ),
        migrations.AddIndex(
            model_name="objectchange",
            index=models.Index(fields=["-time"], name="extras_objectchange_rtime_idx"),
        ),
        migrations.AddField(
            model_name="job",
            name="is_job_button_receiver",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name="JobButton",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("text", models.CharField(max_length=500)),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                ("group_name", models.CharField(blank=True, max_length=50)),
                ("button_class", models.CharField(default="default", max_length=30)),
                ("confirmation", models.BooleanField(default=True)),
                ("content_types", models.ManyToManyField(related_name="job_buttons", to="contenttypes.ContentType")),
                (
                    "job",
                    models.ForeignKey(
                        limit_choices_to={"is_job_button_receiver": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extras.job",
                    ),
                ),
            ],
            options={
                "ordering": ["group_name", "weight", "name"],
            },
            bases=(models.Model, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="completed",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["-created"], name="extras_jobresult_rcreated_idx"),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["-completed"], name="extras_jr_rcompleted_idx"),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["status", "-created"], name="extras_jr_statrcreate_idx"),
        ),
        migrations.AddIndex(
            model_name="jobresult",
            index=models.Index(fields=["status", "-completed"], name="extras_jr_statrcompl_idx"),
        ),
    ]
