# Generated by Django 3.2.16 on 2022-12-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0053_relationship_required_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobresult',
            old_name='job_id',
            new_name='task_id',
        ),
    ]
