# Generated by Django 3.2.16 on 2022-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0054_jobresult__rename_job_id_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobresult',
            options={'get_latest_by': 'date_created', 'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='jobresult',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='jobresult',
            old_name='completed',
            new_name='date_done',
        ),
        migrations.RenameField(
            model_name='jobresult',
            old_name='name',
            new_name='task_name',
        ),
        migrations.AlterField(
            model_name='jobresult',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=30),
        ),
    ]
