# Generated by Django 3.2.16 on 2022-11-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0054_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
