# Generated by Django 3.2.18 on 2023-03-03 18:39

from django.db import migrations, models

import nautobot.extras.models.models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0054_scheduledjob_kwargs_request_user_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="configcontext",
            name="dynamic_groups",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=nautobot.extras.models.models.limit_dynamic_group_choices,
                related_name="_extras_configcontext_dynamic_groups_+",
                to="extras.DynamicGroup",
            ),
        ),
    ]
