# Generated by Django 3.2.18 on 2023-02-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0054_scheduledjob_kwargs_request_user_change'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='relationship',
            index_together={('destination_type', 'destination_hidden'), ('source_type', 'source_hidden')},
        ),
        migrations.AlterIndexTogether(
            name='relationshipassociation',
            index_together={('destination_id', 'source_type', 'relationship'), ('source_id', 'destination_type', 'relationship')},
        ),
    ]
