# Generated by Django 3.2.18 on 2023-03-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0055_configcontext_dynamic_groups"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="objectchange",
            index=models.Index(fields=["-time"], name="extras_objectchange_rtime_idx"),
        ),
    ]
