from collections import namedtuple
import logging
import uuid

import django.core.serializers.json
from django.db import migrations, models

from nautobot.core.choices import ColorChoices
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.utils
from nautobot.ipam.choices import IPAddressRoleChoices


# From 0059_joblogentry_scheduledjob_webhook_data_migration
def null_joblogentry_fields_to_empty(apps, schema_editor):
    """Change null absolute_url and log_object fields to empty strings instead."""
    JobLogEntry = apps.get_model("extras.joblogentry")
    JobLogEntry.objects.filter(log_object__isnull=True).update(log_object="")
    JobLogEntry.objects.filter(absolute_url__isnull=True).update(absolute_url="")


def null_scheduledjob_fields_to_empty(apps, schema_editor):
    """Change null queue field to empty string instead."""
    ScheduledJob = apps.get_model("extras.scheduledjob")
    ScheduledJob.objects.filter(queue__isnull=True).update(queue="")


def null_webhook_fields_to_empty(apps, schema_editor):
    """Change null ca_file_path field to empty string instead."""
    WebHook = apps.get_model("extras.webhook")
    WebHook.objects.filter(ca_file_path__isnull=True).update(ca_file_path="")


# From 0060_alter_joblogentry_scheduledjob_webhook_fields
# Generated by Django 3.2.16 on 2022-12-22 19:10

# From 0061_role_and_alter_status
# Generated by Django 3.2.16 on 2022-11-19 23:15

# From 0062_collect_roles_from_related_apps_roles
# Generated by Django 3.2.16 on 2022-11-19 23:15


# Role Models that would be integrated into this Role model are referred to as RelatedRoleModels.
# For Example: DeviceRole, RackRole e.t.c.
# while implemented_by refers to the model that actually implements the Related Model.
# e.g role = models.ForeignKey(to=DeviceRole, ...)
RelatedRoleModel = namedtuple("RelatedRoleModel", ["model", "implemented_by"])

# Using this, Choices is made to resemble a Role Queryset.
ChoicesQuerySet = namedtuple("ChoicesQuerySet", ["name", "slug", "description", "color"])

color_map = {
    "default": ColorChoices.COLOR_GREY,
    "primary": ColorChoices.COLOR_BLUE,
    "warning": ColorChoices.COLOR_AMBER,
    "success": ColorChoices.COLOR_GREEN,
}

logger = logging.getLogger(__name__)


def create_equivalent_roles_of_virtualmachine_device_role(apps):
    """Create equivalent roles for the VirtualMachine DeviceRole."""
    DeviceRole = apps.get_model("dcim", "DeviceRole")
    roles_to_create = DeviceRole.objects.filter(vm_role=True)
    create_roles(apps, roles_to_create, ["virtualization.virtualmachine"])


def create_equivalent_roles_of_related_role_model(apps):
    """Create equivalent roles for the related role model."""
    related_role_models = (
        RelatedRoleModel("dcim.DeviceRole", ["dcim.device"]),
        RelatedRoleModel("dcim.RackRole", ["dcim.rack"]),
        RelatedRoleModel("ipam.Role", ["ipam.prefix", "ipam.vlan"]),
    )

    for related_role_model in related_role_models:
        app_name, model_class = related_role_model.model.split(".")
        related_role_model_class = apps.get_model(app_name, model_class)

        roles_to_create = related_role_model_class.objects.all()
        create_roles(apps, roles_to_create, related_role_model.implemented_by)


def create_equivalent_roles_of_ipaddress_role_choices(apps):
    """Create equivalent roles for the IPAddressRoleChoices."""
    roles_to_create = []

    for value, label in IPAddressRoleChoices.CHOICES:
        color = IPAddressRoleChoices.CSS_CLASSES[value]
        choiceset = ChoicesQuerySet(name=label, slug=value, color=color_map[color], description="")
        roles_to_create.append(choiceset)
    create_roles(apps, roles_to_create, ["ipam.ipaddress"])


def create_roles(apps, roles_to_create, content_types):
    """Create/retrieve Role records as needed and set their contenttypes."""
    Role = apps.get_model("extras", "Role")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ObjectChange = apps.get_model("extras", "ObjectChange")

    old_role_ct = None
    new_role_ct = None

    if hasattr(roles_to_create, "model"):
        old_role_ct = ContentType.objects.get_for_model(roles_to_create.model)
        # No sense fetching this if we don't have an old role content type
        new_role_ct = ContentType.objects.get_for_model(Role)

    for old_role in roles_to_create:
        new_role, created = Role.objects.get_or_create(
            name=old_role.name,
            defaults={
                "description": old_role.description,
                "color": getattr(old_role, "color", color_map["default"]),
                "weight": getattr(old_role, "weight", None),
            },
        )
        if created:
            logger.info(f'Created Role "{new_role.name}"')
        if old_role_ct and hasattr(old_role, "pk"):
            # Move over existing object change records to the new role we created
            updated_count = ObjectChange.objects.filter(
                changed_object_type=old_role_ct, changed_object_id=old_role.pk
            ).update(changed_object_type=new_role_ct, changed_object_id=new_role.pk)
            logger.info(
                f'Updated {updated_count} ObjectChanges from the existing "{old_role.name}" {old_role._meta.label}'
            )

    # This is for all of the change records for roles which no longer exist
    if old_role_ct:
        updated_count = ObjectChange.objects.filter(changed_object_type=old_role_ct).update(
            changed_object_type=new_role_ct
        )
        logger.info(f"Updated {updated_count} leftover ObjectChanges from deleted {old_role_ct.model} records.")

    roles = Role.objects.filter(name__in=[roles.name for roles in roles_to_create])

    # Add content_types to the roles
    filter_ct_by = models.Q()
    for app_and_model in content_types:
        app_label, model_name = app_and_model.split(".")
        filter_ct_by |= models.Q(app_label=app_label, model=model_name)

    content_types = ContentType.objects.filter(filter_ct_by)
    for role in roles:
        role.content_types.add(*[content_type.id for content_type in content_types])


def populate_roles_from_related_app_roles(apps, schema_editor):
    """Populate Role models using records from other related role models or choices from different apps."""
    create_equivalent_roles_of_related_role_model(apps)
    create_equivalent_roles_of_virtualmachine_device_role(apps)
    create_equivalent_roles_of_ipaddress_role_choices(apps)


def clear_populated_roles(apps, schema_editor):
    Role = apps.get_model("extras", "Role")
    Role.objects.all().delete()
    # TODO: currently we do NOT recreate DeviceRole/RackRole records, nor do we revert ObjectChange records.


class Migration(migrations.Migration):
    replaces = [
        ("extras", "0059_joblogentry_scheduledjob_webhook_data_migration"),
        ("extras", "0060_alter_joblogentry_scheduledjob_webhook_fields"),
        ("extras", "0061_role_and_alter_status"),
        ("extras", "0062_collect_roles_from_related_apps_roles"),
    ]

    dependencies = [
        ("extras", "0058_jobresult_add_time_status_idxs"),
    ]

    operations = [
        migrations.RunPython(null_joblogentry_fields_to_empty, migrations.RunPython.noop),
        migrations.RunPython(null_scheduledjob_fields_to_empty, migrations.RunPython.noop),
        migrations.RunPython(null_webhook_fields_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="joblogentry",
            name="absolute_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="joblogentry",
            name="log_object",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="queue",
            field=models.CharField(blank=True, db_index=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="ca_file_path",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", nautobot.core.models.fields.ColorField(default="9e9e9e", max_length=6)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("weight", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "content_types",
                    models.ManyToManyField(
                        limit_choices_to=nautobot.extras.utils.RoleModelsQuery(),
                        related_name="roles",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
            bases=(models.Model, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.RunPython(populate_roles_from_related_app_roles, clear_populated_roles),
    ]
