from django.db import migrations, models

from nautobot.extras.utils import migrate_role_data

# From 0063_alter_role_options
# Generated by Django 3.2.16 on 2022-12-29 17:18

# From 0064_alter_configcontext_and_add_new_role
# Generated by Django 3.2.16 on 2022-11-25 11:45

# From 0065_configcontext_data_migrations
# Generated by Django 3.2.16 on 2022-11-25 11:45


def migrate_data_from_legacy_roles_to_new_roles(apps, schema):
    """Migrate ConfigContext data from legacy_roles to new_roles."""
    ConfigContext = apps.get_model("extras", "ConfigContext")
    DeviceRole = apps.get_model("dcim", "DeviceRole")
    Role = apps.get_model("extras", "Role")
    migrate_role_data(
        model_to_migrate=ConfigContext,
        from_role_field_name="legacy_roles",
        from_role_model=DeviceRole,
        to_role_field_name="new_roles",
        to_role_model=Role,
        is_m2m_field=True,
    )


def reverse_role_data_migrate(apps, schema):
    """Migrate ConfigContext data from new_roles to legacy_roles."""
    ConfigContext = apps.get_model("extras", "ConfigContext")
    DeviceRole = apps.get_model("dcim", "DeviceRole")
    Role = apps.get_model("extras", "Role")
    migrate_role_data(
        model_to_migrate=ConfigContext,
        from_role_field_name="new_roles",
        from_role_model=Role,
        to_role_field_name="legacy_roles",
        to_role_model=DeviceRole,
        is_m2m_field=True,
    )


# From 0066_rename_configcontext_role
# Generated by Django 3.2.16 on 2022-11-25 11:45


class Migration(migrations.Migration):
    replaces = [
        ("extras", "0063_alter_role_options"),
        ("extras", "0064_alter_configcontext_and_add_new_role"),
        ("extras", "0065_configcontext_data_migrations"),
        ("extras", "0066_rename_configcontext_role"),
    ]

    dependencies = [
        ("extras", "0062_collect_roles_from_related_apps_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ("weight", "name")},
        ),
        migrations.RenameField(
            model_name="configcontext",
            old_name="roles",
            new_name="legacy_roles",
        ),
        migrations.AddField(
            model_name="configcontext",
            name="new_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="_extras_configcontext_roles_+",
                to="extras.Role",
            ),
        ),
        migrations.RunPython(migrate_data_from_legacy_roles_to_new_roles, reverse_role_data_migrate),
        migrations.RemoveField(
            model_name="configcontext",
            name="legacy_roles",
        ),
        migrations.RenameField(
            model_name="configcontext",
            old_name="new_roles",
            new_name="roles",
        ),
    ]
