# Generated by Django 3.2.16 on 2022-12-29 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0062_collect_roles_from_related_apps_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ("weight", "name")},
        ),
    ]
