# Generated by Django 3.2.16 on 2023-02-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0062_rename_configcontext_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configcontext",
            name="regions",
        ),
        migrations.RemoveField(
            model_name="configcontext",
            name="sites",
        ),
    ]
