# Generated by Django 3.2.16 on 2023-01-23 21:39

from django.db import migrations, models
import nautobot.core.celery


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0063_jobresult__rename_date_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobresult',
            old_name='job_kwargs',
            new_name='task_args',
        ),
        migrations.AddField(
            model_name='jobresult',
            name='content_encoding',
            field=models.CharField(default='utf-8', max_length=64),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='content_type',
            field=models.CharField(default='application/x-nautobot-json', max_length=128),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='meta',
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='periodic_task_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='result',
            field=models.TextField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='task_kwargs',
            field=models.JSONField(blank=True, encoder=nautobot.core.celery.NautobotKombuJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='task_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobresult',
            name='worker',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
