# Generated by Django 3.2.16 on 2023-02-09 16:20

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.celery
import nautobot.extras.utils


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0065_rename_configcontext_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobresult",
            options={"get_latest_by": "date_created", "ordering": ["-date_created"]},
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="created",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="completed",
            new_name="date_done",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="job_kwargs",
            new_name="task_args",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="job_id",
            new_name="task_id",
        ),
        migrations.AddField(
            model_name="jobresult",
            name="meta",
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="periodic_task_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="result",
            field=models.TextField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="task_kwargs",
            field=models.JSONField(blank=True, encoder=nautobot.core.celery.NautobotKombuJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="task_name",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="traceback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="worker",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="obj_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=nautobot.extras.utils.FeatureQuery("job_results"),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_results",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="status",
            field=models.CharField(db_index=True, default="PENDING", max_length=30),
        ),
    ]
