# Generated by Django 3.2.18 on 2023-03-14 15:45

from django.db import migrations


def move_cf_name_value_to_lable(apps, schema_editor):
    CustomField = apps.get("extras", "customfield")
    custom_fields = CustomField.objects.filter(label__isnull=True)

    for cf in custom_fields:
        cf.label = cf.name
        cf.save()


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0068_rename_model_fields"),
    ]

    operations = []
