# Generated by Django 3.2.18 on 2023-03-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0069_move_cf_name_value_to_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['weight', 'label']},
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
