# Generated by Django 3.2.18 on 2023-03-15 18:48

from django.db import migrations
import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0070_make_cf_name_field_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customfield",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customfield",
            name="slug",
        ),
        migrations.AddField(
            model_name="customfield",
            name="key",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="label", unique=True
            ),
        ),
    ]
