# Generated by Django 3.2.18 on 2023-03-23 16:03

from django.db import migrations
import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0074_remove_name_field_and_make_label_field_non_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfield",
            name="key",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="label", separator="_", unique=True
            ),
        ),
    ]
