# Generated by Django 3.2.18 on 2023-03-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0034_migrate_region_and_site_data_to_locations"),
        ("extras", "0075_remove_gitrepository_fields"),
        ("ipam", "0022_aggregate_to_prefix_data_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customfield",
            options={"ordering": ["weight", "label"]},
        ),
        migrations.RenameField(
            model_name="customfield",
            old_name="slug",
            new_name="key",
        ),
        migrations.AlterField(
            model_name="customfield",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=50,
            ),
        ),
    ]
