# Generated by Django 3.2.18 on 2023-04-03 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0077_remove_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="commit_default",
        ),
        migrations.RemoveField(
            model_name="job",
            name="commit_default_override",
        ),
        migrations.RemoveField(
            model_name="job",
            name="read_only",
        ),
        migrations.RemoveField(
            model_name="job",
            name="read_only_override",
        ),
    ]
