# Generated by Django 3.2.18 on 2023-03-17 17:29

from django.db import migrations, models
import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0077_migrate_custom_field_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customfield",
            name="name",
        ),
        migrations.AlterField(
            model_name="customfield",
            name="label",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="key",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="label", separator="_", unique=True
            ),
        ),
    ]
