# Generated by Django 3.2.18 on 2023-04-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0079_tagsfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="commit_default_override",
            new_name="dryrun_default_override",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="commit_default",
            new_name="dryrun_default",
        ),
        migrations.AlterField(
            model_name="job",
            name="dryrun_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="supports_dryrun",
            field=models.BooleanField(default=False),
        ),
    ]
