from django.db import migrations

import nautobot.core.models.fields
from nautobot.core.models.fields import slugify_dashes_to_underscores

# From 0081_rename_relationship_slug_to_key
# Generated by Django 3.2.18 on 2023-05-09 16:35

# From 0082_rename_relationship_name_to_label
# Generated by Django 3.2.18 on 2023-05-09 16:35

# From 0083_ensure_relationship_keys_are_unique
# Generated by Django 3.2.18 on 2023-05-09 16:38


def ensure_relationship_keys_are_unique(apps, schema_editor):
    Relationship = apps.get_model("extras", "relationship")

    # Make sure that relationship keys are unique by appending counters
    # and log messages if the old keys are changed.
    relationship_keys = set()
    for rel in Relationship.objects.all().order_by("created"):
        original_rel_key = rel.key
        rel_key = slugify_dashes_to_underscores(original_rel_key)
        append_counter = 2

        while rel_key in relationship_keys:
            rel_key_append = f"_{append_counter}"
            max_key_length = 50 - len(rel_key_append)
            rel_key = original_rel_key[:max_key_length] + rel_key_append
            append_counter += 1

        if rel_key != original_rel_key:
            print(
                f'  Relationship instance "{rel.label}" key attribute "{original_rel_key}" is being changed to "{rel_key}".'
            )
            rel.key = rel_key
            rel.save()
        relationship_keys.add(rel_key)


# From 0084_rename_computed_field_slug_to_key
# Generated by Django 3.2.18 on 2023-05-10 14:40


class Migration(migrations.Migration):
    replaces = [
        ("extras", "0081_rename_relationship_slug_to_key"),
        ("extras", "0082_rename_relationship_name_to_label"),
        ("extras", "0083_ensure_relationship_keys_are_unique"),
        ("extras", "0084_rename_computed_field_slug_to_key"),
    ]

    dependencies = [
        ("extras", "0080_tagsfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relationship",
            old_name="slug",
            new_name="key",
        ),
        migrations.AlterModelOptions(
            name="relationship",
            options={"ordering": ["label"]},
        ),
        migrations.RenameField(
            model_name="relationship",
            old_name="name",
            new_name="label",
        ),
        migrations.AlterField(
            model_name="relationship",
            name="key",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="label", unique=True
            ),
        ),
        migrations.RunPython(
            code=ensure_relationship_keys_are_unique,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="computedfield",
            options={"ordering": ["weight", "key"]},
        ),
        migrations.RenameField(
            model_name="computedfield",
            old_name="slug",
            new_name="key",
        ),
    ]
