# Generated by Django 3.2.18 on 2023-05-05 16:30

from django.db import migrations, models
import nautobot.core.celery


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0080_job_result__result_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="read_only_override",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="data",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="obj_type",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="periodic_task_name",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="task_id",
        ),
        migrations.AddField(
            model_name="jobresult",
            name="celery_kwargs",
            field=models.JSONField(blank=True, default=dict, encoder=nautobot.core.celery.NautobotKombuJSONEncoder),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="celery_kwargs",
            field=models.JSONField(blank=True, default=dict, encoder=nautobot.core.celery.NautobotKombuJSONEncoder),
        ),
        migrations.AlterField(
            model_name="job",
            name="read_only",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="supports_dryrun",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="task_args",
            field=models.JSONField(blank=True, default=list, encoder=nautobot.core.celery.NautobotKombuJSONEncoder),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="task_kwargs",
            field=models.JSONField(blank=True, default=dict, encoder=nautobot.core.celery.NautobotKombuJSONEncoder),
        ),
    ]
