# Generated by Django 3.2.18 on 2023-05-10 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0083_ensure_relationship_keys_are_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computedfield",
            options={"ordering": ["weight", "key"]},
        ),
        migrations.RenameField(
            model_name="computedfield",
            old_name="slug",
            new_name="key",
        ),
    ]
