from datetime import timedelta
import secrets

from django.db import migrations, models

import nautobot.core.celery
import nautobot.core.celery.encoders
from nautobot.core.utils.migrations import check_for_duplicates_with_natural_key_fields_in_migration


# From 0085_taggeditem_cleanup
def cleanup_taggeditem_duplicates(apps, schema_editor):
    TaggedItem = apps.get_model("extras", "TaggedItem")

    # Get the set of distinct values for TaggedItems
    taggeditem_values = TaggedItem.objects.values("content_type", "object_id", "tag")
    # Discard any existing ordering, just to be safe
    taggeditem_values = taggeditem_values.order_by()
    # Count the number of duplicates for each value
    taggeditem_values = taggeditem_values.annotate(count_id=models.Count("id"))

    # Filter to only those that actually have duplicates (i.e. more than one record)
    duplicate_taggeditem_values = taggeditem_values.filter(count_id__gt=1)

    deleted_count = 0
    for duplicate in duplicate_taggeditem_values:
        # Delete all but the "first" in each duplicate set.
        # We can't use models.Min("id") to deterministically pick which one to keep because id is a UUID and psycopg2
        # doesn't implement a min(uuid) function.
        # We also can't just slice the queryset before deleting it (Django doesn't allow it).
        to_delete = TaggedItem.objects.filter(
            content_type=duplicate["content_type"], object_id=duplicate["object_id"], tag=duplicate["tag"]
        )
        to_keep = to_delete.first()
        to_delete = to_delete.exclude(id=to_keep.id)

        count, _ = to_delete.delete()
        deleted_count += count

    if deleted_count:
        print(f"    Deleted {deleted_count} redundant TaggedItem records")


# From 0086_taggeditem_uniqueness
# Generated by Django 3.2.18 on 2023-05-26 14:06

# From 0087_job__celery_task_fields__dryrun_support
# Generated by Django 3.2.18 on 2023-04-13 14:50


# From 0088_job__commit_default_data_migration
def migrate_commit_default_to_dryrun_default(apps, schema_editor):
    """
    Negate the value of dryrun_default (True becomes False, False becomes True)
    """
    Job = apps.get_model("extras", "Job")
    for job_model in Job.objects.all():
        original = job_model.dryrun_default
        if isinstance(original, bool):
            job_model.dryrun_default = not original
            job_model.save()


# From 0089_joblogentry__log_level_default
# Generated by Django 3.2.18 on 2023-05-17 19:07

# From 0090_joblogentry__log_level_data_migration
LOG_LEVEL_MAPPING = {
    "default": "debug",
    "success": "info",
    "failure": "error",
}


def migrate_job_log_entry_log_levels(apps, schema_editor):
    """
    Migrate job log levels from 1.0 values to 2.0 values.
    default => debug
    success => info
    failure => error
    """
    JobLogEntry = apps.get_model("extras", "JobLogEntry")

    for old_log_level, new_log_level in LOG_LEVEL_MAPPING.items():
        JobLogEntry.objects.filter(log_level=old_log_level).update(log_level=new_log_level)


# From 0091_scheduledjob__data_migration
# Generated by Django 3.2.18 on 2023-05-30 16:10


def migrate_existing_scheduled_jobs(apps, schema_editor):
    """
    Migrate the existing ScheduledJobs to support the new format.
    1. set sj.kwargs attribute to the old sj.kwargs["data"].
    2. set sj.user to the old sj.kwargs["user"] if the user is not already set.
    3. set sj.queue and sj.celery_kwargs["queue"] to the old sj.kwargs["task_queue"].
    4. change sj.job_class from old "source/module/class_name" to "module.class_name"
    """
    ScheduledJob = apps.get_model("extras", "ScheduledJob")
    for sj in ScheduledJob.objects.all():
        old_kwargs = sj.kwargs
        sj.kwargs = old_kwargs.get("data", {})
        if sj.user is None:
            sj.user = old_kwargs.get("user")
        sj.queue = old_kwargs.get("task_queue", "")
        sj.celery_kwargs["queue"] = old_kwargs.get("task_queue", "")
        sj.job_class = ".".join(sj.job_class.split("/")[-2:])
        sj.save()


def reverse_migrate_existing_scheduled_jobs(apps, schema_editor):
    """
    Reverse the ScheduledJob Migration / Restore the removed keys in sj.kwargs.
    1. Restore the "data" key from sj.kwargs.
    2. Restore the "commit" key to False.
    3. Restore the "user" key from sj.user.
    4. Restore the "task_queue" from sj.queue.
    5. Restore the "job_class" to a semblance of its old form (will likely be broken)
    """
    ScheduledJob = apps.get_model("extras", "ScheduledJob")
    for sj in ScheduledJob.objects.all():
        sj.kwargs["data"] = sj.kwargs
        sj.kwargs["commit"] = False
        sj.kwargs["user"] = sj.user
        sj.kwargs["task_queue"] = sj.queue or sj.celery_kwargs["queue"]
        sj.job_class = "local/" + "/".join(sj.job_class.rsplit(".", 1))
        sj.save()


# From 0092_uniqueness_data_migration
def ensure_unique_scheduledjob_names(apps, schema_editor):
    ScheduledJob = apps.get_model("extras", "ScheduledJob")

    cache = set()
    for instance in ScheduledJob.objects.all():
        name = instance.name
        counter = 1
        while name in cache:
            suffix = f" {counter}"
            max_name_length = 200 - len(suffix)
            name = f"{instance.name[:max_name_length]}{suffix}"
            counter += 1

        if name != instance.name:
            print(f'    Scheduled Job instance {instance.id} is being renamed to "{name}" for uniqueness')
            instance.name = name
            instance.save()

        cache.add(name)


def check_for_duplicates(apps, schema_editor):
    ConfigContext = apps.get_model("extras", "ConfigContext")
    ConfigContextSchema = apps.get_model("extras", "ConfigContextSchema")
    ExportTemplate = apps.get_model("extras", "ExportTemplate")

    check_for_duplicates_with_natural_key_fields_in_migration(ConfigContext, ["name"])
    check_for_duplicates_with_natural_key_fields_in_migration(ConfigContextSchema, ["name"])
    check_for_duplicates_with_natural_key_fields_in_migration(ExportTemplate, ["name"])


# From 0093_uniqueness_fixup
# Generated by Django 3.2.18 on 2023-06-06 16:22

# From 0094_alter_objectchange_unique_together
# Generated by Django 3.2.18 on 2023-06-12 13:55

# From 0095_ensure_note_timestamps_are_unique
# Generated by Django 3.2.20 on 2023-07-18 14:50


def ensure_note_created_timestamps_are_unique(apps, schema_editor):
    Note = apps.get_model("extras", "Note")
    natural_key_fields = ["assigned_object_type", "assigned_object_id", "user_name", "created"]

    # We append some random milliseconds of time to avoid duplicate timestamps for Note objects' created field.

    duplicate_records = (
        Note.objects.values(*natural_key_fields).order_by().annotate(count=models.Count("pk")).filter(count__gt=1)
    )
    for duplicate_record in duplicate_records:
        duplicate_record.pop("count")
        duplicate_notes = Note.objects.filter(**duplicate_record)
        for note in duplicate_notes:
            random_milliseconds = secrets.randbelow(1000)
            note.created += timedelta(milliseconds=random_milliseconds)
            note.save()


# From 0096_remove_slugs
# Generated by Django 3.2.18 on 2023-06-12 22:19

# From 0097_alter_job_result_remove_result
# Generated by Django 3.2.20 on 2023-07-19 06:21

# From 0098_rename_data_jobresult_result
# Generated by Django 3.2.20 on 2023-07-19 06:21


class Migration(migrations.Migration):
    replaces = [
        ("extras", "0085_taggeditem_cleanup"),
        ("extras", "0086_taggeditem_uniqueness"),
        ("extras", "0087_job__celery_task_fields__dryrun_support"),
        ("extras", "0088_job__commit_default_data_migration"),
        ("extras", "0089_joblogentry__log_level_default"),
        ("extras", "0090_joblogentry__log_level_data_migration"),
        ("extras", "0091_scheduledjob__data_migration"),
        ("extras", "0092_uniqueness_data_migration"),
        ("extras", "0093_uniqueness_fixup"),
        ("extras", "0094_alter_objectchange_unique_together"),
        ("extras", "0095_ensure_note_timestamps_are_unique"),
        ("extras", "0096_remove_slugs"),
        ("extras", "0097_alter_job_result_remove_result"),
        ("extras", "0098_rename_data_jobresult_result"),
    ]

    dependencies = [
        ("extras", "0084_rename_computed_field_slug_to_key"),
    ]

    operations = [
        migrations.RunPython(cleanup_taggeditem_duplicates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="taggeditem",
            name="object_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="taggeditem",
            unique_together={("content_type", "object_id", "tag")},
        ),
        migrations.RenameField(
            model_name="job",
            old_name="commit_default_override",
            new_name="dryrun_default_override",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="commit_default",
            new_name="dryrun_default",
        ),
        migrations.AlterField(
            model_name="job",
            name="dryrun_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="supports_dryrun",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="job",
            name="read_only_override",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="obj_type",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="periodic_task_name",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="task_id",
        ),
        migrations.AddField(
            model_name="jobresult",
            name="celery_kwargs",
            field=models.JSONField(
                blank=True, default=dict, encoder=nautobot.core.celery.encoders.NautobotKombuJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="celery_kwargs",
            field=models.JSONField(
                blank=True, default=dict, encoder=nautobot.core.celery.encoders.NautobotKombuJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="read_only",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="supports_dryrun",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="task_args",
            field=models.JSONField(
                blank=True, default=list, encoder=nautobot.core.celery.encoders.NautobotKombuJSONEncoder
            ),
        ),
        migrations.RunPython(
            code=migrate_commit_default_to_dryrun_default,
            reverse_code=migrate_commit_default_to_dryrun_default,
        ),
        migrations.AlterField(
            model_name="joblogentry",
            name="log_level",
            field=models.CharField(db_index=True, default="info", max_length=32),
        ),
        migrations.RunPython(
            code=migrate_job_log_entry_log_levels,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=migrate_existing_scheduled_jobs,
            reverse_code=reverse_migrate_existing_scheduled_jobs,
        ),
        migrations.RunPython(ensure_unique_scheduledjob_names, migrations.RunPython.noop),
        migrations.RunPython(check_for_duplicates, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="configcontextschema",
            name="unique_name_owner",
        ),
        migrations.RemoveField(
            model_name="configcontextschema",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="scheduledjob",
            name="job_class",
        ),
        migrations.AlterField(
            model_name="configcontext",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="configcontextschema",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="task",
            field=models.CharField(db_index=True, max_length=201),
        ),
        migrations.AlterUniqueTogether(
            name="configcontext",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="exporttemplate",
            unique_together={("content_type", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="objectchange",
            unique_together={("time", "request_id", "changed_object_type", "changed_object_id")},
        ),
        migrations.RunPython(ensure_note_created_timestamps_are_unique, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("assigned_object_type", "assigned_object_id", "user_name", "created")},
        ),
        migrations.RemoveField(
            model_name="note",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="jobresult",
            name="result",
        ),
        migrations.AlterField(
            model_name="jobresult",
            name="data",
            field=models.JSONField(
                blank=True, editable=False, encoder=nautobot.core.celery.NautobotKombuJSONEncoder, null=True
            ),
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="data",
            new_name="result",
        ),
    ]
