# Generated by Django 3.2.18 on 2023-06-12 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0093_uniqueness_fixup"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objectchange",
            unique_together={("time", "request_id", "changed_object_type", "changed_object_id")},
        ),
    ]
