# Generated by Django 3.2.18 on 2023-06-12 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0095_ensure_note_timestamps_are_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("assigned_object_type", "assigned_object_id", "user_name", "created")},
        ),
        migrations.RemoveField(
            model_name="note",
            name="slug",
        ),
    ]
