from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.models
import uuid
import django.core.serializers.json
import django.core.validators
import nautobot.core.models.fields
import nautobot.core.models.validators
import nautobot.extras.models.mixins
import nautobot.extras.models.roles
import nautobot.extras.models.statuses


# From 0099_remove_dangling_note_objects
# Generated by Django 3.2.22 on 2023-11-06 22:56

# From 0100_fileproxy_job_result
# Generated by Django 3.2.22 on 2023-10-27 16:32

# From 0101_externalintegration
# Generated by Django 3.2.22 on 2023-11-01 21:29

# From 0102_set_null_objectchange_contenttype
# Generated by Django 3.2.23 on 2023-11-27 20:43

# From 0103_add_db_indexes_to_object_change
# Generated by Django 3.2.23 on 2024-01-03 17:50

# From 0104_contact_contactassociation_team
# Generated by Django 3.2.23 on 2024-01-04 20:35

# From 0099_remove_dangling_note_objects
def remove_dangling_note_objects(apps, schema_editor):
    """
    Remove Note objects associated with deleted objects.
    """
    Note = apps.get_model("extras", "Note")
    print("\n>>> Finding and removing any invalid or dangling Note objects ...\n")
    model_class = None
    assigned_object_type_id = None
    deleted_count = 0
    for note in Note.objects.order_by("assigned_object_type").iterator():
        # cache model_class and assigned_object_type_id
        if note.assigned_object_type_id != assigned_object_type_id:
            try:
                model_class = apps.get_model(note.assigned_object_type.app_label, note.assigned_object_type.model)
            except LookupError:
                model_class = None
            assigned_object_type_id = note.assigned_object_type_id
        if model_class is None or not model_class.objects.filter(id=note.assigned_object_id).exists():
            note.delete()
            deleted_count += 1
    if deleted_count > 0:
        print(f"\n>>> Removed {deleted_count} invalid or dangling Note objects. \n")
    print("\n>>> Removal completed. \n")


class Migration(migrations.Migration):

    replaces = [
        ("extras", "0099_remove_dangling_note_objects"),
        ("extras", "0100_fileproxy_job_result"),
        ("extras", "0101_externalintegration"),
        ("extras", "0102_set_null_objectchange_contenttype"),
        ("extras", "0103_add_db_indexes_to_object_change"),
        ("extras", "0104_contact_contactassociation_team"),
    ]

    dependencies = [
        ("extras", "0098_rename_data_jobresult_result"),
    ]

    operations = [

        migrations.RunPython(remove_dangling_note_objects, migrations.RunPython.noop),


        migrations.AddField(
            model_name="fileproxy",
            name="job_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="extras.jobresult",
            ),
        ),
        migrations.AlterField(
            model_name="fileproxy",
            name="file",
            field=models.FileField(
                storage=nautobot.extras.models.models._job_storage, upload_to=nautobot.extras.models.models._upload_to
            ),
        ),


        migrations.CreateModel(
            name="ExternalIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "remote_url",
                    models.CharField(
                        max_length=500, validators=[nautobot.core.models.validators.EnhancedURLValidator()]
                    ),
                ),
                ("verify_ssl", models.BooleanField(default=True)),
                ("timeout", models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ("extra_config", models.JSONField(blank=True, null=True)),
                (
                    "secrets_group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.secretsgroup"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                ("ca_file_path", models.CharField(blank=True, max_length=255)),
                (
                    "headers",
                    models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
                ),
                ("http_method", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),


        migrations.AlterField(
            model_name="objectchange",
            name="changed_object_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="contenttypes.contenttype"
            ),
        ),
        migrations.AlterField(
            model_name="objectchange",
            name="related_object_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),


        migrations.AlterField(
            model_name="objectchange",
            name="user_name",
            field=models.CharField(db_index=True, editable=False, max_length=150),
        ),
        migrations.AddIndex(
            model_name="objectchange",
            index=models.Index(fields=["changed_object_type", "changed_object_id"], name="changed_object_idx"),
        ),
        migrations.AddIndex(
            model_name="objectchange",
            index=models.Index(fields=["related_object_type", "related_object_id"], name="related_object_idx"),
        ),
        migrations.AddIndex(
            model_name="objectchange",
            index=models.Index(
                fields=["user", "changed_object_type", "changed_object_id"], name="user_changed_object_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objectchange",
            index=models.Index(
                fields=["user_name", "changed_object_type", "changed_object_id"], name="user_name_changed_object_idx"
            ),
        ),


        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=100)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("name", "phone", "email")},
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=100)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                ("contacts", models.ManyToManyField(related_name="teams", to="extras.Contact")),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("name", "phone", "email")},
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),
        migrations.CreateModel(
            name="ContactAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("associated_object_id", models.UUIDField(db_index=True)),
                (
                    "associated_object_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_associations",
                        to="extras.contact",
                    ),
                ),
                (
                    "role",
                    nautobot.extras.models.roles.RoleField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_associations",
                        to="extras.role",
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_associations",
                        to="extras.status",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_associations",
                        to="extras.team",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("team", "associated_object_type", "associated_object_id", "role"),
                    ("contact", "associated_object_type", "associated_object_id", "role"),
                },
            },
            bases=(
                models.Model,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
            ),
        ),
    ]
