# Generated by Django 3.2.23 on 2023-11-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0101_externalintegration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectchange",
            name="changed_object_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="contenttypes.contenttype"
            ),
        ),
        migrations.AlterField(
            model_name="objectchange",
            name="related_object_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
