# Generated by Django 3.2.23 on 2023-12-06 21:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0102_set_null_objectchange_contenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalintegration",
            name="ca_file_path",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="externalintegration",
            name="headers",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name="externalintegration",
            name="http_method",
            field=models.CharField(blank=True, default="GET", max_length=10),
        ),
    ]
