# Generated by Django 3.2.24 on 2024-02-27 16:09

from django.db import migrations

import nautobot.extras.management


def populate_default_status_and_role_choices(apps, schema_editor):
    """Create/link default Status and Role records for ContactAssociation"""
    nautobot.extras.management.populate_status_choices(
        apps,
        schema_editor,
        models=["extras.ContactAssociation"],
    )
    nautobot.extras.management.populate_role_choices(
        apps,
        schema_editor,
        models=["extras.ContactAssociation"],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0104_contact_contactassociation_team"),
    ]

    operations = [
        migrations.RunPython(populate_default_status_and_role_choices, migrations.RunPython.noop),
    ]
