import uuid

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
from nautobot.extras.choices import DynamicGroupTypeChoices
import nautobot.extras.models.metadata
import nautobot.extras.models.mixins
import nautobot.extras.utils

# From 0111_metadata
# Generated by Django 4.2.13 on 2024-06-26 15:10

# From 0112_dynamic_group_group_type_data_migration

# From 0113_saved_views
# Generated by Django 4.2.14 on 2024-07-15 19:26


# From 0112_dynamic_group_group_type_data_migration
def set_dynamic_group_group_types(apps, schema_editor):
    """Set dynamic group group_type values appropriately."""
    DynamicGroup = apps.get_model("extras", "DynamicGroup")

    # The group_type field defaults to TYPE_DYNAMIC_FILTER
    # There are no preexisting TYPE_STATIC groups as that's a new feature
    # Any group that has children should be converted to TYPE_DYNAMIC_SET
    # NOTE: The below is actually incorrect (see migration 0116) as for some reason, during migrations ONLY,
    # Django somehow swaps the `parent` and `children` relations on DynamicGroup such that the below actually detects
    # the opposite set of groups from what would be expected.
    DynamicGroup.objects.filter(children__isnull=False).distinct().update(
        group_type=DynamicGroupTypeChoices.TYPE_DYNAMIC_SET
    )


class Migration(migrations.Migration):
    replaces = [
        ("extras", "0111_metadata"),
        ("extras", "0112_dynamic_group_group_type_data_migration"),
        ("extras", "0113_saved_views"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0110_alter_configcontext_cluster_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("data_type", models.CharField(max_length=50)),
                (
                    "content_types",
                    models.ManyToManyField(
                        limit_choices_to=nautobot.extras.utils.FeatureQuery("metadata"),
                        related_name="metadata_types",
                        to="contenttypes.contenttype",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
            managers=[
                ("objects", nautobot.extras.models.metadata.MetadataTypeManager()),
            ],
        ),
        migrations.CreateModel(
            name="ObjectMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "scoped_fields",
                    nautobot.core.models.fields.JSONArrayField(base_field=models.CharField(max_length=255), blank=True),
                ),
                ("_value", models.JSONField(blank=True, null=True)),
                ("assigned_object_id", models.UUIDField(db_index=True)),
                (
                    "assigned_object_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_metadata",
                        to="extras.contact",
                    ),
                ),
                (
                    "metadata_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_metadata",
                        to="extras.metadatatype",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_metadata",
                        to="extras.team",
                    ),
                ),
            ],
            options={
                "ordering": ["metadata_type"],
                "verbose_name_plural": "object metadata",
                "indexes": [
                    models.Index(fields=["assigned_object_type", "assigned_object_id"], name="assigned_object"),
                    models.Index(
                        fields=["assigned_object_type", "assigned_object_id", "contact"], name="assigned_object_contact"
                    ),
                    models.Index(
                        fields=["assigned_object_type", "assigned_object_id", "team"], name="assigned_object_team"
                    ),
                ],
            },
            managers=[
                ("objects", nautobot.extras.models.metadata.ObjectMetadataManager()),
            ],
        ),
        migrations.CreateModel(
            name="MetadataChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("value", models.CharField(max_length=255)),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                (
                    "metadata_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("data_type__in", ["select", "multi-select"])),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="extras.metadatatype",
                    ),
                ),
            ],
            options={
                "ordering": ["metadata_type", "weight", "value"],
                "unique_together": {("metadata_type", "value")},
            },
        ),
        migrations.RunPython(
            code=set_dynamic_group_group_types,
            reverse_code=migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("view", models.CharField(max_length=255)),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("is_global_default", models.BooleanField(default=False)),
                ("is_shared", models.BooleanField(default=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "saved view",
                "verbose_name_plural": "saved views",
                "ordering": ["owner", "view", "name"],
                "unique_together": {("owner", "name", "view")},
            },
        ),
        migrations.CreateModel(
            name="UserSavedViewAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("view_name", models.CharField(max_length=255)),
                (
                    "saved_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="extras.savedview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_view_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "view_name")},
            },
        ),
    ]
