# Generated by Django 3.2.25 on 2024-07-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0108_jobbutton_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedfield',
            name='grouping',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
