# Generated by Django 4.2.15 on 2024-08-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0113_saved_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfield",
            name="grouping",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
