# Generated by Django 4.2.15 on 2024-08-19 13:44

from django.db import migrations
from django.utils import timezone
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0114_computedfield_grouping"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="time_zone",
            field=timezone_field.fields.TimeZoneField(default=timezone.get_default_timezone_name),
        ),
        migrations.AlterModelOptions(
            name="scheduledjob",
            options={"ordering": ["name"]},
        ),
    ]
