# Generated by Django 4.2.15 on 2024-08-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0118_task_queue_to_job_queue_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="task_queues",
        ),
        migrations.RemoveField(
            model_name="scheduledjob",
            name="queue",
        ),
        migrations.AlterField(
            model_name="job",
            name="default_job_queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="default_for_jobs", to="extras.jobqueue"
            ),
        ),
    ]
