# Generated by Django 4.2.16 on 2024-10-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0119_remove_task_queues_from_job_and_queue_from_scheduled_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_singleton",
            field=models.BooleanField(default=False),
        ),
    ]
