from django.db import migrations, models


# From 0120_job_is_singleton_job_is_singleton_override
# Generated by Django 4.2.16 on 2024-11-11 07:04

# From 0121_alter_team_contacts
# Generated by Django 4.2.16 on 2024-12-03 15:32

class Migration(migrations.Migration):

    replaces = [
        ("extras", "0120_job_is_singleton_job_is_singleton_override"),
        ("extras", "0121_alter_team_contacts"),
    ]

    dependencies = [
        ("extras", "0119_remove_task_queues_from_job_and_queue_from_scheduled_job"),
    ]

    operations = [

        migrations.AddField(
            model_name="job",
            name="is_singleton",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="is_singleton_override",
            field=models.BooleanField(default=False),
        ),


        migrations.AlterField(
            model_name="team",
            name="contacts",
            field=models.ManyToManyField(blank=True, related_name="teams", to="extras.contact"),
        ),
    ]
