# Generated by Django 4.2.16 on 2024-11-05 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0119_remove_task_queues_from_job_and_queue_from_scheduled_job"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objectmetadata",
            options={"ordering": ["metadata_type", "assigned_object_id"], "verbose_name_plural": "object metadata"},
        ),
    ]
