# Generated by Django 4.2.16 on 2024-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0120_job_is_singleton_job_is_singleton_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="contacts",
            field=models.ManyToManyField(blank=True, related_name="teams", to="extras.contact"),
        ),
    ]
