# Generated by Django 4.2.22 on 2025-06-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0123_alter_joblogentry_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_ai_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="is_ai_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
