# Generated by Django 4.2.23 on 2025-07-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0123_alter_joblogentry_created"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="joblogentry",
            index=models.Index(fields=["job_result", "created"], name="extras_joblog_jr_created_idx"),
        ),
    ]
