# Generated by Django 4.2.20 on 2025-04-04 20:38

import uuid

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields
import nautobot.extras.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0123_alter_joblogentry_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflowDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("model_constraints", models.JSONField(blank=True, default=dict)),
                (
                    "model_content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("app_label", "extras"), ("model__in", ("job", "scheduledjob"))),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "Approval Workflow Definition",
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("object_under_review_object_id", models.UUIDField(db_index=True)),
                ("current_state", models.CharField(default="Pending", max_length=255)),
                (
                    "approval_workflow_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_workflows",
                        to="extras.approvalworkflowdefinition",
                    ),
                ),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                (
                    "object_under_review_content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("app_label", "extras"), ("model__in", ("job", "scheduledjob"))),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("user_name", models.CharField(editable=False, max_length=150, db_index=True)),
            ],
            options={
                "verbose_name": "Approval Workflow",
                "unique_together": {
                    (
                        "approval_workflow_definition",
                        "object_under_review_content_type",
                        "object_under_review_object_id",
                    )
                },
                "ordering": ["approval_workflow_definition"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalWorkflowStageDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("weight", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("min_approvers", models.PositiveIntegerField()),
                ("denial_message", models.CharField(blank=True, max_length=255)),
                (
                    "approval_workflow_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflow_stage_definitions",
                        to="extras.approvalworkflowdefinition",
                    ),
                ),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "approver_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_workflow_stage_definitions",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Workflow Stage Definition",
                "unique_together": {
                    ("approval_workflow_definition", "name"),
                    ("approval_workflow_definition", "weight"),
                },
                "ordering": ["approval_workflow_definition", "weight"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalWorkflowStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("state", models.CharField(default="Pending", max_length=255)),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflow_stages",
                        to="extras.approvalworkflow",
                    ),
                ),
                (
                    "approval_workflow_stage_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflow_stages",
                        to="extras.approvalworkflowstagedefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Workflow Stage",
                "unique_together": {("approval_workflow", "approval_workflow_stage_definition")},
                "ordering": ["approval_workflow", "approval_workflow_stage_definition__weight"],
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalWorkflowStageResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("comments", models.CharField(blank=True, max_length=255)),
                ("state", models.CharField(default="Pending", max_length=255)),
                (
                    "approval_workflow_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflow_stage_responses",
                        to="extras.approvalworkflowstage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflow_stage_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["approval_workflow_stage", "user"],
                "db_table": "extras_approvaluserresponse",
                "verbose_name": "Approval Workflow Stage Response",
            },
        ),
    ]
