# Generated by Django 4.2.21 on 2025-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0124_approval_workflow_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalworkflowdefinition",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="approvalworkflowdefinition",
            unique_together={("model_content_type", "priority")},
        ),
    ]
