# Generated by Django 4.2.22 on 2025-07-15 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0125_remove_job_approval_required_pre_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="approval_required",
        ),
        migrations.RemoveField(
            model_name="job",
            name="approval_required_override",
        ),
    ]
