# Generated by Django 4.2.22 on 2025-07-15 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0127_approval_workflow_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="approval_required",
        ),
        migrations.RemoveField(
            model_name="job",
            name="approval_required_override",
        ),
        migrations.RenameField(
            model_name="scheduledjob",
            old_name="approved_at",
            new_name="decision_date",
        ),
        migrations.RemoveField(
            model_name="scheduledjob",
            name="approved_by_user",
        ),
    ]
