# Generated by Django 4.2.24 on 2025-09-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0128_remove_job_approval_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalworkflow",
            name="object_under_review_content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "extras"), ("model__in", ("scheduledjob",))),
                    models.Q(("app_label", "nautobot_version_control"), ("model__in", ("pullrequest",))),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="approvalworkflowdefinition",
            name="model_content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "extras"), ("model__in", ("scheduledjob",))),
                    models.Q(("app_label", "nautobot_version_control"), ("model__in", ("pullrequest",))),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
