# Generated by Django 4.2.24 on 2025-10-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0128_remove_job_approval_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="debug_log_count",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="error_log_count",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="info_log_count",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="success_log_count",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="warning_log_count",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
