# Generated by Django 4.2.24 on 2025-09-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0074_alter_rack_u_height"),
        ("extras", "0130_jobresult_generate_log_entry_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="configcontext",
            name="device_families",
            field=models.ManyToManyField(blank=True, related_name="+", to="dcim.devicefamily"),
        ),
    ]
