# Generated by Django 4.2.25 on 2025-11-11 04:24

from django.db import migrations


def create_default_scheduledjob_workflow(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    ObjectPermission = apps.get_model("users", "ObjectPermission")
    ApprovalWorkflow = apps.get_model("extras", "ApprovalWorkflow")
    ApprovalWorkflowStage = apps.get_model("extras", "ApprovalWorkflowStage")
    ApprovalWorkflowStageResponse = apps.get_model("extras", "ApprovalWorkflowStageResponse")
    ApprovalWorkflowDefinition = apps.get_model("extras", "ApprovalWorkflowDefinition")
    ApprovalWorkflowStageDefinition = apps.get_model("extras", "ApprovalWorkflowStageDefinition")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ScheduledJob = apps.get_model("extras", "ScheduledJob")

    # --- Groups ---
    groups = {
        "nautobot-default-scheduledjob-approver": Group.objects.get_or_create(
            name="nautobot-default-scheduledjob-approver"
        )[0],
        "nautobot-default-scheduledjob-operator": Group.objects.get_or_create(
            name="nautobot-default-scheduledjob-operator"
        )[0],
        "nautobot-default-scheduledjob-architect": Group.objects.get_or_create(
            name="nautobot-default-scheduledjob-architect"
        )[0],
    }

    # --- Content Types ---
    ct_workflow = ContentType.objects.get_for_model(ApprovalWorkflow)
    ct_stage = ContentType.objects.get_for_model(ApprovalWorkflowStage)
    ct_response = ContentType.objects.get_for_model(ApprovalWorkflowStageResponse)
    ct_workflow_def = ContentType.objects.get_for_model(ApprovalWorkflowDefinition)
    ct_stage_def = ContentType.objects.get_for_model(ApprovalWorkflowStageDefinition)
    ct_scheduled_job = ContentType.objects.get_for_model(ScheduledJob)
    # --- Approval Workflow Definition ---
    awf_def, _ = ApprovalWorkflowDefinition.objects.update_or_create(
        name="Scheduled Jobs Approval - Example",
        defaults={
            "model_content_type_id": ct_scheduled_job.id,
            "model_constraints": {"job_model__job_class_name": "JobThatDoesNotExist"},
            "weight": 100,
        },
    )

    # --- Stage Definition ---
    ApprovalWorkflowStageDefinition.objects.update_or_create(
        name="Approval by nautobot-default-scheduledjob-approver",
        defaults={
            "approval_workflow_definition": awf_def,
            "sequence": 10,
            "min_approvers": 1,
            "denial_message": "This Job requires an approval from nautobot-default-scheduledjob-approver.",
            "approver_group": groups["nautobot-default-scheduledjob-approver"],
        },
    )

    # --- Object Permissions ---
    perms_data = [
        {
            "name": "nautobot-default-scheduledjobs-architect-permissions",
            "description": "Nautobot added permission aligned to the Workflow Architect persona.",
            "enabled": True,
            "actions": ["view", "add", "change", "delete"],
            "object_types": [ct_workflow_def.id, ct_stage_def.id],
            "groups": [groups["nautobot-default-scheduledjob-architect"]],
        },
        {
            "name": "nautobot-default-scheduledjobs-approver-permissions",
            "description": "Nautobot added permission aligned to the Workflow Approver persona.",
            "enabled": True,
            "actions": ["view", "change"],
            "object_types": [ct_stage.id],
            "groups": [groups["nautobot-default-scheduledjob-approver"]],
        },
        {
            "name": "nautobot-default-scheduledjobs-operator-permissions",
            "description": "Nautobot added permission aligned to the Workflow Operator persona.",
            "enabled": True,
            "actions": ["view"],
            "object_types": [ct_workflow.id, ct_stage.id, ct_response.id],
            "groups": [
                groups["nautobot-default-scheduledjob-operator"],
                groups["nautobot-default-scheduledjob-approver"],
                groups["nautobot-default-scheduledjob-architect"],
            ],
        },
    ]

    for perm in perms_data:
        obj, _ = ObjectPermission.objects.update_or_create(
            name=perm["name"],
            defaults={
                "description": perm["description"],
                "enabled": perm["enabled"],
                "actions": perm["actions"],
            },
        )
        obj.object_types.set(perm["object_types"])
        obj.groups.set(perm["groups"])
        obj.save()


def reverse_default_scheduledjob_workflow(apps, schema_editor):
    ObjectPermission = apps.get_model("users", "ObjectPermission")
    ApprovalWorkflowDefinition = apps.get_model("extras", "ApprovalWorkflowDefinition")

    ObjectPermission.objects.filter(
        name__in=[
            "nautobot-default-scheduledjobs-architect-permissions",
            "nautobot-default-scheduledjobs-approver-permissions",
            "nautobot-default-scheduledjobs-operator-permissions",
        ]
    ).delete()

    ApprovalWorkflowDefinition.objects.filter(name="Scheduled Jobs Approval - Example").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0131_configcontext_device_families"),
    ]

    operations = [
        migrations.RunPython(create_default_scheduledjob_workflow, reverse_default_scheduledjob_workflow),
    ]
