# Generated by Django 4.2.27 on 2025-12-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0132_approval_workflow_seed_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalworkflowstageresponse",
            options={
                "ordering": ["approval_workflow_stage", "created"],
                "verbose_name": "Approval Workflow Stage Response",
            },
        ),
        migrations.AddField(
            model_name="approvalworkflowstageresponse",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
