# Generated by Django 4.2.27 on 2026-01-12 16:00

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0133_alter_approvalworkflowstageresponse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="scope_filter",
            field=models.JSONField(
                default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
