# Generated by Django 4.2.27 on 2026-01-13 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extras', '0133_alter_approvalworkflowstageresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
