# Generated by Django 5.2.9 on 2026-01-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("extras", "0135_rename_taggeditem_content_type_object_id_extras_tagg_content_717743_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="clocked",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.clockedschedule",
            ),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="exchange",
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="expires",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="expire_seconds",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="headers",
            field=models.TextField(blank=True, default="{}", editable=False),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="priority",
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="routing_key",
            field=models.CharField(blank=True, default=None, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="solar",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.solarschedule",
            ),
        ),
    ]
