# Generated by Django 5.2.10 on 2026-02-03 11:24

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0136_scheduledjob_clocked_scheduledjob_exchange_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobConsoleLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("output_type", models.CharField(default="output", max_length=10)),
                ("data", models.TextField()),
                (
                    "job_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_console_logs",
                        to="extras.jobresult",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
