# Generated by Django 5.2.10 on 2026-02-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0137_jobconsoleentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="console_log",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="console_log_override",
            field=models.BooleanField(default=False),
        ),
    ]
