# Generated by Django 5.2.12 on 2026-03-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_job_console_log_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalworkflow",
            name="approval_workflow_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_workflows",
                to="extras.approvalworkflowdefinition",
            ),
        ),
        migrations.AlterField(
            model_name="approvalworkflowstage",
            name="approval_workflow_stage_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_workflow_stages",
                to="extras.approvalworkflowstagedefinition",
            ),
        ),
    ]
