# Generated by Django 5.2.11 on 2026-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_job_console_log_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileproxy",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
