# Generated by Django 4.2.28 on 2026-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0139_alter_approvalworkflow_approval_workflow_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="status",
            field=models.CharField(db_index=True, default="active", max_length=30),
        ),
    ]
