# Generated by Django 5.2.12 on 2026-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0139_alter_approvalworkflow_approval_workflow_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledjob",
            name="state",
            field=models.CharField(db_index=True, default="active", max_length=30),
        ),
    ]
