# Generated by Django 5.2.11 on 2026-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0139_alter_fileproxy_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileproxy",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
