# Generated by Django 5.2.12 on 2026-04-03 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0141_scheduledjob_state_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledjob",
            name="approval_required",
        ),
    ]
