# Generated by Django 5.2.14 on 2026-05-28 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0142_remove_scheduledjob_approval_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="date_revoked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="revocation_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminated_job_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="revoked_by_user_name",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
