# Generated by Django 5.2.15 on 2026-07-13 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0142_remove_scheduledjob_approval_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfield",
            name="output_type",
            field=models.CharField(default="text", max_length=50),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="cancel_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="canceled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminated_job_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="canceled_by_user_name",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="jobresult",
            name="date_canceled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
