# Generated by Django 5.2.14 on 2026-05-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0143_jobresult_date_terminated_jobresult_revoked_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresult",
            name="revocation_type",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
