# Generated by Django 5.2.13 on 2026-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="computedfield",
            name="output_type",
            field=models.CharField(default="text", max_length=50),
        ),
    ]
