# Generated by Django 5.2.17 on 2026-09-17 14:12

import django.core.serializers.json
from django.db import migrations

import nautobot.extras.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobhook",
            name="conditions",
            field=nautobot.extras.models.fields.ConditionsField(
                blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="conditions",
            field=nautobot.extras.models.fields.ConditionsField(
                blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
