# Generated by Django 5.2.15 on 2026-07-10 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0146_computedfield_output_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobresult",
            old_name="revocation_type",
            new_name="cancel_type",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="revoked_by",
            new_name="canceled_by",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="revoked_by_user_name",
            new_name="canceled_by_user_name",
        ),
        migrations.RenameField(
            model_name="jobresult",
            old_name="date_revoked",
            new_name="date_canceled",
        ),
    ]
