# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0003_auto_20160304_1642'),
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='object_id',
        ),
        migrations.AddField(
            model_name='secret',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='dcim.Device'),
            preserve_default=False,
        ),
    ]
