# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_userkey_add_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='public_key',
            field=models.TextField(verbose_name='RSA public key'),
        ),
    ]
