# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_auto_20160321_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ['device', 'role', 'name'], 'permissions': (('view_secret', 'Can view secrets'),)},
        ),
    ]
