# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secrets', '0003_auto_20160321_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ['device', 'role', 'name']},
        ),
        migrations.AddField(
            model_name='secretrole',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='secretroles', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='secretrole',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='secretroles', to=settings.AUTH_USER_MODEL),
        ),
    ]
