# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0004_auto_20160407_1548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together=set([('device', 'role', 'name')]),
        ),
    ]
