# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0006_auto_20160622_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
