# Generated by Django 3.1 on 2020-08-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0009_secretrole_drop_users_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
