---
# This file contains the important snippets from `ci_integration.yml` to be tested on feature branch push.
#     Images `push` is hardcoded to `false` here.
# TBD: Remove this file after review and before merge.
name: "Testing workflow"
on:  # yamllint disable
  push:
    branches:
      - "u/snaselj-4028-ci-integration-workflows"

jobs:
  container-build:
    name: "Build Container Images (GHCR Only)"
    runs-on: "ubuntu-22.04"
    if: |
      github.event_name == 'push' &&
      (github.ref_name == 'u/snaselj-4028-ci-integration-workflows')
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        # TBD: Remove this
        branch: ["develop", "next"]
    steps:
      - name: "Configuration"
        id: "config"
        shell: "bash"
        run: |
          # TBD: Replace with github.ref_name
          export BRANCH="${{ matrix.branch }}"
          # export BRANCH="${{ github.ref_name }}"
          export LATEST="false"
          export LATEST_BRANCH="false"
          export LATEST_PY="false"

          if [[ $BRANCH == "develop" ]]; then
            export LATEST_PY="true"
          fi

          if [[ "${{ matrix.python-version }}" == "3.11" ]]; then
            export LATEST_BRANCH="true"
            if [[ $LATEST_PY == "true" ]]; then
              export LATEST="true"
            fi
          fi

          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "latest=$LATEST" >> $GITHUB_OUTPUT
          echo "latest-branch=$LATEST_BRANCH" >> $GITHUB_OUTPUT
          echo "latest-py=$LATEST_PY" >> $GITHUB_OUTPUT
      # - name: "Check out repository code"
      #   uses: "actions/checkout@v3"
      # - name: "Set up QEMU"
      #   uses: "docker/setup-qemu-action@v2"
      # - name: "Set up Docker Buildx"
      #   uses: "docker/setup-buildx-action@v2"
      # - name: "Login to GitHub Container Registry"
      #   uses: "docker/login-action@v2"
      #   with:
      #     registry: "ghcr.io"
      #     username: "${{ github.actor }}"
      #     password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build `final`"
        if: |
          steps.config.outputs.latest-branch == 'true'
        # TBD: Replace DEBUG `run` with actual build action
        run: |
          echo "BRANCH: ${{ steps.config.outputs.branch }}"
          echo "IMAGE: ghcr.io/nautobot/nautobot"
          echo "LATEST: ${{ steps.config.outputs.latest }}"
          echo "LATEST-BRANCH: ${{ steps.config.outputs.latest-branch }}"
          echo "LATEST-PY: ${{ steps.config.outputs.latest-py }}"
          echo "PUSH: false"
          echo "PYTHON_VERSION: ${{ matrix.python-version }}"
          echo "TARGET: final"
      #   uses: "./.github/actions/build-nautobot-image"
      #   with:
      #     branch: "${{ steps.config.outputs.branch }}"
      #     image: "ghcr.io/nautobot/nautobot"
      #     latest: "${{ steps.config.outputs.latest }}"
      #     latest-branch: "${{ steps.config.outputs.latest-branch }}"
      #     latest-py: "${{ steps.config.outputs.latest-py }}"
      #     push: "false"
      #     python-version: "${{ matrix.python-version }}"
      #     target: "final"
      - name: "Build `final-dev`"
        # TBD: Replace DEBUG `run` with actual build action
        run: |
          echo "BRANCH: ${{ steps.config.outputs.branch }}"
          echo "IMAGE: ghcr.io/nautobot/nautobot-dev"
          echo "LATEST: ${{ steps.config.outputs.latest }}"
          echo "LATEST-BRANCH: ${{ steps.config.outputs.latest-branch }}"
          echo "LATEST-PY: ${{ steps.config.outputs.latest-py }}"
          echo "PUSH: true"
          echo "PYTHON_VERSION: ${{ matrix.python-version }}"
          echo "TARGET: final-dev"
      #   uses: "./.github/actions/build-nautobot-image"
      #   with:
      #     branch: "${{ steps.config.outputs.branch }}"
      #     image: "ghcr.io/nautobot/nautobot-dev"
      #     latest: "${{ steps.config.outputs.latest }}"
      #     latest-branch: "${{ steps.config.outputs.latest-branch }}"
      #     latest-py: "${{ steps.config.outputs.latest-py }}"
      #     push: "true"
      #     python-version: "${{ matrix.python-version }}"
      #     target: "final-dev"
