---
# This file contains the important snippets from `ci_integration.yml` to be tested on feature branch push.
#     Images `push` is hardcoded to `false` here.
# TBD: Remove this file after review and before merge.
name: "CI - Integration Branch"
on:  # yamllint disable
  push:
    branches:
      - "u/snaselj-4028-ci-integration-workflows"

jobs:
  container-build:
    name: "Build Container Images (GHCR Only)"
    runs-on: "ubuntu-22.04"
    if: "github.event_name == 'push'"
    steps:
      - name: "Configuration"
        id: "config"
        shell: "bash"
        run: |
          ref="${{ github.ref }}"
          branch="${ref#refs/heads/}"

          case "$branch" in
            "develop")
              min_python_version="3.7"
              max_python_version="3.10"
              ;;
            "next")
              min_python_version="3.8"
              max_python_version="3.11"
              ;;
            "u/snaselj-4028-ci-integration-workflows")
              min_python_version="3.7"
              max_python_version="3.11"
              # Simplify branch name, to be able to use it as an image tag.
              export branch="snaselj"
              ;;
            *)
              echo "Invalid branch $branch"
              exit 1
              ;;
          esac

          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "min-python-version=$min_python_version" >> $GITHUB_OUTPUT
          echo "max-python-version=$max_python_version" >> $GITHUB_OUTPUT
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"
      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build `final` Max"
        uses: "./.github/actions/build-nautobot-image"
        with:
          branch: "${{ steps.config.outputs.branch }}"
          image: "ghcr.io/nautobot/nautobot"
          latest: false
          push: false
          python-version: "${{ steps.config.outputs.max-python-version }}"
          target: "final"
      - name: "Build `final-dev` Min"
        uses: "./.github/actions/build-nautobot-image"
        with:
          branch: "${{ steps.config.outputs.branch }}"
          image: "ghcr.io/nautobot/nautobot-dev"
          latest: true
          push: false
          python-version: "${{ steps.config.outputs.min-python-version }}"
          target: "final-dev"
      - name: "Build `final-dev` Max"
        uses: "./.github/actions/build-nautobot-image"
        with:
          branch: "${{ steps.config.outputs.branch }}"
          image: "ghcr.io/nautobot/nautobot-dev"
          latest: false
          push: false
          python-version: "${{ steps.config.outputs.max-python-version }}"
          target: "final-dev"
