# Generated by Django 5.2.4 on 2025-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudservice",
            name="cloud_networks",
            field=models.ManyToManyField(
                blank=True,
                related_name="cloud_services",
                through="cloud.CloudServiceNetworkAssignment",
                through_fields=("cloud_service", "cloud_network"),
                to="cloud.cloudnetwork",
            ),
        ),
    ]
