# Generated by Django 4.2.13 on 2024-06-12 04:06

from django.db import migrations, models

import nautobot.extras.utils


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudtype",
            name="content_types",
            field=models.ManyToManyField(
                limit_choices_to=nautobot.extras.utils.FeatureQuery("cloud_types"),
                related_name="cloud_types",
                to="contenttypes.contenttype",
            ),
        ),
    ]
