from django.db import migrations
import nautobot.core.models.fields
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.tree_queries


# From 0002_auto_slug
# Generated by Django 3.1.13 on 2021-08-05 03:23

# From 0003_mptt_to_tree_queries
# Generated by Django 3.2.16 on 2022-12-15 19:06

# From 0004_change_tree_manager_on_tree_models
# Generated by Django 3.2.16 on 2022-12-23 02:46

# From 0005_rename_foreign_keys_and_related_names
# Generated by Django 3.2.16 on 2023-01-24 18:45


class Migration(migrations.Migration):

    replaces = [
        ("tenancy", "0002_auto_slug"),
        ("tenancy", "0003_mptt_to_tree_queries"),
        ("tenancy", "0004_change_tree_manager_on_tree_models"),
        ("tenancy", "0005_rename_foreign_keys_and_related_names"),
    ]

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tenantgroup",
            name="slug",
            field=nautobot.core.models.fields.AutoSlugField(
                blank=True, max_length=100, populate_from="name", unique=True
            ),
        ),

        migrations.RemoveField(
            model_name="tenantgroup",
            name="level",
        ),
        migrations.RemoveField(
            model_name="tenantgroup",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="tenantgroup",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="tenantgroup",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="tenantgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="tenancy.tenantgroup",
            ),
        ),

        migrations.AlterModelManagers(
            name="tenantgroup",
            managers=[
                ("objects", nautobot.core.models.tree_queries.TreeManager()),
            ],
        ),

        migrations.AlterModelOptions(
            name="tenant",
            options={"ordering": ["tenant_group", "name"]},
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="group",
            new_name="tenant_group",
        ),
    ]
