# Generated by Django 3.1.14 on 2022-03-18 10:52

from django.db import migrations
import nautobot.extras.models.tags


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0031_auto_tag_taggeditem"),
        ("tenancy", "0002_auto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="tags",
            field=nautobot.extras.models.tags.TaggableManagerField(through="extras.TaggedItem", to="extras.Tag"),
        ),
    ]
