# Generated by Django 3.2.16 on 2022-12-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_auto_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantgroup",
            name="level",
        ),
        migrations.RemoveField(
            model_name="tenantgroup",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="tenantgroup",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="tenantgroup",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="tenantgroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="tenancy.tenantgroup",
            ),
        ),
    ]
