# Generated by Django 3.2.16 on 2022-12-23 02:46

from django.db import migrations
import nautobot.core.models.tree_queries


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_mptt_to_tree_queries"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="tenantgroup",
            managers=[
                ("objects", nautobot.core.models.tree_queries.TreeManager()),
            ],
        ),
    ]
