# Generated by Django 3.2.16 on 2023-01-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_mptt_to_tree_queries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={"ordering": ["tenant_group", "name"]},
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="group",
            new_name="tenant_group",
        ),
    ]
