# Generated by Django 3.2.18 on 2023-03-15 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0006_created_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="tenantgroup",
            name="slug",
        ),
    ]
